### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by alimakki** [StreisandEffect/streisand#1000]
Update the internationalized README files to reflect changes issued in the following [commit](https://github.com/StreisandEffect/streisand/commit/0272b14f38c40df4b8af33691e09711176b3a4b1).

~~Additionally, PR #996 bumped the minimum version of Ansible to v2.4.0.0, and thus must also be reflected in all READMEs.~~

- [x] Français
- [x] 简体中文
- [x] Русский

Edit: removed English

**Comment by alimakki** [comment]
PR #1004 issued for French

**Comment by levleontiev** [comment]
https://github.com/StreisandEffect/streisand/pull/1024
Please see it here.

**Comment by nickolasclarke** [comment]
#1086 resolves this. closing.
