### ISSUE TITLE
Issue with Streisand utilizing a separate VPN as it's "Public" connection

### ISSUE THREAD

**Issue by rjsears** [StreisandEffect/streisand#1012]
I am not sure if this is the correct place to post this, but I could not seem to locate a forum or wiki for Streisand so I am posting here. If there is a better place, please let me know.

I want to setup Streisand to connect to a VPN server for all of its internet connectivity. So I have a deployed server currently with a single network interface that is the Streisand server. I want that server to have a VPN connection to another VPN and for all clients connecting to the Streisand server to be using that VPN as their internet as opposed to the live public IP on the dedicated droplet. 

I have openvpn configured on the streisand server and it works (all traffic from the server gert routed over the VPN) but none of my clients can connect to the Streisand server once the OpenVPN VPN connection goes active.

I am sure I am missing something simple (like adding another nic if necessary).

**Comment by alimakki** [comment]
Moved to [discussions](https://github.com/StreisandEffect/discussions/issues/54).
