### ISSUE TITLE
where is the "generated-docs" file directry

### ISSUE THREAD

**Issue by lublues** [StreisandEffect/streisand#1020]
i install streisand on my linode localhost,but after i finish the installation,i can not find the "generated-docs " on the sterisand files directry.

**Comment by nopdotcom** [comment]
Could you refile this using the template? The details really help sometimes.

**Comment by lublues** [comment]
@nopdotcom i reinstall it on the vps,the firstime i install in another vps..so i can find the generated-docs files  directry

**Comment by cpu** [comment]
@lublues Specifically we need the answers to these questions to reopen this issue:

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
