### ISSUE TITLE
Out of memory when install Digital Ocean instance

### ISSUE THREAD

**Issue by remini1998** [StreisandEffect/streisand#1025]
### Expected behavior:
success to generate the stunnel Markdown mirror page
### Actual Behavior:
TASK [stunnel : Generate the stunnel Markdown mirror page] ****************************************************************************************************************
changed: [162.243.186.189] => (item={'key': u'fr', 'value': {u'file_suffix': u'-fr', u'tor_locale': u'fr', u'language_name': u'Fran\xe7ais'}})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [162.243.186.189]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

### Steps to Reproduce:
1. Use default settings and install instance on Digital Ocean and choose Region 8.

### Suggestions
Increasing the swap memory may help.
[https://stackoverflow.com/questions/20111242/how-to-avoid-errno-12-cannot-allocate-memory-errors-caused-by-using-subprocess](https://stackoverflow.com/questions/20111242/how-to-avoid-errno-12-cannot-allocate-memory-errors-caused-by-using-subprocess)

### Ansible Information

* Ansible version: 2.4.1.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  17.04
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 9582ba4ac8d497a0a1dabdca3c1fe485bda5be27
* Streisand Git clone has untracked changes: 
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by remini1998** [comment]
I thought the problem is on the targeted VPS, but I finally find that it's on the localhost.
I resized the localhost VPS and solved the problem.

**Comment by cpu** [comment]
@remini1998 Great! Glad to hear you were able to sort out the problem :-)
