### ISSUE TITLE
failed issues about stunnel

### ISSUE THREAD

**Issue by lublues** [StreisandEffect/streisand#1027]
TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.005376", "end": "2017-10-31 07:09:08.697012", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-31 07:09:08.691636", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [ssh : Restart SSH] ********************************************

RUNNING HANDLER [openconnect : Restart ocserv] *********************************

RUNNING HANDLER [openconnect : Restart rsyslog for OpenConnect] ****************

RUNNING HANDLER [l2tp-ipsec : Restart rsyslog for Libreswan] *******************

RUNNING HANDLER [dnsmasq : Restart dnsmasq] ************************************

RUNNING HANDLER [openvpn : Restart OpenVPN] ************************************

RUNNING HANDLER [tinyproxy : Restart Tinyproxy] ********************************

RUNNING HANDLER [stunnel : Restart stunnel] ************************************
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry

PLAY RECAP *********************************************************************
localhost                  : ok=300  changed=229  unreachable=0    failed=1

i added it on my vps localhosting,but it failed.

**Comment by nopdotcom** [comment]
Could you supply the information in the issue template?

**Comment by cpu** [comment]
@lublues Seconding @nopdotcom's request for the questions from the issue template being answered.

In particular, what is the provider for this VPS? Is it an OpenVZ VPS? I'm 99% sure it is not a provider that is supported by Streisand based on this error:
> interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)

**Comment by cpu** [comment]
I'm going to close this issue since we haven't heard back with the required information.
