### ISSUE TITLE
[Feature Request] Should allow to choose different SSH port when connecting to other providers server

### ISSUE THREAD

**Issue by xbeta** [StreisandEffect/streisand#1030]
For example, I have a server with `ssh_port` sets to `2222`, not the standard `22`.  I can modify the hardcoding now and change that:

```
  # Create an inventory file string on the fly
  read -r -d '' TEMPL << EOF || true
[localhost]
localhost ansible_connection=local ansible_python_interpreter=python
[streisand-host]
$SERVER_IP ansible_user=$SSH_USER ansible_port=2222
EOF
```

**Comment by cpu** [comment]
Hi @xbeta, thanks for the feature request.

> when connecting to other providers server

Just to make sure I understand 100%: You're asking for using Streisand to provision an **existing server** that has SSHD running on a port other than 22? E.g. the case where you select "  8. Existing Server (Advanced)" from `./streisand`?

**Comment by cpu** [comment]
Closing this issue - there's outstanding information required to make it actionable.

If you're interested I suggest that you open a [discussions repo](https://github.com/StreisandEffect/discussions) issue expanding on the use-case of this feature request.

Thanks!
