### ISSUE TITLE
Streisand errors when setting up server: "boto3 required for this module"

### ISSUE THREAD

**Issue by Blubberx** [StreisandEffect/streisand#1031]
### Expected behavior:

I'm trying to set up a Streisand server on AWS, and have followed the instructions, but keep getting errors just after the "Streisand will now set up your server" message.

### Actual Behavior:

Error message "boto3 required for this module. to retry, use: --limit @/Users/remy/streisand/playbooks/amazon.retry"

### Steps to Reproduce:

1. Run Streisand, choose Amazon and default settings and AWS access keys
2. Get error message "boto3 required for this module. to retry, use: --limit @/Users/remy/streisand/playbooks/amazon.retry"
3. Run "./streisand --limit @/Users/user/streisand/playbooks/amazon.retry"
4. Get same error.

I have installed boto using the sudo pip install boto command. If I run "sudo pip install boto3" I get exceptions uninstalling six-1.4.1.

[ contents of `streisand-diagnostics.md` here ]

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the EC2 Server] ****************************************************************************

TASK [Gathering Facts] *************************************************************************************
ok: [localhost]

TASK [Set the AWS Region fact] *****************************************************************************
ok: [localhost]

TASK [Set the AWS VPC ID fact] *****************************************************************************
skipping: [localhost]

TASK [Set the AWS VPC Subnet ID fact] **********************************************************************
skipping: [localhost]

TASK [ec2-security-group : Create the EC2 security group] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 required for this module"}
	to retry, use: --limit @/Users/user/streisand/playbooks/amazon.retry

PLAY RECAP *************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

##### *Output from `git rev-parse HEAD` in your Streisand directory :* fc5eae566bdf0d245b4b79bf1b9a8113c56d3a36

**Comment by nopdotcom** [comment]
Python environments can get really messed up over time. (Ask me how I know.) I think you might have modules with conflicting dependencies.

The easiest thing to do (well, easiest for me!) is suggest you install the dependencies in a virtualenv. See https://github.com/nopdotcom/streisand/blob/builder-scripts/util/venv-dependencies.sh (but be aware it's not perfect yet). If you speak virtualenv, start reading at around line 88.

Another alternative is to set up a cloud machine somewhere from scratch, then install just the Streisand dependencies.

**Comment by alimakki** [comment]
I found a workaround that appears to work, could you give the following command a try:

`sudo pip install boto3 --ignore-installed six` and let me know if that resolves your issue?

**Comment by Blubberx** [comment]
@alimakki Many thanks, this appears to have done the trick! 

I had tried `sudo pip install boto3 --please just do it` but this is even better ;-)

@nopdotcom Thanks also for taking the trouble to reply.

**Comment by alimakki** [comment]
@Blubberx glad I could help.
