### ISSUE TITLE
Key mismatches - GPG not emitting keys

### ISSUE THREAD

**Issue by PsySc0rpi0n** [StreisandEffect/streisand#1033]
### Expected behavior:
 key matches
 Fingerprint matches
### Actual Behavior:
Fingerprint doesn't matches because streisand files have "Keyfingerprint = " string in there and this GPG version doesn't emit it. It just prints the fingerprint itself. But not those words.

Side note: this script and this problem occurred while trying to run the script in a Debain 9.2 server, Kerlnel 4.9.0-4-amd64, SMP Debian 4.9.51-1
### Steps to Reproduce:
1. Follow pre-requisites
2. When script is installing necessary packages, 2 of them needed their names changed to match Debian package names
3. When script is working, the described problem occurs! 

Side note: issue was fixed locally

### Ansible Information

* Ansible version: 2.4.1.0
* Ansible system: Linux
* Host OS: Debian
* Host OS version:  9.2
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 02b69ba3ad06d036aae2c3647f19d9bf64a2799f
* Streisand Git clone has untracked changes: yes
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: False
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: False
* SSH forward user enabled: False
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by nopdotcom** [comment]
You can use any builder machine you want (I mostly use Macs). The only official server target is Ubuntu 16.04 LTS though, even if you're deploying to localhost.

I would ask people for a PR supporting Debian 9, but it depends on the scope of the changes; we can't maintain two separate paths if they diverge much.

@PsySc0rpi0n, could you test with an Ubuntu 16.04 LTS target, and re-open this if there's a problem?

**Comment by cpu** [comment]
> Side note: this script and this problem occurred while trying to run the script in a Debain 9.2 server, Kerlnel 4.9.0-4-amd64, SMP Debian 4.9.51-1

Echoing @nopdotcom's comment: This is the root of the problem. Streisand only supports Ubuntu 16.04 servers.

> I would ask people for a PR supporting Debian 9, but it depends on the scope of the changes; we can't maintain two separate paths if they diverge much.

I'm fairly cold on this idea. I don't think there is a strong reason to support Debian for the server OS and it will necessarily involve carrying some divergences in master that will bite us over time. We don't have sufficient testing of the currently supported options, I'm not eager to add more without strong justification! :-)

**Comment by PsySc0rpi0n** [comment]
Sure... I understand all the comments above.
And just a justified suggestion:
Ig that "Key fingerprint = " is removed from the script, then it will continue to be compatible with older GPG versions as well as newer ones, so nothing would be broke with changes like that!

At the moment I don't have an Ubuntu SO to test the problem in it! If it happens that I need to install an Ubuntu SO I'll give it a try!

Thanks
PsySc0rpi0n
