### ISSUE TITLE
Tor Browser 7.0.9 for Windows download for 404 failed.

### ISSUE THREAD

**Issue by jkyeo** [StreisandEffect/streisand#1043]
Tor Browser 7.0.9 for Windows download with 404 failed.
Below is the reason:

> Note: Tor Browser 7.0.9 is a security bugfix release for macOS and Linux users only. Users on Windows are not affected and stay on Tor Browser 7.0.8.

So please fix the script to download 7.0.8 for windows.

**Comment by ExpatRights** [comment]
Tor Browser is almost useless in China !!  thing never actually connects to Tor lol..

**Comment by cpu** [comment]
@ExpatRights Please start a new thread in the [Streisand discussions repository](https://github.com/StreisandEffect/discussions) if you would like to share user experience related to using the Tor browser in China. It's not related to this bug/issue.

Thanks!

**Comment by alimakki** [comment]
Tor browser has been updated to 7.0.10 across all platforms.

Thanks!
