### ISSUE TITLE
Windows 7 L2TP documentation out of date

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#1057]
As of 00de2fbc91481700c4c9f53d9c8394ffcfa0f476, there are new instructions for Windows L2TP setup. They work well on Windows 10 for sure.

If you're running Windows 7, you're stuck with manual configuration of the VPN. The manual configuration instructions appear somewhat out of date. (Yes, L2TP is possible to automate on Win 7 too, but it involves a PowerShell script with embedded C#. Probably possible to do it with the NSIS installer.)

If you're running Windows 10, the manual instructions are *definitely* out of date.

Adding the PowerShell L2TP setup would normally trigger re-translation of the instructions. I would suggest holding off on that for a little bit for me to revise that section further.

**Comment by adityarpillai** [comment]
Created PR #1066 for the manual instructions on Windows 10.

**Comment by nopdotcom** [comment]
Thank you for #1066! In celebration, I'm renaming the bug :‐)
