### ISSUE TITLE
[Feature Request] Ability to change region

### ISSUE THREAD

**Issue by thebeastgamer25** [StreisandEffect/streisand#1060]
This is a basic suggestion, but something we should do.

Also, add options for more user profiles., since it could run out quick.

**Comment by cpu** [comment]
Hi @thebeastgamer25,

Feature requests & general topics of discussion should be opened as issues on the [discussions repo](https://github.com/streisandeffect/discussions).

This is ~= a duplicate of https://github.com/StreisandEffect/discussions/issues/17 - I recommend you comment & follow that issue.

Thanks!
