### ISSUE TITLE
GCP regions need updating

### ISSUE THREAD

**Issue by ThePowerOfDreams** [StreisandEffect/streisand#1061]
### Expected behavior:
Can choose any valid GCP region and zone

### Actual Behavior:
Can choose only some GCP regions

### Reference
https://cloud.google.com/compute/docs/regions-zones/

Also, please use the GCP naming scheme so we actually know where the VM will end up; "13. Western Europe (Belgium B)" should be named "13. europe-west1-b (St. Ghislain, Belgium)"

**Comment by nopdotcom** [comment]
Is there a good way to get this information through an API or command-line tool?

**Comment by ThePowerOfDreams** [comment]
What was I thinking?! Hardcoding them caused this issue in the first place.

There absolutely is:
https://cloud.google.com/compute/docs/reference/latest/regions/list

**Comment by nopdotcom** [comment]
The disappointing thing about that service is you need an authenticated project ID. But yeah, it will work well enough in a maintenance script.

If I get ambitious I'll put up a GAE app to proxy the region information.

**Comment by ThePowerOfDreams** [comment]
You have to authenticate anyway during the process, so why proxy it? Fetch the regions and zones available to the user, present the options, then away you go.

**Comment by alimakki** [comment]
For people who live in countries where Google is be blocked, this could be a showstopper for them and render provisioning in GCP near useless.

**Comment by ThePowerOfDreams** [comment]
If they can't access the provisioning API to create the VPC network, firewall rules, and instance (as per the Ansible playbook), then how is it any worse if they also can't access that same API to retrieve the list of regions available to them as I'm suggesting?

**Comment by ThePowerOfDreams** [comment]
To be clear, I'm not suggesting the region check should be made before they choose the Google option in the streisand script, only after.

**Comment by cpu** [comment]
I think fetching region information at runtime is a lot of complexity for fairly low reward. I imagine that the region options change fairly infrequently and having a slightly stale list missing new options doesn't present a very significant drawback for most users.

@ThePowerOfDreams Do you want to submit a PR to add the missing entries & update the labels how you think they should be?

**Comment by ThePowerOfDreams** [comment]
You make a fine point.

Okay, that's fair; I will endeavour to do this in the next week or two.

**Comment by cpu** [comment]
Great! Thank you!
