### ISSUE TITLE
Disable DNS Routing

### ISSUE THREAD

**Issue by kamikazechaser** [StreisandEffect/streisand#1062]
I have an AWS instance in Singapore, however DNS queries are being routed to Google (USA) by dnsmasq. This might be This results in slower resolutions. Is it possible to manually disable this behavior on a already running instance and fully stick to the hosts DNS? Tested on latest streisand release (date of issue). Behavior replicated on SSH, Shadowsocks and OpenVPN methods.

**Comment by cpu** [comment]
Hi @kamikazechaser - this is a question more appropriate for the Streisand discussions repo so I've opened https://github.com/StreisandEffect/discussions/issues/66. I'm going to close this issue and reply over there instead. Thanks!
