### ISSUE TITLE
client-config-dir directive not working for me

### ISSUE THREAD

**Issue by damko** [StreisandEffect/streisand#1078]
I report here what I've already written in #842 

I'm trying to recover after the early expiration of the ca.crt. 
I tried to use the directive in order to force a static IP for a client which also acts as a server for other applications

    client-config-dir /etc/openvpn/ccd

but it doesn't work for me.

When the client tries to connect, syslog says:

    Could not access file '/etc/openvpn/ccd/scheme.angle' Permission denied (errno=13)

The file is there. I tried with the silliest rights with no difference. I even moved the folder to /tmp it's even worse.

It feels like there's a jail or something in the way.

I thought that this was due to a conflict between the dynamic pool range and the ip that I've set in ccd/ but if I set a pool range in the config files (server.conf server-udp.conf) I get a warning in the syslog saying that the pool has been already set therefore the line will be ignored. It looks like the service is started with --ifconfig-pool but I couldn't find any trace of it.

What am I missing? Any tip?

**Comment by cpu** [comment]
Hi @damko - since the problem you're reporting is from instructions in #842 that aren't merged/present in the repo I'd prefer that we keep discussion over there. I'm going to close this issue so that the conversation can be centralized.
