### ISSUE TITLE
i got this problem  "pycurl required for this module"

### ISSUE THREAD

**Issue by GPX-NSlog** [StreisandEffect/streisand#1096]
when i Execution ./streisand ,This problem occurs
```
TASK [genesis-linode : Create the server] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "pycurl required for this module"}
```
### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by cpu** [comment]
@GPX-NSlog - Have you installed the MacOS dependencies mentioned in the README? Specifically it says MacOS users need to run these two commands before Streisand:

```
sudo easy_install pip
sudo pip install pycurl
```

Can you try that and report back if it solved your problem?

Thanks!
