### ISSUE TITLE
commit 36a46f7 (BIP wordlists) violates TOR config policy and breaks TOR -> breaking Streisand default deployment

### ISSUE THREAD

**Issue by aldou** [StreisandEffect/streisand#1103]
### ExecSummary:
The adoption of BIP wordlists includes dashes "-" between words, which violates TOR configuration file standards. This prevents TOR from starting, and consequently Streisand from completing the default deployment. 

### Expected behavior:
TOR runs, Streisand deployment succeeds.

### Actual Behavior:
TOR fails to validate the configuration file /etc/tor/torrc and terminates. Consequently, this prevents the deployment to succeed with following error:
```
TASK [tor-bridge : Wait until obfs4proxy information has shown up in its state file] *************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string node-id in /var/lib/tor/pt_state/obfs4_state.json"}
```

### Steps to Reproduce:
./streisand
select default setup

### Additional Details:
TOR complains that the auto generated names for the 'Nickname' field in /etc/tor/torrc contain a dash "-", which violates TOR configuration file standards, as only the characters [a-zA-Z0-9] are allowed for this field. 

This regression was introduced by commit: https://github.com/StreisandEffect/streisand/commit/36a46f765b82ab10a4107b7a00193bc4cee8462f

TOR stout error is:
```
[warn] Failed to parse/validate config: Nickname 'monkey-glare', nicknames must be between 1 and 19 characters inclusive, and must contain only the characters [a-zA-Z0-9].
[err] Reading config failed--see warnings above.
```

### Workaround:
While deploying Streisand, the following message is displayed for 300 seconds before timing out:
`TASK [tor-bridge : Wait until obfs4proxy information has shown up in its state file]`
During this timeframe, open another terminal window and edit TOR config file
`nano /etc/tor/torrc `
verify that the line starting with Nickname does not include dashes "-", if so delete the dash and save the file. Start TOR: 
`systemctl start tor`

**Comment by cpu** [comment]
HI @aldou, @garrettjj - This problem should be resolved now using the latest code from master. I reverted the BIP wordlist change pending a fix for the tor daemon config policy requirements.

Apologies for the breakage. Thanks for reporting the bug! Tor is one of the areas we can't test in Travis/CI and the integration test work that would have caught this regression isn't quite finished (close though!)
