### ISSUE TITLE
Streisand fails to open all of the necessary ports across every service in Azure security group

### ISSUE THREAD

**Issue by lgnorance** [StreisandEffect/streisand#1113]
### Expected behavior:
Streisand should be able to pass this step in the installation process without errors whilst deploying to an Azure server
### Actual Behavior:
`TASK [azure-security-group : Open all of the necessary ports across every service in the Azure security group] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got multiple values for keyword argument 'id'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 716, in <module>\n    main()\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 712, in main\n    AzureRMSecurityGroup()\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 542, in __init__\n    supports_check_mode=True)\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 285, in __init__\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 641, in exec_module\n    self.results['state'] = self.create_or_update(results)\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 685, in create_or_update\n    parameters.security_rules.append(create_rule_instance(rule))\n  File \"/var/folders/_3/py2snsxj2q916mbqgcb9135w0000gn/T/ansible_E0iMKQ/ansible_module_azure_rm_securitygroup.py\", line 452, in create_rule_instance\n    etag=rule.get('etag', None)\nTypeError: __init__() got multiple values for keyword argument 'id'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/Users/me/streisand/playbooks/azure.retry

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1 `

### Steps to Reproduce:
1. I'm currently running the latest version of OSX (10.13.2) but have also tried this in Ubuntu 16.04.3 with the same error, it appears to be something on my Azure account causing the problem
2. The only thing I have on my Azure account is currently an Algo Server (https://github.com/trailofbits/algo), I wish to deploy both in Azure if it is possible.

`

### Ansible Information

{% if 'localhost' in hostvars %}
{% if 'ansible_version' in hostvars['localhost'] %}
* Ansible version: {{ hostvars['localhost']['ansible_version']['full'] }}
{% else %}
* Ansible version: Unknown
{% endif %}
{% if 'ansible_system' in hostvars['localhost'] %}
* Ansible system: {{ hostvars['localhost']['ansible_system'] }}
{% else %}
* Ansible system: Unknown
{% endif %}
{% if 'ansible_distribution' in hostvars['localhost'] %}
* Host OS: {{ hostvars['localhost']['ansible_distribution'] }}
{% else %}
* Host OS: Unknown
{% endif %}
{% if 'ansible_distribution_version' in hostvars['localhost'] %}
* Host OS version:  {{ hostvars['localhost']['ansible_distribution_version'] }}
{% else %}
* Host OS version: Unknown
{% endif %}
{% if 'ansible_python_interpreter' in hostvars['localhost'] %}
* Python interpreter: {{ hostvars['localhost']['ansible_python_interpreter'] }}
{% else %}
* Python interpreter: Unknown
{% endif %}
{% if 'ansible_python_version' in hostvars['localhost'] %}
* Python version: {{ hostvars['localhost']['ansible_python_version'] }}
{% else %}
* Python version: Unknown
{% endif %}
{% else %}
* No 'localhost' in hostvars. Ansible information unknown.
{% endif %}

### Streisand Information

* Streisand Git revision: {{ streisand_diagnostics_git_rev.stdout }}
* Streisand Git clone has untracked changes: {{ streisand_diagnostics_git_untracked.stdout }}
* Genesis role: {{ streisand_genesis_role | default("None") }}
* Custom SSH key: {{ streisand_ssh_private_key != "~/.ssh/id_rsa" }}

### Enabled Roles

* Shadowsocks enabled:  {{ streisand_shadowsocks_enabled }}
* Wireguard enabled: {{ streisand_wireguard_enabled }}
* OpenVPN enabled: {{ streisand_openvpn_enabled }}
* stunnel enabled: {{ streisand_stunnel_enabled }}
* Tor enabled: {{ streisand_tor_enabled }}
* Openconnect enabled: {{ streisand_openconnect_enabled }}
* TinyProxy enabled: {{ streisand_tinyproxy_enabled }}
* SSH forward user enabled: {{ streisand_ssh_forward_enabled }}
* L2TP enabled: {{ streisand_l2tp_enabled }}
* Configured number of VPN clients: {{ vpn_clients }}`

**Comment by alimakki** [comment]
Hi @lgnorance,

the error you're seeing is due to an API change with Microsoft.

You can follow the bug with [Ansible here](https://github.com/ansible/ansible/issues/33657) if you wish. Unfortunately we have no known workarounds for this at the moment.

**Comment by cpu** [comment]
I'm going to close this issue for now since it's a problem with an upstream dependency.

@lgnorance - You should be able to use one of the other supported cloud providers without encountering this error (DigitalOcean, Linode, AWS, GCE, etc).

Thanks!
