### ISSUE TITLE
OpenVPN CA expires after 30 days

### ISSUE THREAD

**Issue by king-jam** [StreisandEffect/streisand#1115]
### Expected behavior:
OpenVPN CA Expiration to be 5 years or 1825 days per https://github.com/StreisandEffect/streisand/blob/89d18bb1d1c45ff0af9348256a1299b15b17e025/playbooks/roles/openvpn/vars/main.yml#L2
### Steps to Reproduce:
1. 
Deploy given default steps. No customization of setup minus removal of TOR.

```
### Ansible Information

* Ansible version: 2.4.1.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: dcc4a0687eaf99303e8cdbb652474003fe6cc5ba
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-linode
* Custom SSH key: True

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5
```

### Additional Details:
```
root@localhost:/etc/openvpn# cat ca.crt | openssl x509 -noout -enddate
notAfter=Dec 18 22:21:39 2017 GMT
```
```
root@localhost:/etc/openvpn/few.comic# cat ca.crt | openssl x509 -noout -enddate
notAfter=Dec 18 22:21:39 2017 GMT
```

**Comment by king-jam** [comment]
Solved. This was fixed with: https://github.com/StreisandEffect/streisand/commit/7f51e8381e62bbe652095788c817fcd217b6d4fa#diff-86fe70a4057f3201ec0051f1cafb88f5

I just happened to pull a version 3 days before the fix was implemented. Can anyone provide a workaround to avoid redeploying? Not 100% up on Certificate management so I don't know if I can revoke and regenerate the CA, whether I'll need to update all my clients, or any other workarounds.

**Comment by alimakki** [comment]
Hi @king-jam,

Sorry to see that you've run into this issue. There's a thread in [Streisand Discussions](https://github.com/StreisandEffect/discussions/issues/69) related to this bug.

While you could regenerate your CAs, you would have to sign new client and server certificates with the new CA, modify your profiles individually which would be an error prone process. 

The easiest course of action here is to re-deploy Streisand using the latest master.

Again, sorry for the inconvenience.

**Comment by king-jam** [comment]
@alimakki no worries. I'm more angry I deployed 3 days before the bug was fixed! So close to avoid it.

I re-deployed because my research led me to the same conclusion.

I wish there was some notification mechanism on a bug like that so folks would have realized a couple days into a fresh deployment instead of at the 30 day mark but 'alas, open source vs. paid option. Can't complain...nor do I think there is really any way to do that via Github.

**Comment by cpu** [comment]
> I wish there was some notification mechanism on a bug like that so folks would have realized a couple days into a fresh deployment instead of at the 30 day mark but 'alas, open source vs. paid option. Can't complain...nor do I think there is really any way to do that via Github.

I think in the future we'll be evaluating having a low traffic mailing list specifically for announcements of releases & bugs like this. Stay tuned :-)
