### ISSUE TITLE
VPN bundles Double / Triple / Quad

### ISSUE THREAD

**Issue by canusuck** [StreisandEffect/streisand#1117]
Hi, tell me pls how can I create a Double / Triple / Quad bundle for VPN
Particularly interested in the protocols in Ipsec and WareGuard
How best to do this. pls help me
ty u in advance

**Comment by cpu** [comment]
Hi @canusuck 

I don't understand your question but since it isn't related to the Streisand codebase can you please open a new issue [on the Streisand discussions repository](https://github.com/StreisandEffect/discussions/issues)? You'll need to explain what a "VPN Bundle" is.

Thanks
