### ISSUE TITLE
Update FR instructions

### ISSUE THREAD

**Issue by alimakki** [StreisandEffect/streisand#1123]
Tracking issue to translate the changes of the following PRs in French:

- [x] Added the 'Mode' setting under 'Additional TLS Auth' settings for OpenVpn for Ubuntu 17.10  #1121 
- [x] Update instructions for Firefox certificate import #1122 
- [x] WireGuard effective in China note https://github.com/StreisandEffect/streisand/pull/1119

**Comment by cpu** [comment]
I added #1119 to the end of the list. Thanks :-)

**Comment by alimakki** [comment]
PR #1165 issued.
