### ISSUE TITLE
add Alibaba Cloud support

### ISSUE THREAD

**Issue by hadifarnoud** [StreisandEffect/streisand#1128]
Alibaba Cloud is relatively new player and it's big in China/Asia. It's very much tries to be AWS of Asia.

It will be appreciated by many if you add Alibabacloud support.

**Comment by cpu** [comment]
Hi @hadifarnoud,

Please post feature requests in the [Streisand discussions repository](https://github.com/StreisandEffect/discussions).

**Comment by alimakki** [comment]
Issue opened in [discussions](https://github.com/StreisandEffect/discussions/issues/80).

**Comment by nickolasclarke** [comment]
this is also somewhat a dupe of #889.
