### ISSUE TITLE
How to prevent tor bridge/relay scanning/discovery

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1137]
The Tor Project (and others) automatically scan the internet for new Tor bridges/relays and include them in their own list. What happens when I set up my own Streisand server on a VPS? How can I prevent that my bridge address is scanned and automatically added to their (and others) database, that is, to truly keep it private?

**Comment by alimakki** [comment]
@baimafeima, by default Streisand elects to not publish the relay's service descriptor. You can verify this setting [here](https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/tor-bridge/defaults/main.yml).

**Comment by baimafeima** [comment]
@alimakki Thanks, this is exactly the kind of information I was looking for. I hope this is all that needs to be done to ensure privacy. You never know what state actors are capable of in discovering networks _during_ the actual installation process of the Streisand server. It would be great if this could also be documented on the main page for new users.

**Comment by cpu** [comment]
Since the original question has been answered I'm going to close this issue. Thanks!
