### ISSUE TITLE
Clarify SSH key instructions for beginners unfamiliar with SSH/publickey auth

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1138]
I found these instructions not very clear and omitting several steps, they are certainly not written for total beginners: 

Make sure an SSH key is present in ~/.ssh/id_rsa.pub.
If you do not have an SSH key, you can generate one by using this command and following the defaults: ssh-keygen

1. No information is given how to make sure whether an SSH key is present. 
2. Why must it be in exactly this folder and not somewhere else? 
3. What is id_rsa.pub? Does the file have to be named exactly like this in order for it to work or can I just name it sshkeys.pub?
4. When generating an SSH key with the command ssh-keygen, no further information is given what name the file ideally should have and where it should be stored and how to do that.

**Comment by cpu** [comment]
Thanks for the feedback!

**Comment by nopdotcom** [comment]
I'm going to close this; the original itch has been scratched. My...really @cpu's...requests for improvement are filed separately in #11668.
