### ISSUE TITLE
Retry failed

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1139]
I got the following error message because the description of how to generate SSH keys is unclear and not beginner-friendly:

TASK [validation : Fail if the Streisand SSH private key file doesn't exist] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The Streisand SSH private key \"~/.ssh/id_rsa\" does not exist."}

TASK [validation : fail] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Ensure you specified an existing SSH private key file (not public).\n Try using `ssh-keygen -f ~/.ssh/id_rsa to generate your key if it does not exist\n"}
	to retry, use: --limit @/home/martin/streisand/playbooks/validate.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=2   

Then, I typed `--limit @/home/martin/streisand/playbooks/validate.retry`
but again, I got an error message: 
`bash: --limit: command not found...`
  
I also tried `./streisand` but get this message without being able to proceed as indicated in the instructions: 
`bash: ./streisand: Is a directory`

Then I tried to git clone it again but got this error: 
`fatal: destination path 'streisand' already exists and is not an empty directory.`

How shall I proceed?

**Comment by cpu** [comment]
Hi @baimafeima - retrying from a mid-way failed installation isn't supported and will not work. Apologies.
