### ISSUE TITLE
Add V2Ray

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1142]
Could you add V2Ray as a 9th core service?
https://github.com/v2ray/v2ray-core
https://www.v2ray.com/

**Comment by nopdotcom** [comment]
Feature requests make more sense in [discussions](https://github.com/StreisandEffect/discussions). Could you reopen there? A quick paragraph on ways V2Ray is different from existing Streisand services would be great. Obviously we don't need another Shadowsocks implementation, but that could be disabled. :-) Some of the protocol descriptions are in Chinese, and this does add effort for many of us.

**Comment by nopdotcom** [comment]
Moved over to StreisandEffect/discussions#85.
