### ISSUE TITLE
Evaluate XX-Net for addition as another service

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1144]
It would be great to evaluate XX-Net for possible addition as another alternative Streisand service: https://github.com/XX-net/XX-Net

**Comment by nopdotcom** [comment]
This sounds like a good topic for [StreisandEffect/discussions](https://github.com/StreisandEffect/discussions). Over there, could you mention the advantages over the existing protocols in Streisand, and how to build our own XX-Net server so we could evaluate it?
