### ISSUE TITLE
FEATURE REQUEST: streisand mesh

### ISSUE THREAD

**Issue by zenny** [StreisandEffect/streisand#1159]
Hi,

It would be nice if the script has a posibility to create multiple servers in different locations in a mesh (maybe using tinc-vpn or something else).

Cheers,

**Comment by cpu** [comment]
Please open feature requests on the separate discussions repo as prompted in the new issue template:
> Are you suggesting a feature, e.g. a new VPN service or cloud provider? If so, please create a new issue in the Streisand Discussions repository instead: https://github.com/StreisandEffect/streisand-discussions/issues/ 

Thanks
