### ISSUE TITLE
Letsencrypt SSL cert renewal - automatic or manual? How?

### ISSUE THREAD

**Issue by wicknet** [StreisandEffect/streisand#1172]
Kudos for your hard work on this amazing software. Spinning up a new Streisand server on Digital Ocean was super-easy, and having set up a DNS redirect to the new droplet as soon as it came up, Letsencrypt issued it a certificate without any problems during the playbook run.

All good till this point.

However, I'm unable to find any instructions on how to renew the cert before it expires. Does if renew automatically via a pre-set cron job or is it a manual process? Would appreciate some guidance. 

THANKS!

**Comment by cpu** [comment]
Hi @wicknet,

Glad to hear that Streisand worked well for you!

> Does if renew automatically via a pre-set cron job or is it a manual process? Would appreciate some guidance.

It is configured to renew automatically. Streisand installs `acmetool` and it installs a cron entry in `/etc/cron.d/` that takes care of everything. 

Hope that helps clarify!

**Comment by wicknet** [comment]
That's Perfect.

Thanks SO much!
