### ISSUE TITLE
Run on centos

### ISSUE THREAD

**Issue by github-joey** [StreisandEffect/streisand#1174]
Excuse me，How can I  run streisand on the physical machine with CentOS_7_X86_64 system？

**Comment by cpu** [comment]
> How can I run streisand on the physical machine with CentOS_7_X86_64 system
@github-joey Can you clarify?

Do you want to run the Streisand installer on CentOS 7, or you want the Streisand installer to provision a CentOS 7 machine with the VPN services?

If it's the former, please try following the normal setup instructions and share the results if you encounter a problem.

If it's the latter unfortunately Streisand only supports provisioning a Ubuntu 16.04 server and will not be able to support setting up a CentOS 7 machine as a VPN server.

**Comment by nopdotcom** [comment]
If you have problems with clashing Python versions, try the `util/venv-dependencies.sh` script to isolate dependencies to a Python virtualenv.

**Comment by cpu** [comment]
Closing this issue for now. Please feel free to reopen if you're able to answer the questions posed. Thanks!

**Comment by its0x08** [comment]
When will it support CentOS  or Debian?!

**Comment by cpu** [comment]
@its0x08 Almost certainly never. Streisand has minimal maintenance (speaking personally I only reply to a few issues when time permits) and almost no feature development ongoing. Adding an entirely new target operating system will be tremendous work. I recommend you fork the project and try on your own. Good luck!

**Comment by its0x08** [comment]
> @its0x08 Almost certainly never. Streisand has minimal maintenance (speaking personally I only reply to a few issues when time permits) and almost no feature development ongoing. Adding an entirely new target operating system will be tremendous work. I recommend you fork the project and try on your own. Good luck!

Understood !
