### ISSUE TITLE
VPN+Stunnel on Android

### ISSUE THREAD

**Issue by rorusvan** [StreisandEffect/streisand#1175]
Hi, I am rather new in Linux, have been using Streisand installed Digital Ocean VPS and Unilever now everything was working nice. Recently the GSM providers in my country started implementation of DPI. And how while connecting via OpenVPN for Android + Ssldroid occures an error "recv_line: TCP port read failed on recv(): Operation now in progress (errno=115)". 
The landline internet Wi-Fi is not problem, connecting good, but 4G not now. 
My think is that GSM provider started blocking port 41194. Could you give me,please, the idea how to change the Stunnel port 41194 on the Streisand server?

**Comment by eguven** [comment]
It's configured here @rorusvan https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/openvpn/defaults/main.yml#L19

**Comment by rorusvan** [comment]
Thank you, Eren. In this way its possible to change the port 41194 for a new Streisand server. Are you aware of where the Stunnel ports settings on a working server?

**Comment by rorusvan** [comment]
The problem seems to issue not from settings of Stunnel local port, I manually exchanged 41194 to 51194 in Ssldroid settings and ovpn-file, in the home Wi-Fi connect Ok. However in 4G iş not still working.

**Comment by nopdotcom** [comment]
I think you need a redeploy, or to edit the firewall carefully too. 

I don't think we support this kind of change after deployment, so I'm closing. We're delighted if you can do it without a redeploy; if you think it's important, you could post a HOWTO to the Wiki. (The OpenWrt page there gets a *lot* of hits...)
