### ISSUE TITLE
Error installing streisand on AWS

### ISSUE THREAD

**Issue by jesusangelm** [StreisandEffect/streisand#1178]
I got this error message trying to install streisand on AWS:

`TASK [ec2-security-group : Open necessary ports across supported services in the EC2 security group] ********************************************************************* An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupEgress operation: Only Amazon VPC security groups may be used with this operation. fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "InvalidParameterValue", "message": "Only Amazon VPC security groups may be used with this operation."}, "msg": "Unable to authorize out for ip 0.0.0.0/0 security group 'streisand-streisand' - An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupEgress operation: Only Amazon VPC security groups may be used with this operation.", "response_metadata": {"http_headers": {"connection": "close", "date": "Sat, 03 Feb 2018 16:41:38 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 400, "request_id": "6e7f7367-2aaa-40c5-93e1-143d76f5cd27", "retry_attempts": 0}}`

using a user with permissions:

- AdministratorAccess
- AmazonVPCFullAccess

Using:
Ubuntu 16.04 LTS
ansible 2.4.3.0

boto:
Name: boto
Version: 2.48.0

boto3
Name: boto3
Version: 1.5.22

**Comment by nopdotcom** [comment]
Whenever EC2 starts throwing "permission denied" errors on resource setup, my first guess **now** is that I've hit a hard resource limit. If you really need a lot of EIPs, contact support; otherwise, the limits are to keep you from accidentally allocating a million EIPs and getting the bill.

Check the EIP and VPC sections of the EC2 console. If you have more than a few unassigned EIP addresses, or more than a page of VPCs, you're hitting those limits.

Pasting the `streisand-diagnostics.md` file into a comment might help all of us figure this out.

**Comment by jesusangelm** [comment]
mm i don't know AWS very well, but my VPC and EC2 dashboard say: 0 Elastic IP (i guess this is EIP), 0 VPC and 0 EC2 running instances

my current streisand-diagnostincs.md:

`### Ansible Information

* Ansible version: 2.4.3.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 263384f3621d2ee3c0df0fc5854613369d718b5a
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5`

**Comment by nopdotcom** [comment]
Thanks for checking, and for pasting.

Hmm. It says the genesis role is Google. Could be a bug on our side, but could you run `./streisand` again and see if you can get it to say `genesis-amazon`?

**Comment by jesusangelm** [comment]
nah this is not a bug, i'm running a streisand installation on Google Cloud right now.

**Comment by nopdotcom** [comment]
Whatever works! They all have their own advantage and disadvantages. If things are working for you, I bet you were running into transient failures. us-east-2 had a really bad day earlier this week...

Again, thanks for writing this up. If we can see some kind of pattern to it, we may be able to write a guard against it. I'm inclined to close this for now if it's working for you elsewhere.

**Comment by jesusangelm** [comment]
I think you can close this issue, it look like a AWS issue on US-East Virginia location.  i tried again with another location (US-East Ohio) and it is working.
