### ISSUE TITLE
SSH forward user's authorized_key is malformed

### ISSUE THREAD

**Issue by Kyslik** [StreisandEffect/streisand#1179]
After provisioning SSH forward user **authorized_keys** is malformed
### Expected behavior:
```
root@am-2-tiny-ubuntu-vpn:/home/forward/.ssh# cat authorized_keys
ssh-rsa AAAAB3N...
```
### Actual Behavior:
```
root@am-2-tiny-ubuntu-vpn:/home/forward/.ssh# cat authorized_keys
command="echo 'This account is for port forwarding only.'" ssh-rsa AAAAB3N...
```
### Steps to Reproduce:
1. just run the playbook

### Ansible Information

* Ansible version: 2.4.3.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.10.5
* Python interpreter: python
* Python version: 2.7.10

### Streisand Information

* Streisand Git revision: 263384f3621d2ee3c0df0fc5854613369d718b5a
* Streisand Git clone has untracked changes: yes / I changed `do_small_droplet_size_id` variable to `s-1vcpu-1gb`
* Genesis role: genesis-digitalocean
* Custom SSH key: True

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 4

**Comment by nopdotcom** [comment]
That looks like a syntactically valid `authorized_keys`. See the section right below [X11 Forwarding in the `sshd` man page](https://man.openbsd.org/sshd#X11-forwarding):

```
# Comments allowed at start of line 
ssh-rsa AAAAB3Nza...LiPk== user@example.net 
from="*.sales.example.net,!pc.sales.example.net" ssh-rsa AAAAB2...19Q== john@example.net 
command="dump /home",no-pty,no-port-forwarding ssh-dss AAAAC3...51R== example.net 
permitopen="192.0.2.1:80",permitopen="192.0.2.2:25" ssh-dss AAAAB5...21S== 
tunnel="0",command="sh /etc/netstart tun0" ssh-rsa AAAA...== jane@example.net 
restrict,command="uptime" ssh-rsa AAAA1C8...32Tv== user@example.net 
restrict,pty,command="nethack" ssh-rsa AAAA1f8...IrrC5== user@example.net
```

**Comment by Kyslik** [comment]
@nopdotcom my bad, didn't do my homework, just assumed.

Thanks.
