### ISSUE TITLE
Can't install pycurl on MacOS system

### ISSUE THREAD

**Issue by trisolarisdidnothingwrong** [StreisandEffect/streisand#1181]
I'm unable to install pycurl correctly on MacOS Sierra 10.12.6. Can someone advise?

**Logs:**

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-DOVPFi/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6jYayJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-DOVPFi/pycurl/

**Comment by nopdotcom** [comment]
Could you try the `./util/venv-dependencies.sh` script? It helps a lot of people. 

If that doesn't fix it, let's take a look at

```sh
$ type python
$ python -c 'import sys; print sys.path'
```

**Comment by trisolarisdidnothingwrong** [comment]
​Sorry, not a programmer. What's the specific command?​

**Comment by cpu** [comment]
@trisolarisdidnothingwrong The specific command is `./util/venv-dependencies.sh `, run from a terminal after you `cd` to the directory that you git cloned Streisand to.

**Comment by trisolarisdidnothingwrong** [comment]
How do I find which directory I git cloned Streisand to?


--
Addison Yang

Philanthropy in Motion | Community Manager

Mobile | 131.2001.2735
Email | addy134@ucla.edu <addy134@g.ucla.edu>

**Comment by cpu** [comment]
> How do I find which directory I git cloned Streisand to?

@trisolarisdidnothingwrong There's not a good way for anyone on our side to help you with that particular question. My recommendation is that you start fresh. Open a terminal and run:

```
cd   # To make sure you're in your home directory
git clone https://github.com/StreisandEffect/streisand.git # To clone streisand
cd streisand # To change to the git clone directory
./util/venv-dependencies.sh # To install the venv and dependencies
```

**Comment by nopdotcom** [comment]
I want to fix this, because I want macOS to be a first-class builder.

Are you using Homebrew? The easiest way to get the curl development library is `brew install curl`.

I'd appreciate it if you could run that sys.path script. A full log of the `venv-dependencies.sh` would be quite useful. I suggest posting it on gist.github.com, since it's likely to be large. 

It's possible the venv script is already grabbing pycurl too. It would only be available inside the venv; that is, you won't see it unless you run `source YOUR_VENV_DIR/bin/activate`. You need to run that in every terminal window you're working with Streisand in.

**Comment by trisolarisdidnothingwrong** [comment]
I installed via Homebrew successfully. Then I tried running the source
command and got nothing. Can you explain how I retrieve a full log of the
venv-dependencies.sh?

Logs from this attempt:

Last login: Wed Feb  7 01:09:12 on ttys001
MacBook-Pro-2:streisand $ brew install curl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
python ✔                                 libbitcoin-explorer
advancemame                              libbitcoin-node
apm-server                               libbitcoin-server
auditbeat                                librsvg
bandcamp-dl                              libsass
bartycrouch                              libzzip
cask                                     logstash
closure-compiler                         macvim
cockroach                                mariadb@10.1
cryfs                                    mbedtls
dfmt                                     metricbeat
dislocker                                mikutter
elasticsearch                            miniupnpc
elasticsearch@5.6                        mpd
enchant                                  mpdas
exempi                                   mrboom
expect                                   multimarkdown
fabio                                    neko
fibjs                                    nginx
filebeat                                 node-build
flow                                     ortp
fltk                                     osquery
folly                                    packetbeat
fonttools                                pandoc-citeproc
fribidi                                  picard-tools
gdb                                      pre-commit
gexiv2                                   proguard
gifski                                   py2cairo
git-town                                 py3cairo
goenv                                    qpdf
gradle                                   quicktype
gwyddion                                 radare2
hadolint                                 rocksdb
heartbeat                                selenium-server-standalone
htmldoc                                  shadowsocks-libev
htop                                     sip
hugo                                     spigot
hwloc                                    sqlmap
igv                                      stella
influxdb                                 timewarrior
jenkins                                  twarc
joplin                                   vala
kaitai-struct-compiler                   verilator
kibana                                   vifm
kibana@5.6                               vim
libbitcoin                               vips
libbitcoin-blockchain                    wireguard-tools
libbitcoin-consensus                     xpdf
libbitcoin-database                      zimg

==> Downloading
https://homebrew.bintray.com/bottles/curl-7.58.0.sierra.bottle.t
########################################################################
100.0%
==> Pouring curl-7.58.0.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version
in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include

==> Summary
🍺  /usr/local/Cellar/curl/7.58.0: 415 files, 3MB
MacBook-Pro-2:streisand $ source YOUR_VENV_DIR/bin/activate
-bash: YOUR_VENV_DIR/bin/activate: No such file or directory
MacBook-Pro-2:streisand $ cd streisand

**Comment by nopdotcom** [comment]
Huh. Lemme fire up a 10.12 system to check.

Let's avoid installing pycurl (or other dependencies) for now. I think the three commands you want are:

```
cd streisand
./util/venv-dependencies.sh $HOME/streisand-deps
source $HOME/streisand-deps
```

For a full transcript, just copy and paste the lines from the Terminal window, starting with you running `cd streisand`. I'd paste it into a TextEdit window. If you want to keep your username private, search-and-replace `/Users/yourname` with `/Users/streisand`.

Another way of making logs is the `script` command, but we'll try that second, since it's sort of obnoxious. It starts a new sub-shell (to be safe, activate again in this subshell). Everything that would appear on your screen also goes into the `typescript` file, until you `exit` from the subshell. But we shouldn't have to use that yet.

**Comment by trisolarisdidnothingwrong** [comment]
Thanks for continuing to look into this. Definitely appreciate it!

Second command failed, but I still tried the source command.

Log:

Last login: Wed Feb  7 22:34:29 on ttys003

MacBook-Pro-2:streisand $ ./util/venv-dependencies.sh $HOME/streisand-deps

Checking for pip2...

Collecting virtualenv

  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)

    100% |████████████████████████████████| 1.8MB 328kB/s

Installing collected packages: virtualenv

Exception:

Traceback (most recent call last):

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py",
line 215, in main

    status = self.run(options, args)

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py",
line 342, in run

    prefix=options.prefix_path,

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py",
line 784, in install

    **kwargs

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py",
line 851, in install

    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py",
line 1064, in move_wheel_files

    isolated=self.isolated,

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line
345, in move_wheel_files

    clobber(source, lib_dir, True)

  File
"/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line
323, in clobber

    shutil.copyfile(srcfile, destfile)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 83, in copyfile

    with open(dst, 'wb') as fdst:

IOError: [Errno 13] Permission denied:
'/Library/Python/2.7/site-packages/virtualenv.py'

MacBook-Pro-2:streisand $ source $HOME/streisand-deps

-bash: /s//streisand-deps: No such file or directory

MacBook-Pro-2:streisand $

**Comment by trisolarisdidnothingwrong** [comment]
Hi Jay,

Just following up on this. Any further instructions?

**Comment by nopdotcom** [comment]
I'm sorry for the long break; I need a better way of tracking my pending GH issues.

I'm hoping that #1200 will help. My goal was to complete an install on a bare 10.13 system, using the system's native `/usr/bin/python`. I ran `xcode-select --install` to pull down Apple's command-line compilation tools. I used `python -mensurepip` to download `pip`, and `util/venv-dependencies.sh` to install the rest. This seemed to work.

What's in your `$PATH`, `$PYTHONHOME`, and `$PYTHONPATH`?

 When I get some time, I'm going to see how much of the isolation can be enforced in the `venv-dependencies.sh` script.

**Comment by trisolarisdidnothingwrong** [comment]
Hey Jay,

No problem at all. Didn't see instructions online on how to find
$PYTHONHOME. Let me know if the other two are right.

$PATH:

/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

$PYTHONHOME

Not sure how to find this


$PYTHONPATH


['', '/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
'/Library/Python/2.7/site-packages',
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']

**Comment by lawrence-berry** [comment]
I was having similar problems, I think installing pycrypto (`sudo pip install pycrypto`) sorted it for me, then invoking via `sudo ./util/venv-dependencies.sh $HOME/streisand-deps`

**Comment by jasonekratz** [comment]
Just for a point of information I installed streisand on a 10.13.3 system today. I used the default macOS Python 2.7 without issue and the pycurl install worked fine. I did install the newest non-beta Xcode command line utils first from https://developer.apple.com/download/more/ (had to log in).

I did run into an issue trying to use brew to install ansible and ended up just using the linux instruction for sudo pip install ansible which worked just fine.

I also made the mistake of installing the latest dopy client (0.3.7). Didn't work. Don't make the same mistake :)  Uninstalled and then installed 0.3.5 and everything worked great.

**Comment by jasonekratz** [comment]
@trisolarisdidnothingwrong you've definitely got a problem with your $PATH with the 3.5 version of Python there instead of 2.7. Per the instructions anyhow Python 3 won't work, has to be 2.7

**Comment by trisolarisdidnothingwrong** [comment]
Thanks, I installed 2.7 and then pycurl installed fine. My apologies for
the mix-up. The problem I have now is the previous incomplete build. When I
tried to run streisand, it gave me the fatal error "streisand is a
directory" Any guidance on how to rebuild a clean version?


--
Addison Yang

Philanthropy in Motion | Community Manager

Mobile | 131.2001.2735
Email | addy134@ucla.edu <addy134@g.ucla.edu>

**Comment by cpu** [comment]
>  it gave me the fatal error "streisand is a directory" Any guidance on how to rebuild a clean version?

@trisolarisdidnothingwrong You need to `cd streisand` to change into the Streisand project directory and then run `./streisand`.

I'm going to close this issue - it sounds like the original `pycurl` problem has been resolved and the conversation has gone stale.

Thanks!

**Comment by deniztoprak** [comment]
I had the same issue on macOS 10.13.3 and `sudo easy_install pycurl` did the trick for me.
