### ISSUE TITLE
Ports aren't open for Openvpn server in Google Cloud Firewall

### ISSUE THREAD

**Issue by Veka** [StreisandEffect/streisand#1182]
### Expected behavior:
Open ports:

OpenVPN

    TCP - 636
    UDP - 8757

stunnel

    TCP - 993

### Actual Behavior:
Only port tcp:993 is open by openvpn rule.
### Steps to Reproduce:
1.  Default install on Google Cloud Engine

[ contents of `streisand-diagnostics.md` here ]
### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Linux
* Host OS: Debian
* Host OS version:  9.1
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 1e4d9e21bb1e2242f8329e7daa71a3f9adf7fb8d
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment]
Hi @Veka,

Thanks for the bug report! I was able to reproduce this and can confirm your observation that only the stunnel port is being opened. I have a hunch on the root cause and will try to put out a fix PR shortly.

**Comment by cpu** [comment]
Hi again @Veka,

This should be all fixed when running the code in master. Thanks again for reporting the bug!
