### ISSUE TITLE
OpenVPN misconfigure: client can not open web page anymore. 

### ISSUE THREAD

**Issue by Barafu** [StreisandEffect/streisand#1188]
Lets say I have configured OpenVPN on server with domain "dog.go" on IP 1.2.3.4. Afterwards I download .ovpn file (I use UDP ones) and use it with VPN client on Win 10. Overall, internet works fine.

### Expected behavior:

I expect that visiting https://dog.go or https://1.2.3.4 would open streisand web ui for me. 

### Actual Behavior:

Instead, it just waits infinitely to connect. 

### Steps to Reproduce:
1. Connect to OpenVPN
2. Try to visit streisand web UI. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by Barafu** [comment]
I have created a new server and there it is fixed. Some sort of fluke?

**Comment by cpu** [comment]
If creating a new server resolved the problem I'm going to close the issue for now. We can reopen this issue if it occurs again. Thanks!
