### ISSUE TITLE
One particular server is not accessible through VPN but works through Shadowsocks. 

### ISSUE THREAD

**Issue by Barafu** [StreisandEffect/streisand#1191]
There is one particular server that is not accessible through OpenVPN. Browser just hangs indefinitely and opens nothing. However, same address opens through the Shadowsocks to the same streisand machine, and it opens directly, too. It also works with PIA VPN.

I have the word of that server's admin that he does not do anything fancy against VPN. I think issue is somehow connected to DNS. I can PM server's address to anyone investigating the issue. 

### Ansible Information

* Ansible version: 2.4.3.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 606a21b4a8fc674ec18c54b3f61043641362bebd
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 8

**Comment by Barafu** [comment]
OK, this is definitely a DNS problem. DNS server return wrong record. OK, so I added a record of proper IP to both /etc/hosts and dnsmasq config on the streisand machine. However, it still does not work for some reason. The affected server can be pinged now, but does not open front page on client PC when accessed through VPN. It does open from the streisand machione (with lynx) or when client connects to streisand in other way than OpenVPN.

**Comment by cpu** [comment]
Hi @Barafu,

This problem sounds interesting but I'm afraid I don't personally have the time to look into it. Please keep the thread updated if you discover what causes the problematic interaction between OpenVPN and this one website.

**Comment by cpu** [comment]
I'm going to close this issue for now. Unfortunately we don't have the resources to lead investigation and there hasn't been any updates since my last comment. Thanks!
