### ISSUE TITLE
Fatal 'command not found' error during installation

### ISSUE THREAD

**Issue by lumpysimon** [StreisandEffect/streisand#1208]
I'm getting the following fatal error, just after I select DigitalOcean from the provider list:

```
TASK [lineinfile] ****************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: python2: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 127}
	to retry, use: --limit @/Users/myusernameishere/streisand/playbooks/customize.retry

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

I've tried retrying as it suggests but I get the same error.

I also saw the following warning, I don't know if it is relevant or not: `[WARNING]: Found both group and host with same name: localhost`

Addition details below, please let me know if you need anything else to help determine the problem.

**Comment by alimakki** [comment]
Hi @lumpysimon,

I'm guessing you're running into classpath issues, would you mind giving it another shot with the following command (from the streisand root directory) by way of python virtual environments:

`./util/venv-dependencies.sh ~/streisand-venv && source ~/streisand-venv/bin/activate && ./streisand`?

Let us know if that resolves your problem :)

**Comment by mtverlee** [comment]
Hello,

I am having the same issue as described above, also with Digital Ocean as my provider. I tried the solution you listed above but I get the following message: 

```On your system, 'pip' appears to invoke Python 3's pip. This might cause problems.
This script will try switching to 'pip2.7', but your pip2.7 install might be broken too.

You need a working pip command. To get one:

On Debian, Ubuntu, and WSL:
   sudo apt-get install python-pip

On macOS:
   # If you haven't, install homebrew from https://brew.sh/
   brew install python

On other systems: please see your OS documentation on how to install
pip.
```

However, I have a working pip command.

Target Cloud Provider: Digital Ocean
Client OS: macOS High Sierra 10.13.3
Python version: 2.7.14
Ansible version: 2.4.3.0

**Comment by alimakki** [comment]
@mtverlee we could try to break it down:

Within your streisand root directory:

1. `virtualenv streisand-env`
2. `source streisand-env/bin/activate`
3. `pip install -r requirements.txt`
4. `./streisand`

I'm hoping that this sequence of commands will work as I won't have access to my macOS machine for a couple of weeks; if not I'll see if I can muster one somehow.

**Comment by mtverlee** [comment]
@alimakki 

Hello,

The steps you provided didn't seem to work for me as there was still the same error where the python2 command wasn't found.

**TEMPORARY SOLUTION**
I've gotten the following steps to work for me:
- ```sudo rm -rf /Library/Frameworks/Python.framework/Versions/2.7```
- ```sudo rm -rf "/Applications/Python 2.7"```
-```cd /usr/local/bin/```
- ```ls -l /usr/local/bin | grep '../Library/Frameworks/Python.framework/Versions/2.7' | awk '{print $9}' | tr -d @ | xargs rm```
- ```If necessary, edit your shell profile file(s) to remove adding /Library/Frameworks/Python.framework/Versions/2.7 to your PATH environment file. Depending on which shell you use, any of the following files may have been modified: ~/.bash_login, ~/.bash_profile, ~/.cshrc, ~/.profile, ~/.tcshrc, and/or ~/.zprofile.```
- ```brew uninstall python```
- ```brew update && brew install python2```
- ```./util/venv-dependencies.sh ~/streisand-venv && source ~/streisand-venv/bin/activate && ./streisand```

**Comment by alimakki** [comment]
@mtverlee I can't say for sure as I haven't installed High Sierra. That being said homebrew has always been somewhat of a challenge with how it handles python installations and classpaths.

Thanks for sharing your workaround however, it will surely help us tune our virtual-env wrapper script to be more robust across the myriad of platforms out there.

**Comment by mtverlee** [comment]
@alimakki Agreed. Homebrew is full of troubles. Thanks for your help.

**Comment by nopdotcom** [comment]
On a bare 10.13 machine, you can get a basic pip with `sudo python -m ensurepip`. I'll update the documentation separately.

**Comment by alimakki** [comment]
@mtverlee my pleasure.

**Comment by alimakki** [comment]
@lumpysimon, were you able to resolve your issue?

**Comment by lumpysimon** [comment]
@alimakki I got there in the end! I followed @mtverlee 's steps, but it turned out i needed to use `brew uninstall --force python` as somehow Homebrew had 11 different versions of Python installed (taking up over 800Mb of disk space). Once I'd done that it worked fine.

**Comment by alimakki** [comment]
@lumpysimon, glad to know that you've worked around your problem; homebrew certainly has its quirks unfortunately.

Thanks also for the little tidbit of information :)

**Comment by hadifarnoud** [comment]
I have the same issue. uninstalled python via brew and now using MacOS's python `2.7.15`

```

╰ ./util/venv-dependencies.sh ~/streisand-venv && source ~/streisand-venv/bin/activate && ./streisand
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (15.1.0)
./util/venv-dependencies.sh: line 218: virtualenv: command not found

virtualenv failed to create directory '/Users/hadifarnoud/streisand-venv'
using 'virtualenv --python=python2.7 /Users/hadifarnoud/streisand-venv'. Note that /Users/hadifarnoud/streisand-venv must not exist, but
its parent (/Users/hadifarnoud) must exist.

The first argument, 'new-directory', must be somewhere you can write
to. A good place is './venv'. If it already exists, please delete the
directory, or use a different name.

```

**Comment by pascalandy** [comment]
For, my issue was that virtualenv could not be found. 

I had to re-install using sudo:
https://stackoverflow.com/a/37242519

Thanks!
