### ISSUE TITLE
Chromebook L2TP/IPsec internal error

### ISSUE THREAD

**Issue by beachfork** [StreisandEffect/streisand#1213]
### Expected behavior:
VPN should connect after following the steps on the Streisand Gateway.

### Actual Behavior:
VPN does not connect and Chromebook give vague "internal error" output.

### Steps to Reproduce:
1. Install Streisand on a DigitalOcean (any provider?) VPS
2. Follow the Chromebook directions on the Streisand Gateway html file.
3. When trying to connect Chromebook errors out with "internal error"

##### *Target Cloud Provider:
DigitalOcean

##### *Operating System of target host:
Ubuntu 16 LTS

##### *Operating System of client:
Using Samsung Chromebook 3 on latest ChromeOS version

Thanks for any help!

**Comment by cpu** [comment]
Hi @beachfork, sorry to hear about your trouble with Streisand.

I don't have access to any ChromeOS machines and nobody else has jumped in. It's possible the Chromebook L2TP instructions no longer work.

My recommendation is that you try OpenVPN or another VPN service that Streisand provides. I think we should perhaps remove the Chromebook instructions unless they can be verified working and someone is able to maintain them.

@alimakki @jlund @nopdotcom Do any of you have ChromeOS hardware & time to support the L2TP Chromebook configuration?

**Comment by beachfork** [comment]
Hi @cpu! Thanks for the reply!

I didn't test the other protocols since ChromeOS on tunnels the whole system when using L2TP, if I use OpenVPN for example, it will only tunnel via VPN the apps installed via Google Play Store, everything else will be exposed.

While browsing the Google help forums for ChromeOS I've found huge threads claiming that the L2TP is broken unfortunately. But I've found that they claim to have OpenVPN native support, but it envolves a lot of terminal!

https://support.google.com/chromebook/answer/1282338?hl=en

**Comment by cpu** [comment]
> I didn't test other protocols since ChromeOS only tunnels the whole system when using L2TP, if I use OpenVPN for example, it will only tunnel via VPN the apps installed via Google Play Store, everything else will be exposed.

Aha, I can understand why you would want L2TP in those circumstances. If that's your specific need you might want to look at a project like [Algo](https://github.com/trailofbits/algo) that expressly focuses on IPSec based VPNs. I personally think Streisand doesn't meet this need very well (I explain myself here: https://github.com/StreisandEffect/streisand/issues/1222).

> While browsing the Google help forums for ChromeOS I've found huge threads claiming that the L2TP is broken unfortunately. But I've found that they claim to have OpenVPN native support, but it envolves a lot of terminal!

:sob: That would explain your frustration getting L2TP working with Streisand :-) Thanks for linking to that support thread. There might be something we can learn about better OpenVPN ChromeOS support there. It's unfortunate it requires the command line!

I'm going to close this issue for now - it seems unlikely that I'll be able to do anything to help with Chromebook L2TP/IPSec. Apologies!

**Comment by UR0730** [comment]
![image](https://user-images.githubusercontent.com/60294638/73124094-01356e80-3fb9-11ea-81b2-8f0d88e341d7.png)
if you are getting the error message like the one shown in attached image i.e. 'internal error' then make sure to enter the server ip address in the 'server hostname' field, it will fix the issue and get connected at once ;)
