### ISSUE TITLE
tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] 

### ISSUE THREAD

**Issue by loo11** [StreisandEffect/streisand#1216]
Hi, first of all thank you for this script,
Im actually trying to install it but I get the following error, I'm admit that im a novice and dont really know what to do, 
I also get , at the beginning an error from dime**something about, bios version, but it doesnt seems that it affects something.
If you can take a look,
Thank you

### Steps to Reproduce:
8 : Provider (HostHatch)

TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] *************
fatal: [31.220.45.125]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.002234", "end": "2018-03-19 12:05:40.494631", "msg": "non-zero return code", "rc": 1, "start": "2018-03-19 12:05:40.492397", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}

-->
##### *Version of Ansible, using `ansible --version` :*
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/loo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/loo/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

##### *Output from `git rev-parse HEAD` in your Streisand directory :*
77611d3e04a1d09e0f39f206af61c4b150255a09

**Comment by alimakki** [comment]
Hi @loo11 

I am unfamiliar with this host - we generally recommend you try one of the supported cloud providers as they have first class support and have been rigorously tested.

Thanks!
