### ISSUE TITLE
using another openvpn app for Android

### ISSUE THREAD

**Issue by melkopisi** [StreisandEffect/streisand#1217]
Hello, why i can't use the official openvpn connect app for Android or any other openvpn clients as i'm an Android developer and i'm developing my own client the connection always restarting after success connection

**any suggestions ?**

![photo_2018-03-15_05-29-51](https://user-images.githubusercontent.com/8727943/37615000-e089b296-2bb4-11e8-868b-fc8cadf94039.jpg)

**Comment by alimakki** [comment]
Hi @melkopisi 

Streisand generates a handful of OpenVPN connection profiles, one of which is an `stunnel` configuration - from the screenshot that you have provided, it appears that you are using this one.  In order for this to work, you will need to follow the `stunnel` instructions. 

Before doing so, I would recommend you use one of the direct profiles (for example, one of the ones that are suffixed with `combined`). Can you confirm which profile you are using?

Additionally, can you paste the content of your `diagnostics.md`?

Thanks!

**Comment by melkopisi** [comment]
what i want to say this method is working fine when using stunnel with `OpenVPN for Android` but when i try to use another openvpn client it isn't working 

about direct profiles the ISP in my country uses DPI and Throttling so the only way i can connect to openvpn is through stunnel but i'll do my best to provide these information

diagnostics.md :
```### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 6ef162d4e8e00bfeef5873e0acd0d35bfc6eff5e
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-linode
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5
```

**Comment by alimakki** [comment]
@melkopisi what's the other client that you're trying to use?

**Comment by melkopisi** [comment]
the official openvpn app openvpn connect

[https://play.google.com/store/apps/details?id=net.openvpn.openvpn](url)

**Comment by alimakki** [comment]
I will try to get a hold of an Android device to try and test with. What version of Android are you using?

**Comment by melkopisi** [comment]
Android 7.1 Nougat

**Comment by alimakki** [comment]
@melkopisi, I was able to reproduce the issue on an Android 7 device. My guess is that SSLDroid is somewhat old and needs to be updated to account for differences in Android releases > v6.

I did find a workaround however, although it is a somewhat more involved process.

I managed to find a guide from AirVPN [here](https://airvpn.org/topic/24349-how-to-airvpn-via-sslstunnel-on-android-678/) and adapted it to work with a Streisand setup on Linode.

Here is the `stunnel.conf` that I used:

```
client = yes
foreground = yes
pid = /data/data/com.termux/files/home/stunnel4.pid
debug = 6

[stunnel]
accept = 127.0.0.1:41194
connect = 1.2.3.4:993 ## replace with your server IP address
TIMEOUTclose = 0
```

You'll want to copy the file to your phone's filesystem and remember its location (for example the Downloads folder)

Next, you will need to install termux from the play store, launch it and go through the following commands:

1. `termux-setup-storage` to allow termux access to your filesystem
2. `pkg upgrade`
3. `pkg install stunnel`
4. `cd storage/shared/Downloads`
5. launch stunnel: `stunnel stunnel.conf`

Once stunnel is running (and SSLDroid is not), attempt to connect with OpenVPN connect. Let me know if you are successful.

**Comment by melkopisi** [comment]
same problem i guess but why it can work fine with `OpenVPN for Android` app and if the problem with `SSLDroid` i'm an Android Developer and if i know what  support that application needs i can create a version with that support
 
![screenshot_2018-03-20-17-29-53-119_com termux](https://user-images.githubusercontent.com/8727943/37666039-3e32edb0-2c67-11e8-8aed-96a71a2e5356.png)

![screenshot_2018-03-20-17-34-46-484_net openvpn openvpn](https://user-images.githubusercontent.com/8727943/37665788-b1bfcbb4-2c66-11e8-8c20-6ee2d5aa46d8.png)

**Comment by melkopisi** [comment]
So i tried several methods and i was able to create a successful connection over Mobile data and failed over Wi-Fi

but with `OpenVPN for Android` it works fine on both of them and still don't know why

another way easier than using `termux` is using [https://github.com/PeterCxy/stunnel-android](url)

![deepinscreenshot_select-area_20180320191607](https://user-images.githubusercontent.com/8727943/37670972-4fc566c8-2c73-11e8-8479-4e806a228fdb.png)

thanks @alimakki  for your time and knowledge

**Comment by alimakki** [comment]
@melkopisi glad to know that you've found something that works out for you.

If you're getting successful connections over mobile data and not WiFi, it could be an MTU issue.

In any case, thanks for sticking by :)

**Comment by Keridoo** [comment]
Can I run Orbot and Stunnel at the same time via 127.0.0.1 but on different ports? 

Can I use Stunnel to I use Stunnel as a local Socks5 proxy and chain it behind NetGuard (without OpenVPN)? [Here](https://github.com/StreisandEffect/discussions/issues/119) is some background on my user scenario. 

@alimakki I can connect with stunnel by following your Termux instructions. However, I cannot successfully send any traffic via that connection. I wonder whether this is due to the *.p12 file missing as a means to authenticate. 

@melkopisi I'm only an Android user. Can you please give me instructions how to setup PeterCxy's stunnel-android?

**Comment by melkopisi** [comment]
@Keridoo i will try in my spare time :)
