### ISSUE TITLE
Evaluate whether `ocserv` 0.10.11 is sufficient for Streisand

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#1223]
### Expected behavior:

Streisand installs software from upstream repositories. The software gets regular security updates automatically from `unattended-upgrades`.

### Actual Behavior:

Streisand installs `ocserv` from the upstream's published source tarballs:
https://github.com/StreisandEffect/streisand/blob/a9c1638dea2b59e258bc49c5658c809eb70c112e/playbooks/roles/openconnect/tasks/install.yml#L23-L49

### Installing from Ubuntu `universe` package

[Ubuntu packages `ocserv` at version 0.10.11](https://packages.ubuntu.com/xenial/ocserv). We should make sure we can't survive with this version. Presently we're installing 0.11.10: https://github.com/StreisandEffect/streisand/blob/a9c1638dea2b59e258bc49c5658c809eb70c112e/playbooks/roles/openconnect/vars/main.yml#L25

This issue is to track verifying whether we actually 100% need **0.11.10+**.

**Comment by alimakki** [comment]
Resolved in #1242

**Comment by cpu** [comment]
Woohoo!
