### ISSUE TITLE
Failed Task [download-and-verify : Register GPG signature verification results]

### ISSUE THREAD

**Issue by Frichetten** [StreisandEffect/streisand#1227]
### Expected behavior:
Streisand installs without errors.

### Actual Behavior:
I'm getting a weird error for the task "download-and-verify : Register GPG signature verification results".
![screenshot from 2018-03-22 16-58-53](https://user-images.githubusercontent.com/10386884/37801304-15452f42-2df4-11e8-9dc2-e6c8dad96fcc.png)

### Steps to Reproduce:
1. ./streisand (will occur with both custom and default options)

### Ansible Information

* Ansible version: 2.4.3.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  17.10
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 7bc1db3482f7cfaed2270508b2de233bb0c18c69
* Streisand Git clone has untracked changes: yes
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  False
* Wireguard enabled: False
* OpenVPN enabled: True
* stunnel enabled: False
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: False
* SSH forward user enabled: False
* L2TP enabled: False
* Configured number of VPN clients: 5

Does not appear to prevent me from actually using the VPN though.

**Comment by cpu** [comment]
Hi @Frichetten, 

Thanks for opening this issue. I've been seeing the same GPG signature error in my recent development/testing.

I'm in the middle of reworking all of Streisand's GPG code to be (hopefully!) a lot more robust (using GPG2, fetching keys over HTTPS, increasing the key fetch timeout, and building a starter keyring with known good keys from the git repo). You can follow https://github.com/StreisandEffect/streisand/issues/963 for most of this work. I'm hoping to have it ready shortly.

I'll pick up a fix to this problem (assuming it doesn't "go away" on its own) as part of the above work.

Thanks!

**Comment by doodlemania2** [comment]
+1 impacting me as well

**Comment by cpu** [comment]
@doodlemania2 @Frichetten  I believe this should be fixed with the code from master. Can you try updating your Streisand git clone and creating a new server to confirm? Thanks!

**Comment by Frichetten** [comment]
Just did a fresh install without errors. Great work @cpu! I will close this issue now.

**Comment by cpu** [comment]
Awesome, thanks for following up @Frichetten !
