### ISSUE TITLE
Streisand fails on 'Determine which AMI to use' step

### ISSUE THREAD

**Issue by cyrillk** [StreisandEffect/streisand#1228]
### Expected behavior:

No failures.

### Actual Behavior:

Fails on

```
TASK [genesis-amazon : Determine which AMI to use] *************************************************************************************************************************************************************
[DEPRECATION WARNING]: The 'ec2_ami_find' module has been deprecated. Use 'ec2_ami_facts' instead.. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "boto required for this module, install via pip or your package manager"}
```

### Steps to Reproduce:

```
git pull
virtualenv ~/virtualenv
source ~/virtualenv/bin/activate
pip install -r ./requirements.txt
./streisand
```

*Target Cloud Provider:*

`Amazon`

*Version of Ansible, using `ansible --version` :*

```
ansible --version
ansible 2.5.0
  config file = /Users/kk186094/develop/streisand/ansible.cfg
  configured module search path = ['/Users/kk186094/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kk186094/virtualenv/lib/python3.6/site-packages/ansible
  executable location = /Users/kk186094/virtualenv/bin/ansible
  python version = 3.6.4 (default, Mar  9 2018, 23:15:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

*Output from `git rev-parse HEAD` in your Streisand directory :*

```
git rev-parse HEAD
7bc1db3482f7cfaed2270508b2de233bb0c18c69
```

**Comment by cpu** [comment]
Hi @cyrillk, sorry to hear about your trouble with Streisand. Let's see if we can sort it out :-)

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "boto required for this module, install via pip or your package manager"}

I see from your `ansible --version` output you are using `python version = 3.6.4`. Can you share the output from:
`pip3 show boto` and `pip3 show boto3`?

It looks like you ran `pip install -r ./requirements.txt` when I believe for this instance you would want to run `pip3 install -r ./requirements.txt`

**Comment by nopdotcom** [comment]
I guess we can rewrite the documentation to say "Python 2 everywhere" or "Python 3 everywhere". `util/venv-dependencies.sh` needs to pick a strategy. I'm not touching `util/ubuntu-dependencies.sh` until `/usr/bin/python` changes on Debian or Ubuntu.

**Comment by cyrillk** [comment]
@cpu Thank you for looking at it

```
pip3 show boto
Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/kk186094/virtualenv/lib/python3.6/site-packages
Requires:
```

```
pip3 show boto3
Name: boto3
Version: 1.6.15
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/kk186094/virtualenv/lib/python3.6/site-packages
Requires: botocore, s3transfer, jmespath
```

Also, I've tried `pip3 install -r ./requirements.txt` but got the same error.

**Comment by cpu** [comment]
@nopdotcom Any ideas on :point_up:? It seems like the venv has the right packages, is Ansible not using the venv python?

**Comment by nopdotcom** [comment]
I am tempted to declare Python 3 to be unsupported temporarily. We have specific versions of modules pinned in `requirements.txt`. (They are also pinned in the README.) We need to find the same dead chicken as we used last time to wave over the version specs. Then test all the providers. I mean, we could always just wait for bug reports like this instead. :-)

I had an awful experience with Homebrew's Python 3 upgrade, and having `/usr/local/bin/python` be a different version than /usr/bin/python is gonna suck. I'd rather `ln /bin/false /usr/bin/python` and make people choose a version. Not my department though.

**Comment by PTPells** [comment]
@cyrillk, @cpu and/or @nopdotcom have y'all had any success in resolving this issue? My set up too produces the following error *after* having tried `pip3 install -r ./requirements.txt`

### Error:

```
[DEPRECATION WARNING]: The 'ec2_ami_find' module has been deprecated. Use 'ec2_ami_facts' 
instead.. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg. fatal: [localhost]: FAILED! => {"changed": false, "msg": 
"boto required for this module, install via pip or your package manager"}
```

### My Setup:
*OS:* `MacOS 10.13.3`

*Cloud provider:* `Amazon`

`ansible --version` :

```
ansible 2.5.0
  config file = /Users/peterpelberg/streisand/ansible.cfg
  configured module search path = [u'/Users/peterpelberg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```
`pip3 show boto` :
```
Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: 
```
`pip3 show boto3`:
```
Name: boto3
Version: 1.7.4
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: botocore, s3transfer, jmespath
```

**Comment by nopdotcom** [comment]
I *think* these could be separate issues, but they both smell like conflicting environments, yeah. I blame Hombrew for changing what `/usr/local/bin/python` does; they switched it to Python 3.6, which I didn't notice until everything broke. The Homebrew Ansible still uses Python 2.7: 

```
$ brew info ansible | grep Required:
Required: libyaml, openssl, python@2
```

@cyrillk, @PTPells: have you tried `./scripts/venv-dependencies.sh`? I'm pretty sure that's clean with regard to 2.7 vs 3.6. But Homebrew Python is messed up, and it might be messed up in different ways for each of us.

If you'd like to debug this further, here's what I could use:

```bash
$ type -p ansible
/usr/local/bin/ansible
$ head -1 $(type -p ansible)
#!/usr/local/Cellar/ansible/2.5.0/libexec/bin/python2.7
```

The last points to the Python actually being executed by `ansible`.

Once you have that path, let's check out where `boto` and `boto3` go:

```bash
$ /usr/local/Cellar/ansible/2.5.0/libexec/bin/python2.7 -v -c 'import boto' 2>&1 | grep import
$ /usr/local/Cellar/ansible/2.5.0/libexec/bin/python2.7 -v -c 'import boto3' 2>&1 | grep import
```

Those should be rather long; could upload them as a gist?

**Comment by PTPells** [comment]
Thank you for hanging in there with us, @nopdotcom. Here we go...

Running:
`./scripts/venv-dependencies.sh`

Returns:
`-bash: ./scripts/venv-dependencies.sh: No such file or directory`

However, running:
`./util/venv-dependencies.sh`

Returns:
```
Usage: ./util/venv-dependencies.sh new-directory

This script installs Streisand builder dependencies into an isolated
Python virtualenv. A virtualenv is one of the most reliable ways of
avoiding version clashes, and is especially recommended for people
having problems with initial Streisand installs.

Note that this script is not guaranteed to work for localhost
deployments. This will be fixed in a later release.

It depends on Python 2.7, and on a pip command functional enough to
install virtualenv.  If this is a system running Debian or Ubuntu,
this script will also check for other packages needed to install.

This script can install virtualenv for you, but on Linux, this
requires sudo/root access.

'new-directory' must be somewhere you can write to. A good place may be
/Users/peterpelberg/streisand-deps. If it already exists,
please delete the directory, or use a different name.

On your system, 'pip' appears to invoke Python 3's pip. This might cause problems.
This script will try switching to 'pip2.7', but your pip2.7 install might be broken too.
```
Continuing on...

```
$ type -p ansible
/Library/Frameworks/Python.framework/Versions/3.6/bin/ansible
iris:streisand peterpelberg$ head -1 $(type -p ansible)
#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
```

Subsequently running:
`$ /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -v -c 'import boto' 2>&1 | grep import`

Returns the following: 
[-v -c 'import boto' 2>&1 | grep import](https://gist.github.com/PTPells/0effaf00ca80f36473da94f242d8ecc6)

And then running:
`/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -v -c 'import boto3' 2>&1 | grep import`

Returns:
[-v -c 'import boto3' 2>&1 | grep import](https://gist.github.com/PTPells/975d385e52ad35b60a261eaf6935575a)

**Comment by nopdotcom** [comment]
Thanks for the logs! I had forgotten that Python 3 `-v` doesn't quite use the same format; next time I'll ask for `grep '# code object'`.

In any case, I think we need to get the two different `ansible`s in sync. Before, `ansible --version` was printing this:

```
ansible 2.5.0
  config file = /Users/peterpelberg/streisand/ansible.cfg
  configured module search path = [u'/Users/peterpelberg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

but now

```
$ type -p ansible
/Library/Frameworks/Python.framework/Versions/3.6/bin/ansible
```

and I don't think both of those can happen with the same `$PATH`. I think in the time between our posts, you may have fixed some stuff.

I'm guessing `/Library/Frameworks/Python.framework3.6`, is from the Python 3.6 installer from python.org? I've mostly been testing with the Homebrew `python3`, so I probably haven't had this exact experience. The Ansible installed from Homebrew starts:

```
#!/usr/local/Cellar/ansible/2.5.0/libexec/bin/python2.7
```

But we want our own version of Ansible. Could you unlink the Ansible package from Homebrew if you haven't? `brew unlink ansible`; you can always `brew link ansible` later.

(I also just ran into some weird errors with Homebrew Python 2, which I fixed with `brew uninstall --ignore-dependencies python@2; brew install python@2`. It's been a bumpy month or two for Homebrew...)

Run `./util/venv-dependencies.sh /tmp/deps`. If this completes without error, you can run `source /tmp/deps/bin/activate`. The version of Ansible installed by this should say:

```
$ ansible --version
ansible 2.5.0
  config file = /Users/nop/gh/streisand/ansible.cfg
  configured module search path = [u'/Users/nop/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/deps/lib/python2.7/site-packages/ansible
  executable location = /tmp/deps/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 15:00:11) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

If it doesn't, it should at least produce fresh errors. :-)

**Comment by nopdotcom** [comment]
For people wondering why I am so paranoid about Python versions on Homebrew:

https://github.com/Homebrew/homebrew-core/commit/13f26913d7671852c34f0be33bc9e05b19cad528

**Comment by nopdotcom** [comment]
BTW, I just noticed that running the python.org installed jammed this into my `.bash_profile` without asking or even telling me:

```
# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
```

That's pretty special, python.org.

**Comment by PTPells** [comment]
Spoiler alert: good news coming...thank you for your patience and thoroughness, @nopdotcom.

`./streisand` installation completed **without** issue! Are there any logs I can send you that could help bring you greater closure to this issue?

And to your earlier question RE `/Library/Frameworks/Python.framework3.6`, you're right...I installed Python 3.6 using the installer from python.org.

Bonus: for my curiosity as a beginner, would it be accurate and complete to say the installation issues I encountered were rooted in both Python 2 and 3 being installed on my machine?

**Comment by cpu** [comment]
It sounds like this issue reached a happy ending for @PTPells and I think @cyrillk fell off before providing the information needed to dig in.

It sounds like there are multiple pitfalls for OSX users w.r.t where they get their system Python. I'm open to documentation improvements if any of the parties involved in the excellent debugging work from this topic are willing to submit a pull request with improvements.

I'm going to close this issue for now since I think there aren't any immediate actions left to take here. Thanks everyone!
