### ISSUE TITLE
GCE: Failure on TASK [gce-network : Create network]

### ISSUE THREAD

**Issue by dmtroyer** [StreisandEffect/streisand#1230]
### Expected behavior:

No failures.

### Actual Behavior:

```
PLAY [Provision the GCE Server] ***********************************************************************

TASK [Gathering Facts] ********************************************************************************
ok: [localhost]

TASK [Set the Google Compute Engine Zone fact] ********************************************************
ok: [localhost]

TASK [Register JSON file contents] ********************************************************************
ok: [localhost]

TASK [Set JSON file contents fact] ********************************************************************
ok: [localhost]

TASK [Set the Google Compute Engine Service Account Email] ********************************************
ok: [localhost]

TASK [Set the Google Compute Engine Project ID] *******************************************************
ok: [localhost]

TASK [gce-network : Create network] *******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "libcloud with GCE support (0.17.0+) required for this module"}

Failure during server setup
```

### Steps to Reproduce:
1. run `./streisand' with a custom install for GCE. the only non-default is to not install Tor.

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
[Terminal output](https://gist.github.com/dmtroyer/28a724cbb9f0c48b5cfd4f4d20a5c200)
##### *Target Cloud Provider:*
Google
##### *Operating System of target host:*
N/A
##### *Operating System of client:*
MacOS 10.13.3
##### *Version of Ansible, using `ansible --version` :*
2.5.0
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
`7bc1db3482f7cfaed2270508b2de233bb0c18c69`

**Comment by dmtroyer** [comment]
Other things that may help:

- Python 2.7.0
- Pip 9.3.0
- apache-libcloud 2.3.0

**Comment by cpu** [comment]
@dmtroyer Can you share your `streisand-diagnostics.md` file please?

How did you install `apache-libcloud`?

**Comment by dmtroyer** [comment]
I don't see a `streisand-diagnostics.md` file in the top level of the streisand directory.

I installed `apache-libcloud` with `sudo pip install "apache-libcloud>=1.17.0"`.

I was confused as to why sudo would be required for pip. It was previously installed with homebrew, and then when I went to run pip using sudo pip wasn't found. I'm guessing it is homebrew pip/python related?

**Comment by cpu** [comment]
> @cpu I don't see a streisand-diagnostics.md file in the top level of the streisand directory

Ahhh, that makes sense. I think an error at this stage of provisioning would fail before that file is generated. Thanks for checking.

Can you share the full output from `ansible --version`? I'm interested in seeing Ansible's "python version" from that output.

> I installed apache-libcloud with sudo pip install "apache-libcloud>=1.17.0".
>  I'm guessing it is homebrew pip/python related?

That seems very likely. I know @nopdotcom has had a heck of a time sorting out Homebrew/OSX/Python/Pip related headaches.

**Comment by dmtroyer** [comment]
> Can you share the full output from ansible --version? I'm interested in seeing Ansible's "python version" from that output.

```
[dmtroyer@dBook streisand (master)]$ ansible --version
ansible 2.5.0
  config file = /Users/dmtroyer/Projects/personal/streisand/ansible.cfg
  configured module search path = [u'/Users/dmtroyer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by cpu** [comment]
@dmtroyer One thing that might help: uninstall the homebrew installed Ansible, and install Ansible from pip with `pip install ansible`. I think the problem here might be a conflict between homebrew Ansible (in `/usr/local/Cellar/ansible` and the `apache-libcloud` you installed via `sudo pip`.

(I might be totally wrong: unfortunately I don't have an OSX machine or much experience with homebrew)

**Comment by dmtroyer** [comment]
Sorry, I realize this is not helpful, but I just spun up another ubuntu instance and ran it from there. I'm certain it is homebrew/pip related. Unfortunately I don't use python enough to know a good way to manage it or troubleshoot it on my mac.

@cpu thanks for your time and help!

**Comment by cpu** [comment]
@dmtroyer No problem. Thanks for reporting back! Glad to hear provisioning from a Ubuntu host worked for you :+1:

**Comment by pyotr** [comment]
@cpu Hey. Same problem on my mac 10.13.4 :(
