### ISSUE TITLE
Streisand can't reach some servers

### ISSUE THREAD

**Issue by Stanpol** [StreisandEffect/streisand#1238]
I have a VPS from Vultr.com with a fresh Streisand installed on it. The VPN works for 99% of the websites, but not for all of them. 

For example, it's not working for https://foursquare.com/

- Instead of a page I see a 403 Forbidden nginx error. 
- The SSL certificate is correct, signed by Foursquare. 
- The problem is not on a vpn client side, because when I ssh log into to my Streisand server, I can't wget https://foursquare.com/ getting the same 403 error. 
- This is not a Vultr.com problem, cause on a freshly installed Ubuntu, I can wget foursquare.com without any problems.

My guess is that there is some problem with dnsmasq. Because on my Streisand server it is missing AUTHORITY SECTION.

### Expected behavior:
Here is how dns is resolved on a freshly installed system without Streisand:
```
drill foursquare.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 57791
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 0
;; QUESTION SECTION:
;; foursquare.com.	IN	A

;; ANSWER SECTION:
foursquare.com.	60	IN	A	151.101.128.154
foursquare.com.	60	IN	A	151.101.64.154
foursquare.com.	60	IN	A	151.101.0.154
foursquare.com.	60	IN	A	151.101.192.154

;; AUTHORITY SECTION:
foursquare.com.	168021	IN	NS	ns-91.awsdns-11.com.
foursquare.com.	168021	IN	NS	ns-1013.awsdns-62.net.
foursquare.com.	168021	IN	NS	ns-1360.awsdns-42.org.
foursquare.com.	168021	IN	NS	ns-1758.awsdns-27.co.uk.

;; ADDITIONAL SECTION:

;; Query time: 11 msec
;; SERVER: 108.61.10.10
;; WHEN: Mon Mar 26 14:44:05 2018
;; MSG SIZE  rcvd: 233
```
### Actual Behavior:

Here is how dns is resolved on the server with Streisand:
```
drill foursquare.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 17320
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; foursquare.com.	IN	A

;; ANSWER SECTION:
foursquare.com.	58	IN	A	151.101.128.154
foursquare.com.	58	IN	A	151.101.0.154
foursquare.com.	58	IN	A	151.101.64.154
foursquare.com.	58	IN	A	151.101.192.154

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 6 msec
;; SERVER: 127.0.0.1
;; WHEN: Mon Mar 26 14:40:23 2018
;; MSG SIZE  rcvd: 96
```
### Steps to Reproduce:
1. Install Streisand
2. Try to reach foursquare.com
3. `sudo apt-get install ldnsutils` to get drill

##### *Target Cloud Provider:*
Vultr.com
##### *Operating System of target host:*
Ubuntu 16.04.3 LTS
##### *Operating System of client:*
MacOS 10.13.3 
##### *Version of Ansible, using `ansible --version` :*
ansible 2.5.0
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
7bc1db3482f7cfaed2270508b2de233bb0c18c69

**Comment by nopdotcom** [comment]
Could you try installing streisand on the Ubuntu server which is not having problems? It's not uncommon for reused pool IP addresses to get banned by sites due to previous misbehavior from that address. Maybe we should document that.

**Comment by cpu** [comment]
> This is not a Vultr.com problem, cause on a freshly installed Ubuntu, I can wget foursquare.com without any problems.

My gut says similar to @nopdotcom - this may be a matter of one Vultr instance having an IP in someone's WAF/blocklist and one Vultr instance having a "clean" IP.

**Comment by Stanpol** [comment]
Yes, I confirm, that was a particular IP address problem.

**Comment by cpu** [comment]
@Stanpol Thanks for following up :+1: Blocking IPs like this is certainly an annoying practice to encounter :-(
