### ISSUE TITLE
Tunnelblick instructions should instruct to use OpenVPN v >= 2.4

### ISSUE THREAD

**Issue by alimakki** [StreisandEffect/streisand#1239]
The generated instructions for OpenVPN on macOS should specify the usage of an OpenVPN version of >= 2.4 as `tls-crypt` now requires this.

Tunnelblick bundles several versions of OpenVPN and defaults to a v2.3 series, which does not work with our generated configurations.

**Comment by deniztoprak** [comment]
I don't know if it's the same issue but I get the following warning before connecting my AWS instance with generated configuration on `Tunnelblick 3.7.5a (build 5011)`:
> Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:3: block-outside-dns (2.4.4)

**Comment by alimakki** [comment]
@deniztoprak that can be safely ignored, it's a quirk for Windows clients to prevent dns leaks.

**Comment by pandemicsoul** [comment]
@alimakki Happens to me using Mac, as well.

**Comment by alimakki** [comment]
@pandemicsoul, what version of tunnelblick are you using?

**Comment by khovansky-al** [comment]
@alimakki Having same issue with unrecognized `block-outside-dns` here on mac with Tunnelblick 3.7.5a

**Comment by dandaka** [comment]
Tunnelblick 3.7.5a (build 5011) on MacOS, same bug. I get this error every time I connect to VPN.

**Comment by alimakki** [comment]
The latest tunnelblick builds are clever enough to automatically detect which version of OpenVPN to use.

**Comment by artem-russkikh** [comment]
> Having same issue with unrecognized block-outside-dns here on mac with Tunnelblick 3.7.5a

It is possible to ignore `block-outside-dns` macOS Tunnelblick warning by modifying local cofiguration:
```
pull-filter ignore "block-outside-dns"
```
