### ISSUE TITLE
Need to actualise the "AWS IAM role and policy setup"

### ISSUE THREAD

**Issue by i-land** [StreisandEffect/streisand#1249]
### Expected behavior:
With permissions, described in tutorial should be possible to deploy the service. 
### Actual Behavior:
But i got the error "User: arn:aws:iam::32xxxxxxx65:user/vpnuser is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::32xxxxxxx65:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents"
### Steps to Reproduce:
1. Create the user on AWS with permissions described in https://github.com/StreisandEffect/streisand/blob/master/documentation/AWS.md,
2. Try to deploy the server with their Access Key

**Comment by alimakki** [comment]
Hi @i-land,

From the aws console, can you browse to the following IAM -> Users -> *youruser*. Once there, can you expand the policy?

I attempted to reproduce your issue however I was not able to.

For record, mine looks like the following:

![awsiam](https://user-images.githubusercontent.com/920624/38173750-500a48b6-3591-11e8-89cd-635d07fe70e0.png)

**Comment by alimakki** [comment]
Closing this issue as there are no responses from OP. If you're still facing issues, feel free to re-open, thanks.

**Comment by hazolsky** [comment]
I had the same problem recently. Allowing `iam:CreateServiceLinkedRole` action for `CloudwatchPolicies` solves the issue.

**Comment by hazolsky** [comment]
I had this same problem recently. Allowing `iam:CreateServiceLinkedRole` action fixes the issue.
