### ISSUE TITLE
Streisand does not installs to Existing server

### ISSUE THREAD

**Issue by bennymas** [StreisandEffect/streisand#1254]
### Expected behavior:
Streisand should be installed normally
### Actual Behavior:
**It fails on "detecting cloud providers for specific override"**
PLAY [Try to detect Cloud providers for specific overrides] *************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
fatal: [85.17.164.44]: FAILED! => {"changed": false, "cmd": "None -s system-product-name", "msg": "[Errno 2] No such file or directory", "rc": 2}
        to retry, use: --limit @/mnt/c/Users/boris/streisand/playbooks/existing-server.retry

PLAY RECAP **************************************************************************************************************************************************
85.17.164.44               : ok=3    changed=1    unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

**Also it won't generate streisand-diagnostics.md _(or I don't know how to get it)_.**

### Steps to Reproduce:
1. Get a brand new Ubuntu 16.04 x64 minimal VDS installation in "UA Hosting" company
2. Try to install Streisand for it. 
    *local installation in a VDS also fails.

[ contents of `streisand-diagnostics.md` here ]

##### *Output from `git rev-parse HEAD` in your Streisand directory :*
 85de53413d41c4be74dc122595882ee1e8070229

**Comment by nopdotcom** [comment]
Could you try a localhost deploy on this service? There's a helpful script, `util/ubuntu-dependencies.sh` which will install all the requirements for a localhost deploy.

**Comment by bennymas** [comment]
Did it just now, but no changes seems to be happen, the same error. Of course I ran this script before installation.

**Comment by cpu** [comment]
@bennymas I have a very strong suspicion this is a problem specific to your unsupported hosting provider. I'm not sure we have the resources to do extensive troubleshooting to help you with this provider. Are you able to use a supported provider (e.g. DigitalOcean, Linode, Amazon AWS, etc)?

**Comment by theLastOfCats** [comment]
`@/mnt/c/Users/boris/`
is it cygwin or what? Maybe there is a problem.

**Comment by cpu** [comment]
@theLastOfCats I'm not sure what your comment means in relation to the rest of this issue thread. Can you please start a new issue if you are having problems? Make sure to complete the new issue template answering the questions provided. Thanks!

**Comment by cpu** [comment]
I'm going to close this issue since it seems rather conclusively an issue with an unsupported host and the advanced provisioning mode.
