### ISSUE TITLE
No openvpn config files after custom install

### ISSUE THREAD

**Issue by kernie** [StreisandEffect/streisand#1256]
### Expected behavior:
After selecting custom install on a fresh Ubuntu 16.04 server and choosing openvpn only, clicking the downloads on the nginx web page should start a download dialogue for the config file.
### Actual Behavior:
After selecting custom install on a fresh Ubuntu 16.04 server and choosing openvpn only, clicking the downloads on the nginx web page leads to error 404
### Steps to Reproduce:
1. 
Install an Ubuntu 16.04 server.
2. 
Execute Streisand with custom install and select openvpn only. 
3. 
After install go to web page and download ovpn config file.

### Ansible Information

* Ansible version: 2.5.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.4
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: e863ac3b5615f8329238a0274f8a1775104d17da
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  False
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: False
* SSH forward user enabled: False
* L2TP enabled: False
* Configured number of VPN clients: 5

**Comment by nopdotcom** [comment]
I tested "existing server" against Vultr, which is sort of the worst case we've seen in the major providers. Could you try the deploy again, try a localhost deploy, or tell us more about the
##### *Target Cloud Provider*?

**Comment by kernie** [comment]
Probably my fault. Now I made a hard reset to the git repo and installed again. 

It's working as expected.

Sorry for the confusion.
