### ISSUE TITLE
Do "non-admin" users need the certificate?

### ISSUE THREAD

**Issue by pandemicsoul** [StreisandEffect/streisand#1257]
Hopefully a quick and simple question: Let's say I help a friend set up L2TP/IPsec using the credentials for my server. They never need to go to the site with instructions because I provide them the step-by-step. Do they still need the certificate? Or is the cert only needed if you want to connect to the server to see instructions?

**Comment by alimakki** [comment]
Hi @pandemicsoul, they're only needed if you want to access the gateway instructions/credentials.
