### ISSUE TITLE
EC2 instance metadata accessible through authenticated VPN access

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#1260]
### Expected behavior:

While Streisand **does not deploy any IAM roles with metadata accessible secrets** a Streisand instance deployed on AWS should not allow authenticated VPN clients access to instance metadata.

Streisand should block this access in the event advanced users configure IAM roles above-and-beyond the Streisand configuration with secrets that could be leaked. 

### Actual Behavior:

[AWS instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) is accessible at `http://169.254.169.254` through the Streisand VPN services.

### Steps to Reproduce:
1. Deploy to AWS
2. Create some kind of IAM role
3. Authenticate to a VPN service (e.g. Shadowsocks)
4. Access  http://169.254.169.254/latest/meta-data/iam/security-credentials/<ec2IamRole>.

### Proposed Remediation

Streisand should persistently null-route the EC2 metadata host on the Streisand server during the EC2 instance provisioning: e.g. with `route add -host 169.254.169.254 reject`

**Comment by nopdotcom** [comment]
Do we need the metadata during provisioning itself?

**Comment by cpu** [comment]
> Do we need the metadata during provisioning itself?

@nopdotcom Nope. We don't reference the metadata through this web interface at all. I suppose there's some chance that the Ansible module we use does but I'd be pretty surprised and it should show itself immediately as a provisioning error if so.

**Comment by alimakki** [comment]
I did test on an AWS instance, survived a reboot.

**Comment by nopdotcom** [comment]
I was playing with provisioning Lightsail a while ago. I never got it working, but I needed access to the metadata to get anywhere. I was worried that somewhere in the pile of *real* EC2 Ansible modules, there would be a dependency in there somewhere. No, just in `ec2_metadata_facts`, and given the way the Ansible code is structured, I don't expect that to change. So I'm happy.
