### ISSUE TITLE
TLS Ciphersuite/Protocol Enhancement

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#1261]
This is an omnibus issue for tracking a project-wide cleanup/enhancement of TLS ciphersuite and protocol settings. 

### Expected behavior:

Streisand components should emphasize best-practices for TLS ciphersuite deployment. Supported protocol versions should be kept to a minimum and favour modern and secure options. 

### Actual Behavior:

In several places Streisand's ciphersuite/protocol choices overly favour backwards compatibility and include insecure or dated options (e.g. TLS 1.0, 3DES...)

### Services to Address

* [x] - OpenConnect
* [x] - Stunnel`*`
* [x] - OpenVPN
* [x] - NGinx Gateway

`*` Note: Since Stunnel is strictly used as an OpenVPN obfuscation layer the ciphersuite/protocol choices here are less important than in other services.

### OpenConnect:

* TODO: Verify if Streisand is using good settings here. Evaluate the client compatibility impact of choosing more modern options.

### OpenVPN 

* TODO: Verify if Streisand is using good settings here. Evaluate the client compatibility impact of choosing more modern options.

### NGinx Gateway

* TODO: Verify if Streisand is using good settings here. Evaluate the client compatibility impact of choosing more modern options.

**Comment by alimakki** [comment]
Resolved as of #1267
