### ISSUE TITLE
Digital Ocean / access tokens text is confusing

### ISSUE THREAD

**Issue by dandaka** [StreisandEffect/streisand#1272]
### Expected behavior:

Text in wizard is consistent with DO website text.

New API access tokens → New Personal Access Tokens (or New API Personal Access Tokens)

### Actual Behavior:

Text in wizard:

```
New API access tokens can be generated in the DigitalOcean control panel.
https://cloud.digitalocean.com/settings/applications
  * When generating a new token, please note that the Write Scope is necessary
    in order to create Droplets.
```

Text in DO website:

```
Personal Access Tokens
Personal access tokens function like a combined name and password for API Authentication. Generate a token to access the DigitalOcean API
```

### Steps to Reproduce:

1. Launch Streisand
2. Select Digital Ocean
3. Find a step, where it asks about API key

**Comment by cpu** [comment]
@dandaka Do you think the updated text proposed by @Frichetten in #1317 resolves your observation? Thanks!

**Comment by dandaka** [comment]
@cpu Yes, thank you!
