### ISSUE TITLE
Hover effect on links in documentation is kinky

### ISSUE THREAD

**Issue by dandaka** [StreisandEffect/streisand#1273]
### Expected behavior:

Links are behaving.

### Actual Behavior:

Links are jumping around on hover.

http://take.ms/dnHfR

### How to fix the bug

These CSS rules are breaking the flow:

```
a:hover {
display: inline-block;
padding: 0 0.5em;
margin: 0 -0.5em -2px -0.5em;
}
```

### Steps to Reproduce:

1. Open generated documentation in MacOS Chrome
2. Open URL /shadowsocks/
3. Find a link "looking up your IP address"
4. See kinky behaviour

**Comment by nopdotcom** [comment]
Can confirm symptom, it's been nagging at me. I had mostly seen it on smaller screens, but the longer link text you've pointed out makes it really apparent. I think you're right that the real problem is that `a:hover` needs to have the same geometry as `a`.

Do you have a recommendation? I'd like to preserve the existing look, but something has to give.

**Comment by nopdotcom** [comment]
I take that back. This current link style is salvageable if the only time it's used is at the start of block-level elements, preferably solitary. We could just copy up the geometry from `a:hover` to `a`, solving the problem.

Links in runs of text have to do something different.

**Comment by dandaka** [comment]
If you propose ```display: inline-block;``` on all links, it will make all long links appear on new lines. This rule would prioritise decoration over readability.

![image](https://user-images.githubusercontent.com/2384694/38947204-23f64640-433c-11e8-8b3f-a14338ffe142.png)

Removing rules about will keep close to previous look, but paddings around links will be gone. Maybe for good.

Normal state

![image](https://user-images.githubusercontent.com/2384694/38947319-97d30116-433c-11e8-8e97-e6906bdfb6ab.png)

Hover state

![image](https://user-images.githubusercontent.com/2384694/38947336-a50852a0-433c-11e8-9d59-c52671db7c5a.png)

**Comment by cpu** [comment]
I think we can call this fixed with https://github.com/StreisandEffect/streisand/pull/1309

Thanks for reporting the problem and helping suggest a fix! I'm going to close this issue now but if the results of #1309 are still unsatisfactory we can reopen and plan further.
