### ISSUE TITLE
Update repository description & readme to mirror the removal of IPSec

### ISSUE THREAD

**Issue by kakysha** [StreisandEffect/streisand#1279]

**Comment by cpu** [comment]
Hi @Kakysha,

I just fixed the repository description. Thanks for catching that! :eagle: :mag: :trophy: 

The READMEs are already updated so I'm going to close this issue.

**Comment by kakysha** [comment]
@cpu at the very end there are still mentions about IPSec/L2TP, but anyway, thanx for updating the description. Made me frustrated, faced with streisand for the first time today, followed all the instructions and found no IPSec service in the generated docs. Google also clearly shows that other ppl do have it, then I digged into couple of last commits...

**Comment by cpu** [comment]
@kakysha The only mention I see now is the thank you to Paul Wouters. I don't want to remove that part (the thanks are still due :smile:) but I will update the language to make it clearer that this was help with a historic feature.

> Made me frustrated, faced with streisand for the first time today, followed all the instructions and found no IPSec service in the generated docs. Google also clearly shows that other ppl do have it, then I digged into couple of last commits...

I apologize for the frustration. There are some changes we're making in the near future that should help more clearly communicate this sort of change. We will soon have versioned releases and an explicit changelog between releases.

If none of the remaining services in Streisand are helpful for your usecase you might consider Algo: https://github.com/trailofbits/algo

Thanks for engaging with your feedback!
