### ISSUE TITLE
TASK [Register JSON file contents] fatal: [localhost]: FAILED! => {"changed": false, "cmd": 

### ISSUE THREAD

**Issue by re0n24** [StreisandEffect/streisand#1282]
TASK [Register JSON file contents] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["cat", "/home/wsupersp       eed/streisand.json"], "delta": "0:00:00.004129", "end": "2018-04-19 09:04:52.109       277", "msg": "non-zero return code", "rc": 1, "start": "2018-04-19 09:04:52.1051       48", "stderr": "cat: /home/wsuperspeed/streisand.json: No such file or directory       ", "stderr_lines": ["cat: /home/wsuperspeed/streisand.json: No such file or dire       ctory"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/wsuperspeed/streisand/playbooks/google.ret       ry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by re0n24** [comment]
Debian & Ubuntu same error all the time / Google Cloud

**Comment by re0n24** [comment]
A lot of errors with SSH keys also.... How to run it on the server? looks like it's not working at all, i'm newbee in coding and i'm telling you, your guide is usless! it doesn't work! every single step ***errors

**Comment by alimakki** [comment]
@re0n24, sorry to see you're having problems with deployment. Before we proceed, can you please follow the instructions on the issue template?



### Expected behavior:

### Actual Behavior:

### Steps to Reproduce:
1. 



[ contents of `streisand-diagnostics.md` here ]


### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

Thanks

**Comment by re0n24** [comment]
Expected behavior: I'd like to have wireguard server, is it ok?
Actual Behavior: every single time I have different errors! if I'm just doing step by step (using your guide) it's can't find any ssh keys in the custom directory. All the problems about these keys I think. 
Steps to Reproduce:
That problem happening when i'm trying to istall your server using lochalhost mode. 
[ contents of streisand-diagnostics.md here ]
TASK [Register JSON file contents] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["cat", "/home/wsupersp eed/streisand.json"], "delta": "0:00:00.004129", "end": "2018-04-19 09:04:52.109 277", "msg": "non-zero return code", "rc": 1, "start": "2018-04-19 09:04:52.1051 48", "stderr": "cat: /home/wsuperspeed/streisand.json: No such file or directory ", "stderr_lines": ["cat: /home/wsuperspeed/streisand.json: No such file or dire ctory"], "stdout": "", "stdout_lines": []}
to retry, use: --limit @/home/wsuperspeed/streisand/playbooks/google.ret ry

PLAY RECAP *********************************************************************
localhost : ok=2 changed=0 unreachable=0 failed=1

Additional Details:
Log output from Ansible or other relevant services (link to Gist for longer output): everything by default (I used your guide)
Target Cloud Provider: Google Cloud
Operating System of target host: Ubuntu 16 or Debian (same errors)
Operating System of client: -----------
Version of Ansible, using ansible --version : everything by default (I used your guide)
Output from git rev-parse HEAD in your Streisand directory : tried "root" and "*user"

**Comment by cpu** [comment]
> cat: /home/wsuperspeed/streisand.json: No such file or directory

@re0n24 This is the problem. After choosing your GCE region the following information is displayed:

```
The full path of your unique service account credentials file. Details on generating this can be found at 
https://docs.ansible.com/ansible/guide_gce.html#credentials
 and 
https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts
 [/home/wsuperspeed/streisand.json]: 
```

Have you read the two linked documentation pages?
1. https://docs.ansible.com/ansible/guide_gce.html#credentials
2. https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts

To use GCE you need to create that `/home/wsuperspeed/streisand.json` credentials file with a service account key you get from your GCE admin website.

**Comment by re0n24** [comment]
@cpu How about this problem?: 
_"TASK [validation : Fail if the Streisand SSH private key file doesn't exist] ****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The Streisand SSH private key \"openkey\" does not exist."}

TASK [validation : fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Ensure you specified an existing SSH private key file (not public).\n Try using `ssh-keygen -f openkey to generate your key if it does not exist\n"}
        to retry, use: --limit @/home/usertest/streisand/playbooks/validate.retry

PLAY RECAP **********************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=2"_ 

I have this problem every single time when I'm trying to install "Streisand", and idk what how to deal with it, I tried **"ssh-keygen -f openkey"** but after that, I have the same error. **"--limit @/home/usertest/streisand/playbooks/validate.retry"** - doesn't work also.

**Comment by cpu** [comment]
Hi @re0n24,

It sounds like the original problem you reported is resolved so I'd like to close this issue.

I opened a new issue for your second problem in the Streisand discussions repo. This is the best place to ask further support related questions: https://github.com/StreisandEffect/discussions/issues/115 I've commented there to ask you for some information.

Thanks!

**Comment by re0n24** [comment]
The second issue happening earlier than the original problem. So I simply can't get to the original problem because of this "ssh-keys"...
