### ISSUE TITLE
Add `-v` flag to recommended SSH forwarding command in user instructions

### ISSUE THREAD

**Issue by raabrp** [StreisandEffect/streisand#1284]
`ssh -ND {{ port }} forward@{{ server }}` gave no output on my host (Fedora 27, OpenSSH version 7.6p1).

I had to add a flag for verbosity to see the fingerprint of the server.

Would `ssh -vND {{ port }} forward@{{ server }} 2>&1 | grep SHA` be better here?

A PR seemed silly for a single line (?), but it this is ultimately an issue-driven question.

https://github.com/StreisandEffect/streisand/blob/ce6956ebfe60f30135c23a93eb8091cb9b6fd952/playbooks/roles/ssh-forward/templates/instructions.md.j2#L79

**Comment by cpu** [comment]
@raabrp Good catch. I think the `-v` was probably there originally and got dropped when we added the `-N` and made the `forward` user non-interactive. 

> A PR seemed silly for a single line (?)

Not at all :-) Do you want to submit the PR? It would save me some time and then you can have a nice "Contributor" badge next to your name :star2:

**Comment by zlatin** [comment]
The authenticity of host is checked only on the first connect. If you're connecting from the machine, from which you set up the server, the server is already in your `~/.ssh/known_hosts`. If you connect from other computer, you will get the prompt to confirm server fingerprint. So, as for me, we should change description whether the user will recieve the prompt to confirm fingerprint. The current command works properly.

**Comment by raabrp** [comment]
So the options for a PR:
1) Change description to read "If this is your first time connecting to the server, verify that the fingerprint matches one of these: { ... } , otherwise, no output will be given from the command."
2) Change the command to include a -v flag.

Who votes / decides?

**Comment by cpu** [comment]
@zlatin That's a good point but I think the SSH forwarding instructions are meant for folks beyond the individual that set up the Streisand instance so we shouldn't assume that the fingerprint is already known as a result of initial setup: it might be two different users.

@raabrp I think the simplest path forward is to add the `-v` - if a user has already connected and doesn't need to verify the fingerprint no harm is done by having it in the output :-)

**Comment by zlatin** [comment]
@cpu @raabrp I agree now that adding `-v` is the best option. So we can treat all users the same way not depending on number of times they connected.

⁣Sent from BlueMail ​

**Comment by cpu** [comment]
This was fixed in #1305. Thanks again @raabrp !
