### ISSUE TITLE
OpenVPN Ubuntu 16.04 instructions doesn't match UI

### ISSUE THREAD

**Issue by shotor** [StreisandEffect/streisand#1296]
### Expected behavior:

- Ubuntu OpenVPN extension to have "verify name exactly" + "additional TLS authentication mode"
- Initiate OpenVPN connection

### Actual Behavior:

- Missing fields in UI
- Connection fails

### Steps to Reproduce:
1. Install OpenVPN plugin `sudo apt-get install network-manager-openvpn-gnome`
2. Create new OpenVPN connection
3. Fill in fields
3. Click advanced
4. Go to TLS Authentication tab
5. Enter client name in "subject match"
6. Add key file to additional TLS authentication without setting mode
7. Save and connect => failure

![image](https://user-images.githubusercontent.com/6153419/39142291-82101dcc-472a-11e8-85b6-11c306077433.png)

Relevant section from manual:

Go to the TLS Authentication tab.
- Under Server Certificate Check choose verify name exactly and enter x-y-z as its value. (missing)
- Check Verify peer (server) certificate usage signature. (ok)
- Go to Additional TLS authentication or encryption. (ok)
- Select TLS-Crypt as the Mode. (missing)
- Select the ta.key file you downloaded from the client-files directory for the Key File. (ok)
- Click OK.

**Comment by Frichetten** [comment]
![image](https://user-images.githubusercontent.com/10386884/39390677-8cc9acde-4a5d-11e8-8497-7a8ca03944c3.png)
Hey @shotor, thanks for submitting an issue! I'm running Ubuntu 17.10 (I'm excited to upgrade to 18.04 later :]) and I have posted a screenshot of my configuration. It looks like some changes were made to NetworkManager between 16.04 and 17.10. In particular, it looks like in 17.10 you need to set a 'Mode' but 16.04 does not need this. 

I'd like to help with this issue, but I'd likely need a comment from @cpu. @cpu, Any guidance for how different versions of Ubuntu should be documented? I know that OpenVPN has a dedicated section to Ubuntu, but not the particular versions? Would you want Streisand to support all the LTS versions of the OS?

**Comment by cpu** [comment]
>  @cpu, Any guidance for how different versions of Ubuntu should be documented? I know that OpenVPN has a dedicated section to Ubuntu, but not the particular versions? Would you want Streisand to support all the LTS versions of the OS?

I don't think anyone has ever made a super thought out decision on this :-) If we know that 16.04, 17.10, and 18.04 need different instructions then having them all listed sounds good to me. As a note, 17.10 isn't an LTS release. I think its reasonable to expect laptop users to be using non-LTS releases and so within reason I'm ok with trying to support those releases too.

Thanks!!

**Comment by shotor** [comment]
Thanks @Frichetten @cpu - I'm trying to narrow down why it's not working with my settings - it times out after sending the ta.key file, not sure how to debug this issue further. Log:

```
Apr 28 15:42:32 xyz NetworkManager[1222]: <info>  [1524922952.7753] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: Started the VPN service, PID 11719
Apr 28 15:42:32 xyz nm-openvpn[11722]: OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Apr 28 15:42:32 xyz NetworkManager[1222]: <info>  [1524922952.8030] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN plugin: state changed: starting (3)
Apr 28 15:42:32 xyz NetworkManager[1222]: <info>  [1524922952.8030] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN connection: (ConnectInteractive) reply received
Apr 28 15:42:32 xyz nm-openvpn[11722]: Control Channel Authentication: using '/home/x/Downloads/ta.key' as a OpenVPN static key file
Apr 28 15:43:32 xyz NetworkManager[1222]: <warn>  [1524923012.5848] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN connection: connect timeout exceeded.
Apr 28 15:43:32 xyz NetworkManager[1222]: <warn>  [1524923012.5925] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN plugin: failed: connect-failed (1)
Apr 28 15:43:32 xyz NetworkManager[1222]: <info>  [1524923012.5927] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN plugin: state changed: stopping (5)
Apr 28 15:43:32 xyz NetworkManager[1222]: <info>  [1524923012.5928] vpn-connection[0xf067e0,b091703a-186c-41b1-8455-07747ce0c3fa,"vpn-server",0]: VPN plugin: state changed: stopped (6)
```

**Comment by alimakki** [comment]
@shotor Does your version of network manager allow you to choose between tls-auth and tls-crypt? My suspicion is that you may be having an issue there where it defaults to tls-auth instead of the latter.

**Comment by shotor** [comment]
@alimakki the only thing I can do through the ui (last screenshot) is set the key direction to 0 or 1. Neither works

This is the generated NetworkManager configuration:

```
[connection]
id=vpn-server
uuid=b091703a-186c-41b1-8455-07747ce0c3fa
type=vpn
autoconnect=false
permissions=
secondaries=

[vpn]
ta-dir=0
connection-type=tls
auth=SHA256
remote=x.x.x.x
cipher=AES-256-CBC
comp-lzo=yes
cert-pass-flags=0
proto-tcp=yes
port=443
remote-cert-tls=server
cert=/home/xyz/Downloads/client.crt
ca=/home/xyz/Downloads/ca.crt
key=/home/xyz/Downloads/client.key
ta=/home/xyz/Downloads/ta.key
service-type=org.freedesktop.NetworkManager.openvpn

[ipv4]
dns-search=
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
```

**Comment by alimakki** [comment]
Can you try this?:

```
[connection]
id=vpn-server
uuid=b091703a-186c-41b1-8455-07747ce0c3fa
type=vpn
autoconnect=false
permissions=
secondaries=

[vpn]
connection-type=tls
auth=SHA256
remote=x.x.x.x
cipher=AES-256-CBC
comp-lzo=yes
cert-pass-flags=0
proto-tcp=yes
port=443
remote-cert-tls=server
cert=/home/xyz/Downloads/client.crt
ca=/home/xyz/Downloads/ca.crt
key=/home/xyz/Downloads/client.key
tls-crypt=/home/xyz/Downloads/ta.key
service-type=org.freedesktop.NetworkManager.openvpn

[ipv4]
dns-search=
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
```

**Comment by shotor** [comment]
No dice, tried 443, also tried unchecking `use tcp` and setting the port to the udp port.

Could it have something to do with the OpenVPN version or how the network manager plugin on 16.04 executes OpenVPN?

I couldn't connect from command line either without first upgrading to 2.4. On 2.3 `tls-crypt` would not be recognized, changing it to `tls-auth` was recognized but would end up in a re-connect loop.

Only upgrading to 2.4 fixed it.

**Comment by alimakki** [comment]
I suspect that your version of Network Manager may be using/referencing OpenVPN 2.3 rather than 2.4, so yes. `tls-crypt` is for >= v2.4.

**Comment by shotor** [comment]
Would that mean connecting using NetworkManager on Ubuntu 16.04 is currently impossible?

**Comment by alimakki** [comment]
This may be the case, looking at the dependencies for network-manager-openvpn in 16.04 shows that it depends on OpenVPN 2.3.10: https://packages.ubuntu.com/xenial/network-manager-openvpn.

**Comment by hailengc** [comment]
Same issue, any update on this?

**Comment by Frichetten** [comment]
Hi @hailengc, are you having issues on 16.04? I was planning on working on this as time permits over the next few days to see if there was a simple work around.

**Comment by nopdotcom** [comment]
Thank you for the contribution! Good documentation is always a pain point. Ubuntu 16.04 is still supported by Canonical—are you interested in writing it up?

**Comment by Frichetten** [comment]
@alimakki @nopdotcom, I tried to find a good workaround to allow 16.04's network-manager to interpret the openvpn config and didn't come up with anything. As alimakki described above, there are some dependencies causing issues. Hypothetically the user _could_ compile and install a new network-manager from source and configure it that way but it would be a ton of work.

For #1408 I've been updating the documentation for the various supported Ubuntu versions. Would you guys be alright If for 16.04 I documented that the user must use the command line version of OpenVPN 2.4?

**Comment by nopdotcom** [comment]
Yeah, if it's broken in 16.04, just say that.

**Comment by alimakki** [comment]
Closing this issue as the documentation has been updated.

**Comment by hailengc** [comment]
@Frichetten Thanks for your work. I updated my system to 18.04 and everything was OK!
