### ISSUE TITLE
what is the default username and password for the web interface streisand?

### ISSUE THREAD

**Issue by jidckii** [StreisandEffect/streisand#1300]
what is the default username and password for the web interface streisand?

**Comment by cpu** [comment]
Hi @jidckii,

The username is always "streisand". There is no default password.

The password is picked randomly. Please check the `generated-docs` folder on the machine you ran Streisand from. Inside should be an `.html` document that includes instructions on connecting to the Streisand instance. This document has the username and password.

Good luck!
