### ISSUE TITLE
installer fails in freeebsd 10  (looking for apt inside freebsd)

### ISSUE THREAD

**Issue by digger3d** [StreisandEffect/streisand#1301]
Hello!
after installing bash (#pkg install bash) and hardlinking it into /bin (#ln /usr/local/bin/bash /bin/bash)
### Expected behavior:
complete installation
### Actual Behavior:
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 127, "stderr": "/bin/bash: apt: command not found\n", "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry
### Steps to Reproduce:
at aruba.it cloud vps
clean freebsd 10 server
[ contents of `streisand-diagnostics.md` here ]
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
root@DeepSignal:~/streisand # bash ./streisand

  S T R E I S A N D

Which provider are you using?
  1. Amazon
  2. Azure
  3. DigitalOcean
  4. Google
  5. Linode
  6. Rackspace
  7. Localhost (Advanced)
  8. Existing Server (Advanced)
: 7

LOCAL PROVISIONING WILL OVERWRITE CONFIGURATION ON **THIS** MACHINE.
THE MACHINE YOU ARE CURRENTLY EXECUTING THIS SHELL SCRIPT ON.
ARE YOU 100% SURE THAT YOU WISH TO CONTINUE?

Please enter the word 'streisand' to continue: streisand

Confirmed. Continuing

Do you wish to customize which services Streisand will install?
By saying 'no' Streisand will use the settings configured in /root/.streisand/site.yml

Press enter to customize your installation:

Confirmed. Customizing Streisand services.

 [WARNING]: Found both group and host with same name: localhost

Enter the path to your SSH private key, or press enter for default  [~/.ssh/id_rsa]:
How many VPN client profiles should be generated per-service (min: 1 max: 20)? Press enter for default  [5]: 15
Enable OpenConnect? Press enter for default  [yes]:
Enable OpenVPN? Press enter for default  [yes]:
Enable Shadowsocks? Press enter for default  [yes]:
Enable SSH Forward User? (Note: A SOCKS proxy only user will be added, no shell). Press enter for default  [yes]:
Enable sshuttle? (Note: A full shell access user will be added) Press enter for default  [no]:
Enable stunnel? Press enter for default  [yes]:
Enable tinyproxy? Press enter for default  [yes]:
Enable Tor? Press enter for default  [yes]:
Enable WireGuard? Press enter for default  [yes]:

PLAY [Customize enabled Streisand services] *************************************************************************************************************************************************************************************************

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [lineinfile] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=1    unreachable=0    failed=0

 [WARNING]: Found both group and host with same name: localhost

PLAY [Perform global variables validation] **************************************************************************************************************************************************************************************************

TASK [validation : Stat the Streisand SSH private key] **************************************************************************************************************************************************************************************
ok: [localhost]

TASK [validation : Fail if the Streisand SSH private key file doesn't exist] ****************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Stat the Streisand SSH public key] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [validation : Fail if the Streisand SSH public key file doesn't exist] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that OpenVPN optional variables are rational] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that Tinyproxy optional variables are rational] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that sshutle optional variables are rational] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that the maximum number of clients is set to a reasonable amount] ***********************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that at least one VPN is specified] *****************************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

 [WARNING]: Found both group and host with same name: localhost

PLAY [Prepare the new server for Ansible] ***************************************************************************************************************************************************************************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 127, "stderr": "/bin/bash: apt: command not found\n", "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

##### *Target Cloud Provider:*
aruba.it
##### *Operating System of target host:*
# uname -a
FreeBSD DeepSignal 10.3-RELEASE-p24 FreeBSD 10.3-RELEASE-p24 #0: Wed Nov 15 04:57:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
##### *Operating System of client:*
Windows, Android, Ubuntu
##### *Version of Ansible, using `ansible --version` :*
# ansible --version
ansible 2.5.0
  config file = /root/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/local/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Jul  5 2016, 01:21:33) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
git rev-parse HEAD
aadf6490df9a092901320a2de0ca5142d4ce90eb

**Comment by alimakki** [comment]
Hi @digger3d,

The only currently supported OS for deployment is Ubuntu 16.04.
