### ISSUE TITLE
Request for an option to create personal settings for each user.

### ISSUE THREAD

**Issue by DarthSlider** [StreisandEffect/streisand#1302]
Request to add a feature to make a way to add users besides basic straisand user. 
So every user would have they own config files so you would have an option to block users and/or block compromised VPN profiles just for a single user.

So for it should look like this: admin logs into the server and create a new straisand user. It should generate personal profiles, keys and manual pages for this user.
After that, each user should log in to your server with they own username and password and get its own manual.

**Comment by cpu** [comment]
Hi @DarthSlider,

Please open feature requests on the [StreisandEffect/discussions](https://github.com/StreisandEffect/discussions/) repo.

I was going to copy your feature request over there, but its already represented by https://github.com/StreisandEffect/discussions/issues/16.

Thanks!

**Comment by DarthSlider** [comment]
@cpu Thank you. I'm kinda new github user, so sorry for stupid request.
