### ISSUE TITLE
Cloud Cost Estimate in Documentation

### ISSUE THREAD

**Issue by drduker** [StreisandEffect/streisand#1303]
Please give an estimate for cloud provider cost as of a certain date so we know how much it would cost to deploy these services in the cloud with X amount of bandwidth per month.  Perhaps an estimate with google cloud and aws?  

This would be super helpful.  If I'm going to use this instead of a personal device that would work perfect for this, like a raspberry pi b3+ or personal machine, then I need to know how much it will cost me.  Even a rough estimate in your documentation would be really helpful.  

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by drduker** [comment]
Please respond quickly on this as I just want a rough estimate to move forward with my school project.  Thanks!!!

**Comment by alimakki** [comment]
@drduker maybe this link can get you started: https://github.com/StreisandEffect/discussions/issues/28
