### ISSUE TITLE
Azure: GPG import failure "can't connect to the agent: IPC connect call failed"

### ISSUE THREAD

**Issue by ekifox** [StreisandEffect/streisand#1308]
(item=2F2B01E7.security@openvpn.net.asc) => {
"changed": true, 
"cmd": ["gpg2", "--no-default-keyring", "--keyring", "/root/.gnupg/streisand/pubring.gpg", "--import", "/root/.gnupg/streisand/keys/2F2B01E7.security@openvpn.net.asc"], 
"delta": "0:00:05.073360", 
"end": "2018-04-26 23:42:32.174818", 
"item": "2F2B01E7.security@openvpn.net.asc", 
"msg": "non-zero return code", 
"rc": 2, 
"start": "2018-04-26 23:42:27.101458", 

"stderr": "gpg: key 2F2B01E7: public key \"OpenVPN - Security Mailing List <security@openvpn.net>\" imported\ngpg: can't connect to the agent: IPC connect call failed\ngpg: Total number processed: 1\ngpg:               imported: 1\ngpg: no ultimately trusted keys found",

"stderr_lines": ["gpg: key 2F2B01E7: public key \"OpenVPN - Security Mailing List <security@openvpn.net>\" imported", "gpg: can't connect to the agent: IPC connect call failed", "gpg: Total number processed: 1", "gpg:               imported: 1", "gpg: no ultimately trusted keys found"], "stdout": "",
"stdout_lines": []}

**Comment by cpu** [comment]
Hi @ekifox,

Can you please answer the questions from the new issue template? 

##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by ekifox** [comment]
Azure, IDK, Linux Mint 18.2

I used latest version of streisand from git.

**Comment by cpu** [comment]
@ekifox Is this bug repeatable? E.g. if you create a second Azure instance using the Streisand script does it also fail at this step?

I haven't been able to reproduce this on any of my own instances. 

> gpg: can't connect to the agent: IPC connect call failed"

It's possible we need to add an explicit Ansible `wait_for` on the GPG agent socket becoming available.

**Comment by ekifox** [comment]
The first thing I did after getting this error is repeated installation in a new region from scratch.
Unfortunately, the mistake was repeated at the same stage.

**Comment by cpu** [comment]
> Unfortunately, the mistake was repeated at the same stage.

@ekifox Ok, thanks for confirming. I'll try to come up with a branch you can run in Azure to see if we can find a fix.

**Comment by cpu** [comment]
Hi again @ekifox,

Can you give the branch from https://github.com/StreisandEffect/streisand/pull/1314 a try and see if it solves your problem? You can clone that branch by running: `git clone -b cpu-wait-for-gpg https://github.com/cpu/streisand.git`

Since I can't provision hosts on Azure to reproduce the bug myself I'm counting on you to let me know if this helped :-)

**Comment by ekifox** [comment]
It all worked, but the installation took two hours. The lowest tariff in Azur does not allow you to get a gigabit Internet channel and is too small for a full set of software. Maybe you should try changing the tariff in the installer to a more expensive one? Or make a choice for the client.

**Comment by cpu** [comment]
> It all worked, but the installation took two hours. 

I'm glad to hear that this change let the installation proceed. Thanks for verifying!

> The lowest tariff in Azure does not allow you to get a gigabit Internet channel and is too small for a full set of software. Maybe you should try changing the tariff in the installer to a more expensive one? Or make a choice for the client.

@ekifox Are you interested in submitting a pull-request to make this change? I agree that it sounds like the instance is resource constrained to the point of providing a pretty degraded experience. That said, I'm afraid I don't have much time/interest for Azure and the other currently active maintainers are in a similar place.

**Comment by cpu** [comment]
#1314 was merged to master. I'm going to close this issue now that the IPC connect failure was addressed.

Thanks again for filing the bug & confirming the fix! Much appreciated.
