### ISSUE TITLE
How to increase/add VPN client profiles from 20 to xxx?

### ISSUE THREAD

**Issue by mdmdd** [StreisandEffect/streisand#1330]
### Expected behavior:
Add unlimited client profiles.
### Actual Behavior:
Maximum 20 profiles allowed.
### Steps to Reproduce:
1. Normal setup procedure.

**Comment by nopdotcom** [comment]
We don't have much experience with larger deployments. If you're interested in experimenting, the check for max clients is in https://github.com/StreisandEffect/streisand/tree/master/playbooks/roles/validation . We'd be interested in hearing where you run into limits. I think some things will be broken at 200, although 100 may be OK. 

Performance with a large number of concurrent users is also unknown. Feedback would be useful to multiple projects, I suspect.

Having a lot of user accounts will cause usability problems for generated docs. User management needs a new design, but I don't want to drive it solely by the large account list case. It may be that 200 is workable technically, but not for new-deployer usability.

In any case, this scenario is not currently *supported*, so I'm going to close it on this issue list. StreisandEffect/discussions might be a good place to report back on experiments with larger servers.
