### ISSUE TITLE
GCE install fails: conditional check 'ansible_virtualization_type != 'lxc'' failed

### ISSUE THREAD

**Issue by Siequnu** [StreisandEffect/streisand#1332]
### Expected behavior:
Setup GCE Streisand server.
### Actual Behavior:
Fails on task TASK [common : Apply the custom sysctl values]
### Steps to Reproduce:
1. Setup Google Project as per documentation
2. Download JSON credential file
3. Run streisand in virtual environment setup with `util/venv-dependencies.sh`
4. Default setup.
5. Streisand runs, but fails with the following message
`
TASK [common : Apply the custom sysctl values] ********************************************

TASK [sysctl : Apply custom sysctl values] ************************************************
fatal: [35.229.166.197]: FAILED! => {"msg": "The conditional check 'ansible_virtualization_type != 'lxc'' failed. The error was: error while evaluating conditional (ansible_virtualization_type != 'lxc'): 'ansible_virtualization_type' is undefined\n\nThe error appears to have been in '/Users/user/streisand/playbooks/roles/sysctl/tasks/main.yml': line 3, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: Apply custom sysctl values\n      ^ here\n"}
`

### Ansible Information

* Ansible version: 2.5.2
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.11.6
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 3031d005010c6dea691ea2f96044592cfe40db04
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 2

**Comment by Siequnu** [comment]
The exact same setup worked a few minutes prior to wind up a AWS instance of Streisand.

**Comment by Siequnu** [comment]
This appears to be similar to #1319 and #1285. 

A temporary solution is this tree with lxc checks removed: https://github.com/nopdotcom/streisand/tree/nop-broken-ansible-gce-only

**Comment by nopdotcom** [comment]
I suppose I could open an issue tracker over on my repository, but here's a deploy from https://github.com/nopdotcom/streisand/tree/nop-broken-ansible-gce-only:

```
[streisand-gateway : Success!]
Server setup is complete. The `streisand-c976e36e75b5.html` instructions file in the generated-docs folder is ready to give to friends, family members, and fellow activists. Press Enter to continue.:
```

--------


### Ansible Information

* Ansible version: 2.5.2
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.11.6
* Python interpreter: python
* Python version: 2.7.15

### Streisand Information

* Streisand Git revision: c976e36e75b5df41424139ae246cfdf65c676141
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

------------

So I follow this with:

```
$ pip uninstall ansible && pip install ansible==2.5.0
Uninstalling ansible-2.5.2:
  Would remove:
    /private/tmp/ansible27/bin/ansible
    /private/tmp/ansible27/bin/ansible-config
    /private/tmp/ansible27/bin/ansible-connection
    /private/tmp/ansible27/bin/ansible-console
    /private/tmp/ansible27/bin/ansible-doc
    /private/tmp/ansible27/bin/ansible-galaxy
    /private/tmp/ansible27/bin/ansible-inventory
    /private/tmp/ansible27/bin/ansible-playbook
    /private/tmp/ansible27/bin/ansible-pull
    /private/tmp/ansible27/bin/ansible-vault
    /private/tmp/ansible27/lib/python2.7/site-packages/ansible-2.5.2.dist-info/*
    /private/tmp/ansible27/lib/python2.7/site-packages/ansible/*
Proceed (y/n)? y
  Successfully uninstalled ansible-2.5.2
[...]
Installing collected packages: ansible
Successfully installed ansible-2.5.0
```
OK, now we patch the version check code...

```diff 
$ git diff -u
diff --git a/util/ansible_check.sh b/util/ansible_check.sh
index 0c9988f..3d47953 100644
--- a/util/ansible_check.sh
+++ b/util/ansible_check.sh
@@ -6,7 +6,7 @@ set -e
 # check_ansible checks that Ansible is installed on the local system
 # and that it is a supported version.
 function check_ansible() {
-  local REQUIRED_ANSIBLE_VERSION="2.5.2"
+  local REQUIRED_ANSIBLE_VERSION="2.5.0"

   if ! command -v ansible > /dev/null 2>&1; then
     echo "
```

```
TASK [streisand-gateway : Success!] ******************************************************************************************************************************************************
[streisand-gateway : Success!]
Server setup is complete. The `streisand-stresand250.html` instructions file in the generated-docs folder is ready to give to friends, family members, and fellow activists. Press Enter to continue.:
```

### Ansible Information

* Ansible version: 2.5.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.11.6
* Python interpreter: python
* Python version: 2.7.15

### Streisand Information

* Streisand Git revision: c976e36e75b5df41424139ae246cfdf65c676141
* Streisand Git clone has untracked changes: yes
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by danihodovic** [comment]
Downgrading to ansible 2.5.0 solved the issue for me as well.

Thanks @Siequnu !

**Comment by milewski** [comment]
downgrading to version 2.5.0 gives me the following error:

```
Streisand requires Ansible version 2.5.2 or higher.
This system has Ansible ansible 2.5.0
  config file = /root/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609].

```

**Comment by Siequnu** [comment]
Commit 42c7ba7 merely centres the Streisand logo. One must roll back the  ansible version and change the version check in util/ansible_check.sh to 2.5.0.

**Comment by milewski** [comment]
That version is one version before the (Bump ansible CI to v2.5.2)https://github.com/StreisandEffect/streisand/commit/8fb464ac254783d5252a9778a6bdaba917b4c684 which pretty much does what you are saying....

**Comment by Siequnu** [comment]
Pity you didn’t bother mentioning the right commit the first time around.
