### ISSUE TITLE
starting gpg agent fails if it is already running

### ISSUE THREAD

**Issue by hamidzr** [StreisandEffect/streisand#1333]
### Expected behavior:
To restart when attempting to start the GPG agent and it's already running
### Actual Behavior:
exits with non zero return value
### Steps to Reproduce:
1. start the setup for existing server
2. break the setup after gpg agent is started
3. retry to setup

### Ansible Information

* Ansible version: 2.5.2
* Ansible system: Linux
* Host OS: Archlinux
* Host OS version:  NA
* Python interpreter: python
* Python version: 3.6.5

### Streisand Information

* Streisand Git revision: c81b4f4500248ad91f480b54a49705c4eed34efe
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by artyomboyko** [comment]
Same issue

**Comment by m-sharaf11** [comment]
just a temporary workaround i used
  
ssh into server  ( assume key is ~/.ssh/id_rsa )
`ssh root@{SERVER IP}` 
`ps -aef | grep gpg-agent`
`kill {PID} `
example: `kill 5935 `

**Comment by hamidzr** [comment]
#1335 takes care of this issue. Until it's merged, feel free to apply the patch manually.
