### ISSUE TITLE
FAILED  line "changed": false, "cmd": "xdg-open

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1338]
```[streisand-gateway : Success!]
Server setup is complete. The `streisand.html` instructions file in the generated-docs folder is ready to give to friends, family members, and fellow activists. Press Enter to continue.:

TASK [streisand-gateway : Attempt to open the instructions on Linux (if applicable). Errors in this task are ignored because the `xdg-open` command is not always available.] ***
fatal: [188.166.75.203 -> localhost]: FAILED! => {"changed": false, "cmd": "xdg-open ../generated-docs/streisand.html", "msg": "[Errno 2] No such file or directory", "rc": 2}
...ignoring
```

where is the mistake?
The streisand system almost settled but at the last step broke

**Comment by alimakki** [comment]
@rdbox there is no mistake, it appears that you have gone through a localhost install option. The very last step in the Streisand setup process is to open your web browser to show you how to connect to your gateway - something that is not possible via a CLI only environment. No worries, your install was successful (notice the `ignoring` at the very end) .

**Comment by rdbox** [comment]
Yes, I was able to go to the site https: // ipserver, but is this message normal? how to fix it
