### ISSUE TITLE
How to customize OpenVPN configuration before installation?

### ISSUE THREAD

**Issue by FlyingHavoc** [StreisandEffect/streisand#1348]
How to customize OpenVPN configuration before installation?

I have a wifi router with OpenVPN client, but it lacks some features that Streisand uses upon OpenVPN installation and configuration.

My OpenVPN client inside wifi router has only options for LZO compression (**comp-lzo**) and TLS-Auth (**tls-auth**) for HMAC authentication.

Currently after Streisand installation OpenVPN profiles are:
**compress lz4
tls-crypt**

Is there a way to set other defaults like comp-lzo and use tls-auth before Streisand installs OpenVPN instance?

Or can I just re-configure this easily after OpenVPN is already running? Guess this is not an easy one, since the key is generated for tls-crypt....

Thanks.

**Comment by cpu** [comment]
I'm going to close this issue since I think @alimakki covered the answer. Thanks all!
