### ISSUE TITLE
acmetool initial provisioning failure: port conflict(?)

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#1349]
### Expected behavior:

When configured correctly, a Streisand instance should be able to acquire a Let's Encrypt issued certificate during initial provisioning.

### Actual Behavior:

Sometimes (e.g. #1329) the configuration is correct but the initial provisioning fails. Streisand assumes there is a problem with the configuration and sets up Nginx to use a self signed certificate. Later, acmetool runs again and is able to issue a Let's Encrypt certificate.

### Steps to Reproduce:
1. Create a Streisand instance, set up a DNS A record once the IP is known.
2. Select that you wish to use Let's Encrypt
3. Enter the domain name
4. ??? Perhaps the port conflict [observed here](https://github.com/StreisandEffect/streisand/issues/1186#issuecomment-366242541) occurs, and provisioning fails

My current theory is that there is a condition in which acmetool tries to set up a Port 80 HTTP->HTTPS redirection service when we already have something bound to 80. This fails in the initial setup but seems to not cause problems later on.

This issue is a marker to remind me to try and reproduce this concretely to identify a fix.

**Comment by joiggama** [comment]
I've been having exactly the same issue when disabling tor in vars variable  for a noninteractive setup.

**Comment by cpu** [comment]
@joiggama Interesting! I hadn't made a connection with the Tor role. If you leave Tor enabled does the acmetool provisioning work as expected?

Apologies this issue remains unresolved - I've been starved for Streisand volunteer time lately.

**Comment by bensteinberg** [comment]
I'm seeing this problem too, in deployments to both AWS and Digital Ocean. I *think* it also has the effect of making Wireguard client credentials unusable after running `streisand` a second time in order to get the cert from Letsencrypt.

**Comment by leachim** [comment]
same issue with me. I just tried enabling tor and hope this will temporarily fix it.

**Comment by leachim** [comment]
Enabling Tor worked for me.

**Comment by thiras** [comment]
Enabling Tor doesn't work any more. Tor itself breaks the installation.
