### ISSUE TITLE
Wireguard is blocked in Iran

### ISSUE THREAD

**Issue by NightMachinary** [StreisandEffect/streisand#1351]
I can connect to my Wireguard server if I first tunnel my machine through the ShadowsocksR tunnel on the same server, but connecting normally would result in no net connection.

### Ansible Information

* Ansible version: 2.5.3
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.3
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 4c791b045c14725075e76dd766b8e576db311707
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by cpu** [comment]
Hi @NightMachinary,

Thanks for providing this connectivity anecdote. Since this is not an issue that Streisand can address with a code change in our project I'm going to close this ticket. I encourage you to try an alternative connection method to see which works best in your environment. Thanks!

**Comment by NightMachinary** [comment]
It is unblocked now. Internet here is so chaotic. 😂

**Comment by parsalotfy** [comment]
Hi @NightMachinary 
is it still blocked ?
how can wireguard protocol get blocked ?!
I created a wireguard server and I cannot connect to it ...

**Comment by NightMachinery** [comment]
[**@parsalotfy**](https://github.com/parsalotfy) commented on [Oct 28, 2020, 9:54 PM GMT+3:30](https://github.com/StreisandEffect/streisand/issues/1351#issuecomment-718123867 "2020-10-28T18:24:45Z - Replied by Github Reply Comments"):
> Hi [@NightMachinary](https://github.com/NightMachinary)  
> is it still blocked ?  
> how can wireguard protocol get blocked ?!  
> I created a wireguard server and I cannot connect to it ...

It's not blocked for me. You probably have a configuration problem. Try using https://github.com/IAmStoxe/wirehole .

**Comment by parsalotfy** [comment]
this is my configuration :

```
docker run -d \
  --name=wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e SERVERURL=lordkian.ir `#optional` \
  -e SERVERPORT=51820 `#optional` \
  -e PEERS=1 `#optional` \
  -e PEERDNS=auto `#optional` \
  -e INTERNAL_SUBNET=10.13.13.0 `#optional` \
  -e ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 `#optional` \
  -p 51820:51820/udp \
  -v /path/to/appdata/config:/config \
  -v /lib/modules:/lib/modules \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --restart unless-stopped \
  linuxserver/wireguard
```


I don't know why it does not connect !

![image](https://user-images.githubusercontent.com/30390810/97483048-361d8a00-196c-11eb-93b1-bfbd069b19a8.png)

I think wireguard protocol is blocked in Iran.What do you think ?
