### ISSUE TITLE
Some Iranian VPNs are able to use OpenVPN directly

### ISSUE THREAD

**Issue by NightMachinary** [StreisandEffect/streisand#1352]
The OpenVPN server installed by Streisand is not connectable without stunnel in Iran, but I have some OpenVPNs accounts that do connect! Here is one such `.ovpn` profile:
```
client
dev tun

remote us.ovadd.com 53 udp

persist-key
persist-tun
resolv-retry infinite
route-metric 1

nobind
pull

verb 3

auth-user-pass


<ca>
-----BEGIN CERTIFICATE-----
MIIB0DCCAVWgAwIBAgIJAOJyDpIMMGK0MAoGCCqGSM49BAMCMA8xDTALBgNVBAMM
BE5leHQwHhcNMTgwMjIyMTAzMzMwWhcNMjgwMjIwMTAzMzMwWjAPMQ0wCwYDVQQD
DAROZXh0MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAErWw4c9tA7uyp9pE6OrOGpS76
3T8nu+Gy4VowpzRKOmdWJZ+Cx8IV3y/tc+ipkup7Q+hBy8oA18QnAwI2D2qokfII
hdXHOipsgsclWX2yxRvppxd/WQPkgqeSX/x+epIio30wezAdBgNVHQ4EFgQUfdQi
jRfUJ/+/21QE+6MUzTDnNLwwPwYDVR0jBDgwNoAUfdQijRfUJ/+/21QE+6MUzTDn
NLyhE6QRMA8xDTALBgNVBAMMBE5leHSCCQDicg6SDDBitDAMBgNVHRMEBTADAQH/
MAsGA1UdDwQEAwIBBjAKBggqhkjOPQQDAgNpADBmAjEA5/0xoi9xlt+jxcjEhTff
7kNWTIUdJEmbUHGegh7d6zH4do7traP0ThdieaEMT7uQAjEAnZfwF9KythTQAsOM
DDDfG7bkfC6pssuLmC7aPPKUyMF5EfSyoMAuuXd3LV2KOuZC
-----END CERTIFICATE-----
</ca>

<cert>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7c:c7:5f:33:b9:bb:fc:e1:43:fc:95:db:e8:eb:d2:14
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=Next
        Validity
            Not Before: Feb 22 10:34:02 2018 GMT
            Not After : Feb 20 10:34:02 2028 GMT
        Subject: CN=client
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:da:4a:a6:40:62:d6:03:21:04:1c:cb:98:a9:59:
                    06:33:af:4d:0e:86:60:fa:08:0c:a7:19:e5:6e:11:
                    05:e7:89:b7:de:8a:c6:ca:3a:3d:29:1f:11:1c:91:
                    21:a8:e0:06:ef:22:8a:24:cf:34:2f:c9:db:3c:a8:
                    b8:2b:9b:da:e1:21:4e:54:1d:9d:62:e0:18:e2:02:
                    11:ed:b8:05:dc:92:7b:79:51:05:55:d5:fd:9e:d9:
                    c3:b8:f1:f6:37:aa:39
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Subject Key Identifier:
                E0:30:59:1D:8C:FF:59:E3:A1:21:35:1C:EE:55:40:F4:CE:35:1E:94
            X509v3 Authority Key Identifier:
                keyid:7D:D4:22:8D:17:D4:27:FF:BF:DB:54:04:FB:A3:14:CD:30:E7:34:BC
                DirName:/CN=Next
                serial:E2:72:0E:92:0C:30:62:B4

            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Key Usage:
                Digital Signature
    Signature Algorithm: ecdsa-with-SHA256
         30:65:02:31:00:b7:72:5b:f8:e7:8b:61:3b:ab:44:b7:01:03:
         ab:fa:eb:a9:9b:f0:6c:19:c6:ec:ff:03:f6:e0:08:17:f7:79:
         ab:cb:73:91:3a:2e:a5:da:b1:4a:2c:e4:e0:07:ae:89:20:02:
         30:65:d6:06:d6:5f:75:1b:95:03:ad:41:f2:3b:97:1f:0d:99:
         46:12:d3:9c:6c:70:0a:81:a5:47:88:18:35:58:15:fa:cc:e7:
         08:a5:5e:01:a3:67:b1:6b:36:33:05:ff:13
-----BEGIN CERTIFICATE-----
MIIB7DCCAXKgAwIBAgIQfMdfM7m7/OFD/JXb6OvSFDAKBggqhkjOPQQDAjAPMQ0w
CwYDVQQDDAROZXh0MB4XDTE4MDIyMjEwMzQwMloXDTI4MDIyMDEwMzQwMlowETEP
MA0GA1UEAwwGY2xpZW50MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE2kqmQGLWAyEE
HMuYqVkGM69NDoZg+ggMpxnlbhEF54m33orGyjo9KR8RHJEhqOAG7yKKJM80L8nb
PKi4K5va4SFOVB2dYuAY4gIR7bgF3JJ7eVEFVdX9ntnDuPH2N6o5o4GQMIGNMAkG
A1UdEwQCMAAwHQYDVR0OBBYEFOAwWR2M/1njoSE1HO5VQPTONR6UMD8GA1UdIwQ4
MDaAFH3UIo0X1Cf/v9tUBPujFM0w5zS8oROkETAPMQ0wCwYDVQQDDAROZXh0ggkA
4nIOkgwwYrQwEwYDVR0lBAwwCgYIKwYBBQUHAwIwCwYDVR0PBAQDAgeAMAoGCCqG
SM49BAMCA2gAMGUCMQC3clv454thO6tEtwEDq/rrqZvwbBnG7P8D9uAIF/d5q8tz
kToupdqxSizk4AeuiSACMGXWBtZfdRuVA61B8juXHw2ZRhLTnGxwCoGlR4gYNVgV
+sznCKVeAaNnsWs2MwX/Ew==
-----END CERTIFICATE-----
</cert>

<key>
CENSORED
</key>
```

### Ansible Information

* Ansible version: 2.5.3
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.3
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 4c791b045c14725075e76dd766b8e576db311707
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by cpu** [comment]
Hi @NightMachinary 

Please do not post private keys to the issue tracker.

> The OpenVPN server installed by Streisand is not connectable without stunnel in Iran, but I have some OpenVPNs accounts that do connect! Here is one such .ovpn profile:

I don't understand what you're asking. What is the question or bug you are reporting? If the bug is that OpenVPN without Stunnel doesn't function in Iran there is little we can do: that's why stunnel is available as an option.

**Comment by NightMachinary** [comment]
@cpu I am saying I can connect using this .ovpn profile without stunnel, which suggests direct OpenVPN connections are possible from Iran, with the right setup.

**Comment by NightMachinary** [comment]
The private key is also useless, I believe. You need username/password to use it.

**Comment by cpu** [comment]
> I am saying I can connect using this .ovpn profile without stunnel, which suggests direct OpenVPN connections are possible from Iran, with the right setup.

@NightMachinary That's good news & I'm glad to hear it :-) Is there somewhere in the Streisand documentation that suggested this wouldn't be possible? Are you sharing this as an FYI? Can you help me understand what action you were hoping we would take with the information?

Thanks!

**Comment by NightMachinary** [comment]
Yeah, just sharing the info; I thought you might also be able to discern
something from the ovpn profile. I am worse than a noob in these matters,
so I can’t quite judge if the info will be worthwhile. :-)
It’s also possible that someone reading this has some connections with
Iranian networking professionals and could ask them how they do it.

**Comment by alimakki** [comment]
@NightMachinary I think you're misunderstanding what the private tls-auth/crypt key in OpenVPN is used for - it's definitely not useless and making it public can greatly help a censor DoS OpenVPN connections.

**Comment by alimakki** [comment]
The only difference I'm seeing in the profiles (aside from what type of certificates) is the port number - perhaps port 53 is left untouched by censors in that region.

**Comment by NightMachinary** [comment]
@alimakki Hmm. Well, it is really easy for the authorities to block them anyways, they use the national banking system to sell VPNs. I don't think the government targets specific sellers like this. And I even suspect they might be in league with the censors, sharing the profits. Iran's censoring has always been meant as more of a barrier for the common people, religious ones, and children; They mostly never use a paid VPN service.

**Comment by NightMachinary** [comment]
@alimakki How can I change the OpenVPN server deployed to use that port?

**Comment by hadifarnoud** [comment]
@NightMachinary they are probably connected to government and their server is whitelisted (avoid using them, probably collect your data too). I suspect even if you use port 53, it won't help.

**Comment by NightMachinary** [comment]
Unfortunately, I am buying my own server from Iranian companies as well, so
privacy is ever so distant. :(
(Why? No cloud provider sells VPSes to Iranians. Those fools.)

**Comment by h-rezaei** [comment]
Hello from Iran
Local vpn companies  first connect you to an Iranian server in a local  datacenter (extremely unprofessional and unsafe)

then from then on, I'm suspecting that those servers have open access to the internet and they are used to monitor the vpn traffic that they're getting from the users.
Or they use some sort of gateway to redirect openvpn connections from users to a server in EU that they also own.


My point though, is that the reason that direct open vpn connections are open is because you're being redirected through Iranian datacenters

**Comment by cpu** [comment]
I think this issue has become a general discussion and I'd suggest interested parties move to a new issue in the [Streisand discussions repository](https://github.com/StreisandEffect/discussions) instead.

If there's a concrete change that the Streisand project should be considering that I'm missing from this thread please open a new issue that clearly identifies the change being requested. Thanks all!
