### ISSUE TITLE
Shadowsocks is blocked in Iran, use ShadowsocksR

### ISSUE THREAD

**Issue by NightMachinary** [StreisandEffect/streisand#1353]
I can easily connect to the SSR server I set up on my Streisand server, but not to the Shadowsocks server set up by Streisand. I also tried setting up a normal Shadowsocks server myself, and that was blocked as well.
I used [this guide](https://www.tipsforchina.com/how-to-setup-a-fast-shadowsocks-server-on-vultr-vps-the-easy-way.html) to set up SSR.

### Ansible Information

* Ansible version: 2.5.3
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.3
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 4c791b045c14725075e76dd766b8e576db311707
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by cpu** [comment]
This looks like a feature request for ShadowsocksR support. Please post new feature requests in [the Streisand discussions repository](https://github.com/StreisandEffect/discussions/issues).

Thanks
