### ISSUE TITLE
I suggest using env public ip server

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1358]
I want to add from myself a proposal to use a global variable in which the value public ip address will be specified.
 
And such a variable will be used in all programs, it will be very convenient in case of changing the public address.

Or during the download of a droplet of snapshots the public ip will be downloaded from the script automatically thus

Downloading streisand public ip will be correctly specified in env and will always work correctly in all programs.

what do you think this can be developed?
To develop such a script?

**Comment by nopdotcom** [comment]
This would be very useful, but I think it's quite difficult. See https://github.com/StreisandEffect/discussions/issues/17 .
