### ISSUE TITLE
RFE: Provide .mobileconfig files to autoconfigure iOS devices

### ISSUE THREAD

**Issue by nodomain** [StreisandEffect/streisand#136]
This would even further ease setup. Also I would love to see the possibility to enable iOS connect-on-demand.

**Comment by jlund** [comment]
I am not familiar with either of these concepts. Any links or other information that you could provide would be helpful.

**Comment by mveplus** [comment]
This may provide some inside...
[Introduction .mobileconfig] (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/iPhoneOTAConfiguration/Introduction/Introduction.html)
[XML profile] (https://developer.apple.com/library/ios/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206)
[Sign Apple mobileconfig files - nor necessary ] (https://wiki.geant.org/display/tcs/Sign+Apple+mobileconfig+files) 
Management tools: [iPhone Configuration Utility free] (http://www.enterpriseios.com/wiki/iPhone_Configuration_Utility) [or this] (https://www.theiphonewiki.com/wiki/IPhone_Configuration_Utility), [Apple Configurator free] (https://itunes.apple.com/us/app/apple-configurator/id434433123?mt=12) [or this] (https://itunes.apple.com/us/app/os-x-server/id883878097), any text editor.

**Comment by gnbio** [comment]
Have been using [Cloak ](https://www.getcloak.com/) on iOS because of the support for VPN-on-Demand; was any progress made on this, there was some more (probably now outdated) details [here](https://www.derman.com/blogs/iOS-OpenVPN-OnDemand-Setup).
Thanks, such a great service!

**Comment by kehao95** [comment]
It surely a feature nice to have, especially for those non-skilled users. It will save their effort to add and config VPN user/pass/PSK etc. 
.mobileconfig is a kind of config file for macOS & iOS. It can pre-config loads of VPNs in a single file. they can install the VPN payloads within clicks. 
If you are using mac, I'd suggest you  download the Apple Configurator 2 on Mac AppStore to play with it.
And [here is a demo shows what you can do with it.](http://g.recordit.co/1BBduOkv8G.gif)

**Comment by quinncomendant** [comment]
I've been discussing in #512 how a "Connect on demand" option is setup by the Algo VPN for macOS and iOS users via .mobileconfig files.

Here is the mobileconig file generated by my Algo setup (with keys redacted) as an example of how it should be done: [algo.mobileconfig.zip](https://github.com/jlund/streisand/files/809972/algo.mobileconfig.zip)
