### ISSUE TITLE
Wireguard. No handshakes from peer to server after peer restart. Until server restart wg-quick.

### ISSUE THREAD

**Issue by stepanovdg** [StreisandEffect/streisand#1364]
### Expected behavior:
Wireguard client on openwrt router connects successfully to Streisand server on restart.
### Actual Behavior:
Wireguard client on openwrt router connectsto Streisand server on restart.
But latest handshake show never. Also on server handshakes doesn`t appear.
### Steps to Reproduce:
1. That issue does not appears always. But from time to time. (Seems like bad connection wrapping). 
If my router was disabled due out of power. After restart it connects to wireguard, pinging server but no handshakes. 

On server peer lists like connected but no handshakes.

restarting wg-quick@wg0 on server helps. After such restart router connects successfully and all is working. 

Just not sure what could be real reason inside and how to automate workaround solution (how to check that service required to reboot) - but it also seems  strange to me.

**Comment by cpu** [comment]
Hi @stepanovdg,

Streisand's generated documentation does not include instructions for OpenWRT and WireGuard. If you're interested in getting that working you're unfortunately on your own. 

I recommend you start a [Streisand discussions](https://github.com/StreisandEffect/discussions/issues) issue if you want to discuss OpenWRT support.

Thanks!
