### ISSUE TITLE
[Feature Request] add V2Ray support

### ISSUE THREAD

**Issue by hadifarnoud** [StreisandEffect/streisand#1365]
I just found this awesome new internet censorship circumvention tool called V2Ray. Apparently it's used in China to bypass GFW. It's hard to setup and difficult to understand but if it works to bypass GFW, it's probably very good.

I think streisand can add v2ray and make the whole thing super easy.
https://www.v2ray.com/

**Comment by nopdotcom** [comment]
Closed in favor of https://github.com/StreisandEffect/discussions/issues/85 , which I have been neglecting. :-( 

Thanks for the reminder.
