### ISSUE TITLE
[Feature Request] Client MFA

### ISSUE THREAD

**Issue by bytemare** [StreisandEffect/streisand#1373]
Hi there,

Do you have plans on adding MFA for client connections ?
I'm thinking of Google Authenticator, Yubikeys and stuff like that.

Thanks !

**Comment by cpu** [comment]
Hi @bytemare,

> Do you have plans on adding MFA for client connections ?

There are no plans for this presently.

In the future we would prefer feature requests/questions on the [Streisand discussion repo](https://github.com/StreisandEffect/streisand-discussions/issues/ ). Thanks!

**Comment by bytemare** [comment]
Ok, thanks :)

And sorry for asking here, I missed the note for the discussion repo. Will do from now on !

**Comment by cpu** [comment]
> And sorry for asking here, I missed the note for the discussion repo. Will do from now on !

No problem! Thank you.
