### ISSUE TITLE
Installation fails. Problem with OpenVPN repos?

### ISSUE THREAD

**Issue by aryonoco** [StreisandEffect/streisand#1375]
### Expected behavior:

Installation to finish

### Actual Behavior:

Installation fails on a brand new Ubuntu 16.04 server. 

Tried on both Linode and DigitalOcean with same results. 

### Steps to Reproduce:
1. Start a fresh installation of Streisand with all default values. 
2. Proceed until OpenVPN installation. 
3. At the point of inserting OpenVPN official repository, installation fails. Here's the output (I've hidden my IP address):
```

TASK [openvpn : Add the official OpenVPN repository] ***********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException
fatal: [X.X.X.X]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_v7AY5X/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_v7AY5X/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 456, in update\n    raise FetchFailedException()\napt.cache.FetchFailedException\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

RUNNING HANDLER [ssh : Restart SSH] ****************************************************************************************

RUNNING HANDLER [openconnect : Restart rsyslog for OpenConnect] ************************************************************

RUNNING HANDLER [dnsmasq : Restart dnsmasq] ********************************************************************************
        to retry, use: --limit @/home/aryan/streisand/playbooks/linode.retry

PLAY RECAP *****************************************************************************************************************
X.X.X.X                 : ok=105  changed=86   unreachable=0    failed=1
localhost                  : ok=11   changed=2    unreachable=0    failed=0

```

[ contents of `streisand-diagnostics.md` here ]

```

### Ansible Information

* Ansible version: 2.5.4
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  18.04
* Python interpreter: python
* Python version: 2.7.15rc1

### Streisand Information

* Streisand Git revision: 917cf8ef5d02dc19af480a4073cca3930a62f0c0
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

```

I'm assuming there's something wrong with the OpenVPN repo. Is there a way to just use the OpenVPN that's available in the Ubuntu repos? 

Thanks.

**Comment by aryonoco** [comment]
Indeed https://build.openvpn.net/debian/openvpn/stable is not accessible right now, and https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos says that they are currently down for maintenance. 

My question is, why add this third party repo? Does the official OpenVPN build add any unique features that are not available in the Ubuntu build? In my experience, every third party repo added to Ubuntu/Debian is adding another potential point of failure and reduced chances of successful updates/upgrades in future.

**Comment by alimakki** [comment]
@aryonoco The official repo gives us the latest version (2.4+) giving us lz4 compression and tls-crypt most importantly. The Ubuntu builds are still hovering on the 2.3 branch with security fixes backported.

**Comment by aryonoco** [comment]
@alimakki Fair enough. 

The OpenVPN repos are back up, they were down for over 12 hours. 

I just went through and completed a new installation and all is good. 

Closing the ticket.
