### ISSUE TITLE
I propose to supplement streisand DNSCrypt or Stubby

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1376]
Dear developers, consider my proposal to add a new package to streisand as ```DNS over TLS.```
I believe that DNS queries should be encrypted, in China they analyze what kind of DNS traffic.

I installed it as a test on my local ```Stubby``` machine, and my ping went up and became more stable, of course, it would not save from locks, but the connection and my main Internet channel became not much more stable

**Comment by nopdotcom** [comment]
How would this be configured? I agree that DNSCrypt is a good thing, and we should support it. But would this be inside or outside the VPN network? Bound to 127.0.0.1 on the server, the only way to reach it is through the VPNs. The goal is to protect the Streisand *server* from people from DNS mischief?

**Comment by rdbox** [comment]
inside vpn I'm in a mood right now.
DNSCrypt + dnsmasq with internal ip 10.8.0.1.
I pass this ip as a push command "dhcp-option DNS 10.8.0.1"

**Comment by nopdotcom** [comment]
So, listen on 10.8.0.1, 10.9.0.1, and 10.192.122.1, depending on which is being pushed? That works for me.

My suggestion is: Keep dnsmasq on port 53 for now. Run DNSCrypt/Stubby on 127.0.0.1:1053, and add this to /etc/dnsmasq.d/dnscrypt:

```
server=localhost#1053
```

Maybe we need a standard internal "service" network, like 10.10.0.0/24, available to all authenticated users? Here's a possible `/etc/network/interfaces.d/service0`:

```
auto service0

iface service0 inet static
      pre-up ip link add service0 type dummy
      post-down ip link del service0

      address 10.10.0.1
      netmask 255.255.255.0
```

**Comment by rdbox** [comment]
it is interesting!
@nopdotcom Do you add it to the basic configuration in the new streisand package?

**Comment by 19hundreds** [comment]
sorry, I don't understand. Do you wanna see the code of the script?

**Comment by rdbox** [comment]
@19hundreds yes

**Comment by 19hundreds** [comment]
sure! I'll try to grab it when I get home

**Comment by 19hundreds** [comment]
Here it is. It's a very simple (stupid?) script which runs in cron every 5 minutes

```
#!/bin/bash
# dnscrypt sometimes has issues with the main (and random) DNSs because they are not as 
# reliable as mainstream DNS services like 8.8.8.8
# To fix this I perform a query every minute to a fake domain which can not be resolved
# and therefore be cached by dnsmasq. This returns exit status 0 if the main DNS server 
# resolves the query but if something is wrong with the main DNS the exit status is 9

fakedomain="rlcp2asnuh89ntaenscrgcraeakjkjxieuo.com"
dig @127.0.0.1 ${fakedomain} +time=2 &> /dev/null
if [ "${?}" != "0" ]; then
	service dnscrypt stop
	service dnscrypt start
	service dnsmasq stop
	service dnsmasq start
	exit 3
fi
```

**Comment by rdbox** [comment]
@19hundreds perfectly suits me

**Comment by 19hundreds** [comment]
@rdbox don't forget to enable "random dns" (I'm going by heart, look through the file to find the exact syntax) in the dnscrypt-proxy config file

**Comment by cpu** [comment]
Hi folks. There is an existing discussions thread for this topic: https://github.com/StreisandEffect/discussions/issues/14 I recommend that folks add their thoughts there and only use this repository when you have a pull request for review.

Thanks!
