### ISSUE TITLE
shadowsocks and openvpn android does not work

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1379]
I need help, I do not understand the reason.
And so in order I put ```streisand``` all fine not PC all works well.

Then I decided to configure the software on the androyd in the mobile device
and then I ran into the ```shadowsocks and openvpn``` samples only partially.
All sites that are blocked in China, namely the same Google and Instagram it does not work.
The browser in the error server is not available
Application instagram simply does not want to update the tape posts.

P.S. Only the third-party ```ExpressVPN``` program works as it should.
I ask for help. I want to configure my vpn

it may be necessary to customize something in addition, or there are instructions how to set up for androyd for those who are in China

**Comment by denoza** [comment]
I am not sure what you mean? May be you try to connect via `simple-obfs`.

**Comment by rdbox** [comment]
I had to download another version of openvpn
https://play.google.com/store/apps/details?id=net.openvpn.openvpn

only this version has earned.


but I have another problem, the sites are opened but the banking applications do not work.
Although through the application ExpressVPN everything works.
I can not figure out how to set up openvpn so that all traffic goes through it

**Comment by boreddeveloper** [comment]
I would be better if you the app though. I was in China of student exchange was using PureVPN app there. Man censorship in China is not cool

**Comment by rdbox** [comment]
@boreddeveloper 
Yes, I know, but I'm experiencing data leaks.
I can not believe the companies that provide access to the VPN service

**Comment by boreddeveloper** [comment]
> Yes, I know, but I'm experiencing data leaks.

is AWS open in China ?

**Comment by rdbox** [comment]
my vps Digital Ocean

**Comment by boreddeveloper** [comment]
> my vps Digital Ocean

good approach. 

have your tried algo on DO?

I used it on Azure got free account using bizspark

**Comment by rdbox** [comment]
but this problem does not solve the problem in the program itself OpenVPN or you must configure the config file correctly

**Comment by rdbox** [comment]
but this problem does not solve the problem in the program itself OpenVPN or you must configure the config file correctly

**Comment by rdbox** [comment]
but this problem does not solve the problem in the program itself OpenVPN or you must configure the config file correctlyё

**Comment by rdbox** [comment]
but this problem does not solve the problem in the program itself OpenVPN or you must configure the config file correctlyё

**Comment by boreddeveloper** [comment]
As one of the forum members pointed out. OpenVPN is blocked in China. Use Algo then it uses IKeV 2 or WireGuard. I thing it might work on DO. I have high expectations for wireguard as it is new and might not be blocked in China

**Comment by rdbox** [comment]
I'll disappoint you. ```WireGuard``` does not work for android.
China now tightened the nuts, and raised the amplified GFW setting

```stunnel``` does not work for me either

**Comment by rdbox** [comment]
I have the version of Android 4.2.2
The current version of shadowsocks does not work
It's more correct to say that it works but Google sites do not open

**Comment by nopdotcom** [comment]
What happens when you go to Google sites? CAPTCHA?

**Comment by strixaluco** [comment]
> I have the version of Android 4.2.2
4.2.2 means API 17¹, while Shadowsocks client for Android dropped support of API 19² (Android 4.4) since 4.4.6 version³. There were quite a few changes in the client since then⁴, some possibly crucial. Have you tried using Shadowsocks on Android > 5.0?

¹ — https://developer.android.com/about/versions/android-4.2
² — https://developer.android.com/about/versions/android-4.4
³ — https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.4.6
⁴ — https://github.com/shadowsocks/shadowsocks-android/compare/v4.4.6...master

**Comment by rdbox** [comment]
>What happens when you go to Google sites? CAPTCHA?

when I go I use shadowsocks on a site such as Google Instagram Facebook
then I have an error site is not available.
And all other sites such as bing yahoo they work


> 4.2.2 means API 17¹, while Shadowsocks client for Android dropped support of API 19² (Android 4.4) since 4.4.6 version³. There were quite a few changes in the client since then⁴, some possibly crucial. Have you tried using Shadowsocks on Android > 5.0?

 I know that I need a new phone, but so far I do not have the opportunity to buy.

I tried to use the versions that you sent me, but they do not fit on my phone.
When you try to install an error appearing called a ```syntax installation error```

I understand that I have an old phone, mammoth dinosaur

**Comment by strixaluco** [comment]
I'm afraid this current issue is not related to Streisand per se.

> I know that I need a new phone, but so far I do not have the opportunity to buy.

Having old firmware doesn't always mean you should buy a new device. You can install third-party firmware, such as LineageOS, if your device is supported¹.

¹ — https://wiki.lineageos.org/devices/

**Comment by rdbox** [comment]
> если ваше устройство поддерживается

unfortunately there is no my model,
**my model GT-I9082**
maybe another firmware will work

**Comment by strixaluco** [comment]
> We're getting further into off-topic here.
> There are plenty of firmware options for GT-I9082 on XDA: https://forum.xda-developers.com/galaxy-grand-duos/development

**Comment by rdbox** [comment]
found a problem, it turns out ip Digitalocean was blocked in the country where I went to sites

**Comment by boreddeveloper** [comment]
> I'll disappoint you. WireGuard does not work for android.

oh! okay. That's a shame.

> found a problem, it turns out ip Digitalocean was blocked in the country where I went to sites

you mean the DO IP is blocked in China?

**Comment by rdbox** [comment]
>вы имеете в виду, что DO IP заблокирован в Китае?

there is no part of the ip hoster DO blocked in Russia.
I needed Russian sites, and I did not know long ago that my ip server was in the black list. I had to change ip and the problem was solved
and so I've been looking for a reason for a week maybe

**Comment by strixaluco** [comment]
@rdbox great you've figured out the issue.

> It works on Windows PC, Apple mobiles as long you have the app installed before you land in China.

@mveplus, speaking of Potatso Lite for iOS, you can install it even in China unless your account is tied to Chinese app store.
