### ISSUE TITLE
Issue in installing in Vultr cloud

### ISSUE THREAD

**Issue by seokochin** [StreisandEffect/streisand#1389]
I used to install Streisand in Google, Digital Ocean etc. But when I try to install it in Vultr, I am getting error like this:

> TASK [gpg : Start the GPG agent] ***********************************************
fatal: [144.202.43.173]: FAILED! => {"changed": true, "cmd": ["gpg-agent", "--homedir", "/root/.gnupg", "--use-standard-socket", "--daemon"], "delta": "0:00:00.006761", "end": "2018-06-25 03:51:29.927919", "msg": "non-zero return code", "rc": 2, "start": "2018-06-25 03:51:29.921158", "stderr": "gpg-agent[25286]: a gpg-agent is already running - not starting a new one", "stderr_lines": ["gpg-agent[25286]: a gpg-agent is already running - not starting a new one"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/mohammedsalih/Downloads/streisand-vpns/streisand/playbooks/existing-server.retry

I am using Ubuntu 14.04 i386 

Can someone help ?

**Comment by atulsian89** [comment]
I had the same issue. Delete the /root/.gnupg and streisand folders in /root and then run gpgconf --kill gpg-agent and then re run the script.

**Comment by seokochin** [comment]
No luck.
I tried and still same error.

**Comment by nopdotcom** [comment]
Could you try #1387? (@hamidzr did this first in #1335.)

**Comment by seokochin** [comment]
no luck @nopdotcom 
I tried to add that patch. But got the error like this now

fatal: [144.202.43.173]: FAILED! => {"changed": true, "cmd": ["gpgconf", "--launch", "gpg-agent"], "delta": "0:00:00.007225", "end": "2018-06-25 07:38:23.135788", "msg": "non-zero return code", "rc": 2, "start": "2018-06-25 07:38:23.128563", "stderr": "gpgconf: invalid option \"--launch\"", "stderr_lines": ["gpgconf: invalid option \"--launch\""], "stdout": "", "stdout_lines": []}

**Comment by nopdotcom** [comment]
Which one did you try? Also, do you have a `streisand-diagnostics.md` file in the streisand directory?

**Comment by nopdotcom** [comment]
Look harder for `streisand-diagnostics.md`. It should be in the regular top-level `streisand` directory, the same place you're running `./streisand` from. It's generated before any gpg stuff happens.

**Comment by nopdotcom** [comment]
Actually, you said you were using 14.04. Could you try 16.04?

**Comment by cpu** [comment]
This issue has gone stale and 14.04 is unsupported. I'm going to close this for now. Thanks all!
