### ISSUE TITLE
"Unsupported parameters for (ec2) module

### ISSUE THREAD

**Issue by mdevasar** [StreisandEffect/streisand#1390]
HI, i try to spin one EC@ via ansible. But get below error. Can you help.

The ansible-play book i wrote is:

---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create security group
    ec2_group:
      name: web
      description: for web servers
      aws_secret_key: hqM1OHkIeA3LWJUor.xxxxxxxx
      aws_access_key: AKIAIT.xxxxxxxxxxxxx
      vpc_id:
      region: us-east-2
      rules:
       - proto: tcp
         ports:
           - 80
           - 22
           - 443
         cidr_ip: 0.0.0.0/0
       - tags: web-server

PLAY [localhost] ****************************************************************************************************************************************

TASK [provision ec2] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ec2) module: monitor, register, wait_out Supported parameters include: assign_public_ip, aws_access_key, aws_secret_key, count, count_tag, ebs_optimized, ec2_url, exact_count, group, group_id, id, image, instance_ids, instance_initiated_shutdown_behavior, instance_profile_name, instance_tags, instance_type, kernel, key_name, monitoring, network_interfaces, placement_group, private_ip, profile, ramdisk, region, security_token, source_dest_check, spot_launch_group, spot_price, spot_type, spot_wait_timeout, state, tenancy, termination_protection, user_data, validate_certs, volumes, vpc_subnet_id, wait, wait_timeout, zone"}
        to retry, use: --limit @/aws/ec2_v1.retry

**Comment by mdevasar** [comment]
sorry i pasted wrong play book. Correct one is 
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: provision ec2
    ec2:
      key_name: newkeypair
      region: us-east-2
      aws_secret_key: hqM1OHxxxxxxxxxxxxxxxx
      aws_access_key: AKIAIxxxxxxxxxxxxx
      instance_type: t2.micro
      image: ami-2a0f324f
      wait: true
      wait_out: 300
      exact_count: 1
      vpc_subnet_id: subnet-a90c48c1
      group: web
      assign_public_ip: yes
      monitor: no
      register: ec2

**Comment by nopdotcom** [comment]
Streisand should do all of that for you automatically. Is it not doing it?

BTW, I think you have an indentation problem. `register` should be at the same level as `ec2`.

`monitor` should be `monitoring`. See https://docs.ansible.com/ansible/latest/modules/ec2_module.html#ec2-module

**Comment by alimakki** [comment]
@mdevasar there shouldn't be a need to edit these files manually, the installer will prompt you for those.

**Comment by mdevasar** [comment]
Thanks! you guys helped me exact issue. I replaced wait_out with wait_timeout and monitor with monitoring. which fixed my issue.

**Comment by vinay-cell** [comment]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ec2) module: vpc_id Supported parameters include: assign_public_ip, aws_access_key, aws_secret_key, count, count_tag, debug_botocore_endpoint_logs, ebs_optimized, ec2_url, exact_count, group, group_id, id, image, instance_ids, instance_initiated_shutdown_behavior, instance_profile_name, instance_tags, instance_type, kernel, key_name, monitoring, network_interfaces, placement_group, private_ip, profile, ramdisk, region, security_token, source_dest_check, spot_launch_group, spot_price, spot_type, spot_wait_timeout, state, tenancy, termination_protection, user_data, validate_certs, volumes, vpc_subnet_id, wait, wait_timeout, zone"}

**Comment by vinay-cell** [comment]
to solve the above error
