### ISSUE TITLE
Is it possible setting up Streisand with Azure 'Free Trial' subscription?

### ISSUE THREAD

**Issue by sundmoon** [StreisandEffect/streisand#1393]
It seems like I cannot manage Subscriptions and Access Control (IAM)
https://github.com/StreisandEffect/streisand/blob/master/documentation/AZURE.md

**Comment by alimakki** [comment]
This is possible as I have done it before.

**Comment by sundmoon** [comment]
Azure is known as a constantly changing platform
The exact steps from the doc aren't getting along with what I see on the Azure portal as a Free Trial holder

Seeking help from people with fresh experience.

**Comment by nopdotcom** [comment]
Should this be re-titled, "Streisand Azure documentation does not match current Azure"?

**Comment by sundmoon** [comment]
@nopdotcom   Does anybody knows a way to set up Streisand on current Azure? 
I can test it while I still have the trial, no plans to updrade.

I set up 'Azure automation account' recently - maybe this will help

**Comment by nopdotcom** [comment]
It used to work. 

It's a problem for me to check this; I've already used up my free account time. Could you try it for us?

**Comment by sundmoon** [comment]
I still have the free trial, and I have no 'Subscriptions' menu item under 'Help + Support' 

https://docs.microsoft.com/en-in/azure/azure-resource-manager/resource-group-create-service-principal-portal#assign-application-to-role

So I have no clue how to get to something like 'Free Trial - Access Control (IAM)'

**Comment by cpu** [comment]
I think we should remove Azure support. It isn't used frequently enough to avoid bitrot and I don't believe we have maintainers able to provide support on a case-by-case basis.

I'm going to close this issue for now since I think its likely a dead end. I'm sorry @sundmoon. My recommendation is to evaluate another provider choice (AWS, DigitalOcean, Google Cloud, etc).
