### ISSUE TITLE
frequent reconnection openvpn for android

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1394]
there is a problem, on the mobile phone the application open for android works very oddly.
Every 60-80 seconds there is reconnection on the Internet does not work at all to surf and read websites.

the config file openvpn, is used with the same settings both on the laptop and on the phone. Only different certificates are present.
how do I find the problem? What you need to do to find a broken place

**Comment by Sinek8** [comment]
I was not able to use same openvpn user from more than one device at the same time. It would constantly reconnect as you described. Did you try different users?

**Comment by alimakki** [comment]
Streisand's OpenVPN configuration is set to only allow 1 client profile connect at any given time. This means that if 2 devices share the same profile, only 1 will be able create a connection.

**Comment by rdbox** [comment]
I use different profiles.
On the PC I have sheriff-unknown
while on the phone the citizen-crowd

I ran the test and completely disconnected the PC problem.
  The phone also has an openvpn reconnect

I NEED A HELP!
I really like your program build

**Comment by alimakki** [comment]
Have you tried OpenVPN over stunnel? Do the other vpn options have a similar behavior (OpenConnect or Wireguard)?

I'm curious to know if your ISP could be interfering with the tunnel.

**Comment by rdbox** [comment]
openvpn + stunnel greatly worsens the work of the Internet. It becomes slow
Wireguard can not use my client OS windows 7
The provider at me China Telecom he already infuriates me very much

**Comment by alimakki** [comment]
@rdbox I think it would be best for you to experiment with different VPN options provided by Streisand, as well as different hosting providers as results can vary by region and protocol. The issue you are facing is mst likely related to the ISP interfering/degrading networks to block such activity and there is little we can do from our end.

Thanks
