### ISSUE TITLE
how to get rid of vpn server menu extra

### ISSUE THREAD

**Issue by covici** [StreisandEffect/streisand#1399]
I have on my MAC, a menu extra  item called vpn-server which connects to an old vm using Ubuntu 14.4.  I removed tunnelblick using the uninstaller they have, but this item is still there -- I do not know what program its using, do you have any ideas as to how to get rid of it, so I can start with  a clean slate, install tunnelblick again and use the new server using 16.04?

Thanks.

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by alimakki** [comment]
You should be able to remove profiles from tunnelblick using its UI. You can also reference the [tunnelblick documentation](https://tunnelblick.net/cFileLocations.html) for additional info.
Closing issue as this is not a Streisand related issue.

Thanks!

**Comment by covici** [comment]
OK, thanks, I think that edid it.

On Sun, 08 Jul 2018 14:26:25 -0400,
Jay Carlson wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> Does the icon look like this?
> voila_capture 2017-07-26_01-14-29_pm
> 
> If it does, it's in System Preferences's "Network" panel.
> 
> voila_capture 2017-07-26_03-25-35_pm copy
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com
