### ISSUE TITLE
config file problem with versions of openvpn?

### ISSUE THREAD

**Issue by covici** [StreisandEffect/streisand#1401]
### Expected behavior:

connect should go without issues
### Actual Behavior:
I get message from tunnelblick saying my config needs editing and no connection.

### Steps to Reproduce:
1. download and install tunnelblick on MAC OS 13.5.
2.  Allow Tunnelblick to update to 3.76a.
3. download divide volume config from the server -- config is dated 5/18/18.
4.  open the config and tunnelblick will install.
I get behavior stated above.

For me, the workaround was to try to set the openvpn version to any of the 2.5 versions, tunnelblick's response is to say it could not use that version and it will use 2.4.6.  Once this is done the message goes away and connection is successful.

[ contents of `streisand-diagnostics.md` here ]

**Comment by alimakki** [comment]
@covici due to the use of `tls-crypt` for our OpenVPN configuration a 2.4x client is required - setting it to that version in tunnelblick is the correct thing to do. Their website does state that it should detect the version automatically however I suspect is buggy.

**Comment by covici** [comment]
OK, thats fine with me, just not obvious when I ran for the first
time.

On Tue, 17 Jul 2018 15:12:16 -0400,
Ali Makki wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> @covici due to the use of tls-crypt for our OpenVPN configuration a 2.4x client is required - setting it to that version in tunnelblick is the correct thing to do. Their website does state that it should detect the version automatically
> however I suspect is buggy.
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

**Comment by cpu** [comment]
It sounds like the problem has been identified. If someone has a suggestion for how to handle this better in the OpenVPN/Tunnelblick setup instructions I'd be open to reviewing a docs PR with a fix :-) Thanks everyone!
