### ISSUE TITLE
domain name instead of ip address

### ISSUE THREAD

**Issue by xXPeymanXx** [StreisandEffect/streisand#1410]
hi, 
first thx for this nice job, its works nice as expected.
i want to to know how can i use my server domain name instead of ip address in all anti-censorship's  services config files ? its so necessary because my country ban my server ip eventually, so i must change server ip address.

**Comment by nopdotcom** [comment]
There's no good way to change the IP address of a Streisand server after it's been installed; I'm sorry.

Which protocols and cloud providers are you using? Depending on the protocol, it can be pretty easy to add a secondary IP address to the server for ingress.

**Comment by xXPeymanXx** [comment]
@nopdotcom right now i use OpenVPN and shadowsocks in DigitalOcean, both of them works with my domainname instead of its ip (changed it from ovpn file and shadowsocks client).
as i see you bind protocols to server valid ip instead of this i think u can bind protocols to localhost(127.0.0.1) so if server get a new ip no problem will not occurring.

and another thing, shadowsocks client for android that server fetch is too old latest version right now is 4.5.7
[https://github.com/shadowsocks/shadowsocks-android/releases](url)

**Comment by nopdotcom** [comment]
@xXPeymanXx: I think you want to bind to 0.0.0.0 (for all interfaces). That should work for `/etc/shadowsocks-libev/config.json`. OpenVPN should already work. Edit `/etc/sslh.cfg` while you're at it.

Thanks for the heads-up on shadowsocks.

**Comment by xXPeymanXx** [comment]
@nopdotcom thx for the tips. so i tried it and it works with some other changes, i test it with creating a snapshot from my droplet and recreate it to change its ip and after reboot everything is ok .
write them down if somebody have this problem (Protocol tested : `OpenConnect`, `OpenVPN (direct)`, `OpenVPN (stunnel)`, `Shadowsocks`, `tor`)

1- change `server` in `/etc/shadowsocks-libev/config.json` to 0.0.0.0
2- change listen host in `/etc/sslh.cfg` to 0.0.0.0 instead of public ip and change tls protocol port from 443 to another open port (i set it 444) because after restarting nginx said `bind() to 127.0.0.1:443 failed (98: Address already in use)`
3- change port of nginx listener in `/etc/nginx/sites-available/streisand` to that port we set in `/etc/sslh.cfg` so my config is `listen 127.0.0.1:444 default_server ssl http2;`
4- change config files manually that connect to my domain name instead of public ip

just have one problem after these changes my openvpn sslh still connects but have dns problem and cant resolve any names, what is the problem here ?

**Comment by nopdotcom** [comment]
I'd suggest keeping sslh on 443, and bind nginx to 444.

Is dnsmasq running? `/etc/dnsmasq.d/openvpn.conf` is where we listen on the interfaces listed in `/etc/openvpn/server.conf`. Do you think `push "dhcp-option DNS 10.8.0.1"` is actually getting pushed to your clients?

If you'd like to check DNS reachability on Android: I'm not sure it's the *easiest* way, but I do know [Termux](https://play.google.com/store/apps/details?id=com.termux) has a `host` command.

```
$ apt install dnsutils
$ host google.com 10.8.0.1
$ host google.com 8.8.8.8
$ host google.com 1.1.1.1
```

**Comment by cpu** [comment]
I think this is probably a thread better suited for the [discussion repo](https://github.com/StreisandEffect/discussions) since it doesn't track a change we can make in the Streisand repository. I'm going to close this issue and suggest if its an on-going discussion that someone create a new discussion issue to continue the topic. Thanks!
