### ISSUE TITLE
linode vps ubuntu16.04 install failed

### ISSUE THREAD

**Issue by liefeng44** [StreisandEffect/streisand#1415]
Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the Linode Server] ************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************
ok: [localhost]

TASK [genesis-linode : set_fact] **************************************************************************************************
ok: [localhost]

TASK [genesis-linode : Get the ~/.ssh/id_rsa.pub contents] ************************************************************************
ok: [localhost]

TASK [genesis-linode : Create the server] *****************************************************************************************
**fatal: [localhost]: FAILED! => {"changed": false, "msg": "You do not have permission to add Linodes to this account."}
	to retry, use: --limit @/root/streisand/playbooks/linode.retry**

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   

is root login

why  do not have permission to add Linodes to this account.?
-------------------------------------------------------------------------------------------------
and when i do 
"

Run the installer for Ansible and its dependencies.

 ./util/venv-dependencies.sh ./venv

"
**python-novaclient 2.27.0 has requirement pbr<2.0,>=1.6, but you'll have pbr 4.2.0 which is incompatible.**

but it succesful
"All dependencies installed into ./venv. To use this environment, run this
in your shell:
"
--------------------------------------------------------------------------------------

**Comment by nopdotcom** [comment]
I looked at the Python package incompatibility. It is expected. The script should print "please ignore the following message:".

I am not sure why you are not getting Linodes created. Is there a limit? Looking for help from Linode users.

**Comment by paulp** [comment]
Linode user here. Worked for me. It was only my second linode though. Probably you're correct that he's up against some limit.

**Comment by liefeng44** [comment]
> I looked at the Python package incompatibility. It is expected. The script should print "please ignore the following message:".
> 
> I am not sure why you are not getting Linodes created. Is there a limit? Looking for help from Linode users.
i used the  account that is a sub-account , i don't know if this is the reason

**Comment by cpu** [comment]
This sounds like an issue with the Linode account itself. I recommend that you:
1) verify you're using an API key generated for the version 2 API (See https://github.com/StreisandEffect/streisand/issues/1467)
2) open a support ticket with Linode to see if they can provide any help/guidance.

Thanks!
