### ISSUE TITLE
Trouble opening Shadowsocks

### ISSUE THREAD

**Issue by plsbemyfriend24** [StreisandEffect/streisand#1416]
Hello, for some reason when I try to open shadowsocks, it gives me an error followed by the words Unhandled exception has occurred in you application: If you click continue, the application will ignore this error and attempt to close. If you click quit, the application will close immediately. Exception has been thrown by the target of an.

I use a PC, by the way

**Comment by plsbemyfriend24** [comment]
I also get a error when I try to open the application in my folder: Fatal error: Can't check configuration file 'C/Users/Joshua/Downloads/SSR-PC(2)/|(shadowsocks application)-/temp/privoxy.conf':(error number 0)

**Comment by alimakki** [comment]
@plsbemyfriend24 seems like it could be a bug in the Windows client.
Could you try downloading the [following release v4.0.10](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.0.10) and see if that resolves your issue?

**Comment by cpu** [comment]
This issue has gone stale without any reply from the original poster. I'm going to close it for now. Thanks all!
