### ISSUE TITLE
how to add new functions to the logs

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1421]
I have a few questions
1. Is streisand automatically updated or does it have to be done manually?

2. where I can see a description of what you did, can be added a new function or something changed.
Often developers point this out as a version
example
v1.0.2
v1.0.1
v1.0

**Comment by nopdotcom** [comment]
1. We use Ubuntu's `unattended-upgrades` package, so if upstream releases security fixes, all Streisand installations get them. However, there is no automatic upgrade of Streisand itself; if we change how shadowsocks is configured, it only affects new installations.

2. We need to do this. Thank you for the reminder.

**Comment by cpu** [comment]
It doesn't seem like there are remaining questions to address in this thread so I'm going to close the issue. In the future please ask questions on the [Streisand discussions repo](https://github.com/StreisandEffect/discussions).
