### ISSUE TITLE
linode localhost  Ubuntu 16.04 LTS Profile  install fail

### ISSUE THREAD

**Issue by mytts** [StreisandEffect/streisand#1431]
vps provider :linode  My Ubuntu 16.04 LTS Profile (Latest 64 bit (4.17.17-x86_64-linode116))
mode : 7. localhost (Advanced)
chose no
Streisand will use the settings configured in /root/.streisand/site.yml

got error of this  

TASK [stunnel : Generate local stunnel configuration file (for connecting clients)] ***************************************************
ok: [localhost]

TASK [stunnel : Stop (init.d's) stunnel4] *********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service stunnel4.service: host"}
	to retry, use: --limit @/root/streisand/playbooks/localhost.retry

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=183  changed=55   unreachable=0    failed=1

**Comment by mytts** [comment]
cat streisand-diagnostics.md


### Ansible Information

* Ansible version: 2.6.3
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 1d8ee35e16f350737a783c967c669ba462d6334f
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by nopdotcom** [comment]
Hmm. Instead of `7. localhost`, could you try installing using the `5. Linode` option from a different system? It would be interesting to know if one succeeds but the other doesn't.

**Comment by mytts** [comment]
i tried 5. Linode option,it succeed

**Comment by nopdotcom** [comment]
Cool, thanks for the feedback. localhost and Existing should work, but if there's an explicit option for a provider, we strongly prefer you use it. I'm going to close this; reopen if you run into this again.
