### ISSUE TITLE
[Suggestion] Change Default DNS Server to CloudFlare DNS

### ISSUE THREAD

**Issue by brackenhill-mob** [StreisandEffect/streisand#1433]
CloudFlare DNS is a lot quicker at resolution than any other DNS server I've tested.

Also their privacy statement says that they won't store user IP addresses.

See https://1.1.1.1/

HTH

**Comment by fishzle** [comment]
The best way to improve DNS data leakage, and possible simultaenously improve performance is to integrate with pi-hole. See https://github.com/StreisandEffect/discussions/issues/41

**Comment by cpu** [comment]
I think this is squarely a topic for the [discussion repo](https://github.com/StreisandEffect/discussions). I'm going to close the issue here and encourage folks to move to a discussions thread.
