### ISSUE TITLE
Issue connecting to Wireguard Linux ubuntu 18.04

### ISSUE THREAD

**Issue by ilyas95** [StreisandEffect/streisand#1434]
When I try to connect to the server by using sudo wg-quick up configfile I get the following as output:
[#] ip link add configfile type wireguard
[#] wg setconf configfile /dev/fd/63
[#] ip address add 10.192.122.2/32 dev configfile
[#] ip link set mtu 1420 dev configfile
[#] ip link set configfile up
[#] resolvconf -a configfile -m 0 -x
/usr/bin/wg-quick: line 31: resolvconf: command not found
[#] ip link delete dev configfile

I tried to look inside the file /usr/bin/wg-quick but I cannot find the problem
Someone had this problem?
I'm sure the problem is not the server because I'm able to connect with my android phone

**Comment by nopdotcom** [comment]
Which version of which Linux?

**Comment by ilyas95** [comment]
Ubuntu 18.04 LTS (Bionic Beaver)

**Comment by ilyas95** [comment]
@Frichetten 
It worked, thank you
I installed openresolv as you suggested

**Comment by Frichetten** [comment]
I wouldn't recommend it. (I had problems while testing with 'resolvconf'). Do me a favor, could you run `cat /etc/resolve.conf` and see what the outout is? (Don't post it online because it should contain your servers IP address).

If it contains anything other than the IP of your server, we need to fix that. If it does have the right IP the next step would be to run the same command on the server and see what that output is. 

As a side note, what VPS provider are you using?

**Comment by z0rc** [comment]
127.0.0.53 is local systemd-resolved daemon, that installed by default in Ubuntu. I'm not sure that `resolvconf` supports it or ever will. And in general I believe it's `wg-quick` missing support systemd-resolved and shoudn't entirely rely on `resolvconf`.

**Comment by z0rc** [comment]
As alternative, you don't need a wg-quick and can enable Wireguard in systemd directly. See https://wiki.debian.org/Wireguard#Step_2_-_Alternative_C_-_systemd, please be aware, that this isn't a full guide and it might not work in your case.

**Comment by Frichetten** [comment]
@ilyas95, after you run the wg-quick command (with your configuration) what does /etc/resolv.conf look like? When I have Wireguard turned off my /etc/resolv.conf looks exactly like you mentioned. But when I turn Wireguard on it shows the internal 10.x.x.x IP address of the server. 

If you are leaking DNS, we'd need to ensure your system is properly routing DNS queries to the server.

**Comment by Ronaldkornblow** [comment]
@Frichetten What is the resolution here?

**Comment by Frichetten** [comment]
@Ronaldkornblow, I'm not sure I understand what you mean?

**Comment by Ronaldkornblow** [comment]
@Frichetten I still cannot connect. Is there any resolution here?

**Comment by Frichetten** [comment]
Oh sorry, I understand now :) Are you getting the same error as described in the OP? If so, have you attempted to install 'openresolv'?

**Comment by Ronaldkornblow** [comment]
@Frichetten 
I was able to get rid of the error above from the install.
I installed openresolv which has stopped my dns from working even with wg not up.

**Comment by Frichetten** [comment]
@Ronaldkornblow, I would recommend checking what is in your /etc/resolv.conf. If Wireguard is down, you should be using whatever your default DNS server is. However, when Wireguard is up, it should instead use DNS through Wireguard.

**Comment by cpu** [comment]
>  @nopdotcom, considering that Ubuntu holds a large share of the Linux desktop market, do you think it would be a good idea to include instructions related to installing resolvconf?

@Frichetten Do you mean `openresolv` here instead of `resolvconf`? If so, yes I think a docs PR with this update (or a working WireGuard/systemd-resolver config) would be awesome.

**Comment by alimakki** [comment]
Closing as the issue has been been documented by @Frichetten

**Comment by abduljabbarbcs** [comment]
@alimakki @Frichetten I am facing following issue on Ubuntu 18.04.4
[#] ip link add vague-print type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev vague-print
Cannot find device "vague-print"

Can you please help me to resolve it. Thank you

**Comment by sarnold** [comment]
@abduljabbarbcs i would recommend starting a new issue as your problem (at least on the surface) seems unrelated to dns tool conflicts.
