### ISSUE TITLE
How to disable specific profile(certificate) for stopping them to use ssh openvpn?

### ISSUE THREAD

**Issue by dilandyechiel** [StreisandEffect/streisand#1436]
Hi,

I would like to if there is a possibility to disable a profile or a certificate to restrict them from using VPN? currently basically for Openvpn profiles and Openconnect profiles?

Thanks.

(Posted on Discussion but seems inactive sub)

**Comment by dilandyechiel** [comment]
**Any love here too please?**

**Comment by alimakki** [comment]
Hello @dilandyechiel,

The current method in which Streisand is set up does not build CRLs for SSL based VPNs (such as OpenVPN) which is required to revoke already-issued certificates.

As is, it right now, it would have to be done manually via CLI, unfortunately.

I've opened a new issue #1447 to track this request.
