### ISSUE TITLE
Error while Installing streisand (Tor Unauthenticated Package)

### ISSUE THREAD

**Issue by supervirus5** [StreisandEffect/streisand#1438]
### Actual Behavior: 
`TASK [tor-bridge : Install the package to keep the Tor signing key current] ***********************************************************************
fatal: [VPS_IP]: FAILED! => {"cache_update_time": 1535933139, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\"project.org-keyring'' failed: E: There were unauthenticated packages and -y was used without --allow-unauthenticated\n", "rc": 100, "stderr": "E: There were unauthenticated packderr_lines": ["E: There were unauthenticated packages and -y was used without --allow-unauthenticated"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReadinnstalled:\n  deb.torproject.org-keyring\n0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 4922 B of archives.\nAfter this operation, 22.5 kB of addities cannot be authenticated!\n  deb.torproject.org-keyring\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The foorg-keyring", "0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.", "Need to get 4922 B of archives.", "After this operation, 22.5 kB of additional disk space will bicated!", "  deb.torproject.org-keyring"]}
`
And this error as well : 
`TASK [shadowsocks : Check that the Shadowsocks service started (VPS_IP)] ********************************************************************
fatal: [VPS_IP]: FAILED! => {"changed": false, "elapsed": 30, "msg": "Timeout when waiting for VPS_IP:8530"}
`
### Steps to Reproduce:
1. Create an Amazon AWS Account
2. Clone and Run Streisand
3. Enter your aws keys details When prompted
4. Wait for the error to show up 
<!--
`### Ansible Information

* Ansible version: 2.5.4
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 5a6139f819c1a20c1c72cf549e331173a707eb19
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-amazon
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 20
`

**Tried to reinstall streisand after disabling (Shadowsocks + Tor) and got the same error**

**Comment by nopdotcom** [comment]
Tor upstream is broken. I'll take a look at what can be done to work around it.

**Comment by dilandyechiel** [comment]
Confirming. Having same issue while installing on new digital ocean server.

**Comment by supervirus5** [comment]
@nopdotcom I also think that Shadowsocks don't install correctly because of this error as well : 
`TASK [shadowsocks : Check that the Shadowsocks service started (VPS_IP)] ******************************************************************** fatal: [VPS_IP]: FAILED! => {"changed": false, "elapsed": 30, "msg": "Timeout when waiting for VPS_IP:8530"}`

**Comment by ddvzlnz** [comment]
Confirming same exact error on Vultr and Digital Ocean.

**Comment by MaikGit** [comment]
I got the same issue on Digital Ocean, maybe we just need to wait until the TOR upstream come back online

**Comment by Spengreb** [comment]
I got the issue also today when deploying with AWS. Are there any alternatives for the Tor upstream?
