### ISSUE TITLE
Not possible to connect to wireguard on Digital ocean instance

### ISSUE THREAD

**Issue by leachim** [StreisandEffect/streisand#1443]
### Steps to Reproduce:
Setting up an instance of streisand on a running digital ocean instance using the noninteractive deployment option. I think this must be a problem with the target host, as I can neither use an Android phone nor the Linux machine wireguard client to connect to the internet, even though the connection itself works. Ansible reports no errors, except for a failure to register my domain with let's encrypt. I could overcome this issue however, by logging in and using `acmetool reconcile` command. 

I think it must be an issue with dns resolution, as I managed to connect in both instances, but I cannot load webpages. I think, on my linux machine the dns name of the server is not added to the /etc/resolv.conf file and ip route does not show any entry for the dns in the wireguard configuration file. But then I am somewhat suprised that the phone doesn't work, either. It used to work for an older version of streisand.

**Comment by Frichetten** [comment]
Hi @leachim, thank you for opening an issue. 
Is what you've experienced similar to the issue described in #1434? (If you run `resolvconf` on your client system what is the output?)

**Comment by leachim** [comment]
It might well be related, and I originally tried the solutions proposed in this issue. I think it might have to do with dns resolution. In an unconnected state, my resolv.conf file has the following content:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search Home
```
I am also running systemd-resolv service. 

I had resolvconf installed, I tried uninstalling and replacing it with openresolv (it seems that the commands in the wireguard client configuration have parameters that were created to be used with openresolv). But it didn't really help. 

I am wondering how is the resolv.conf file updated by wireguard. I would expect this file to change as a result of starting the wireguard connection, but this is not the case. However, I don't see any errors in the wireguard output: 
```
[#] ip link add wg0-client type wireguard
[#] wg setconf wg0-client /dev/fd/63
[#] ip address add 10.192.122.2/32 dev wg0-client
[#] ip link set mtu 1420 dev wg0-client
[#] ip link set wg0-client up
[#] resolvconf -a wg.wg0-client -m 0 -x
[#] wg set wg0-client fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0-client table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
```
Could this mean, that systemd-resolv is managing the dns and this is why wireguard doesn't work? Do you know how to integrate this with wireguard? I am relatively new to the systemd world.

**Comment by Frichetten** [comment]
I am also unfamiliar with Systemd :(

What does your /etc/resolv.conf look like in a connected state? When I am unconnected mine is `nameserver 127.0.0.53` which (I believe) is the systemd DNS daemon. However when I connect to wireguard (using wg-quick) my /etc/resolv.conf contains the 10.x.x.x IP address of my server.

**Comment by leachim** [comment]
Yes, it doesn't change. So this seems to be the problem. It's not clear to me, however, why it is not being updated.

**Comment by leachim** [comment]
What surprises me, though, is the fact that I see the same behavior when I connect to the wireguard instance through my android phone. It used to work with the last streisand instance that I had set up a couple of month ago. Now when I connect, I can't load any webpages.

**Comment by nopdotcom** [comment]
I just fired up a DO instance. I see "DNS = 10.192.122.1" in both the regular WireGuard file and in the QR code for Android. Android and macOS name resolution appears to work. I'll fire up a Linux VM in a bit to test resolution there. I'm going to try 16.04 first, then 18.04.

**Comment by leachim** [comment]
How did the Linux VM testing go? 
What I also noticed, I am having an issue when setting up my DO instance. I am using a .org subdomain as address for the let's encrypt certification and there I get an error when running the non-interactive setup. I can work around this by running acmetool reconcile on the server and then restart the setup process. But maybe this leads to the problem? I would be happy if at least the android instance would be running.

**Comment by leachim** [comment]
I figured out this is actually the same issue as these two: #1349 and #1329 
I don't know about separate systemd networkd issues, but I first would have to fix the above.

**Comment by cpu** [comment]
Thanks for following up @leachim.

Since it sounds like it was the same problem as #1349 and #1329 and the port conflict has been resolved in master I'm going to close this issue. If further WireGuard problems occur after provisioning new instances using the code in master we can definitely open a new issue!
