### ISSUE TITLE
Allow certificate revocations for TLS based VPNs

### ISSUE THREAD

**Issue by alimakki** [StreisandEffect/streisand#1447]
Streisand's current setup does not build CRLs (certificate revocation lists) for SSL/TLS based VPNs.
This affects:

- OpenVPN
- OpenConnect

**Comment by nopdotcom** [comment]
I would rather support proper authorization, if/when that's possible. (You may have *authenticated* with the cert, but the server may not *authorize* you.)

**Comment by cpu** [comment]
I don't think it makes sense to support user revocation only for this one service. In general I think Streisand is best to continue recommending that users recreate their entire Streisand instance when they change the set of trusted users. I don't think Streisand has the foundation in place to support anything else right now unfortunately.
