### ISSUE TITLE
How to update streisand on my Linode VPS?

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1448]
I'm not sure if this is the right place to post, but it's been a while since I've installed streisand on my Linode VPS. Is there any standard procedure of how to update all servers to fix security vulnerabilities? I haven't been able to find any information regarding this here on GitHub. What do you recommend or is there any possibility to automatically receive the latest updates without having to do anything?

**Comment by alimakki** [comment]
@baimafeima,

Streisand will auto-update on its own and reboot if necessary as well; it's all configured as part of the unattanded-upgrades.
