### ISSUE TITLE
No internet connection on iPhone after successful connection to VPN server

### ISSUE THREAD

**Issue by huy-nguyen** [StreisandEffect/streisand#1450]
### Expected behavior:

Should be able to connect to internet.

### Actual Behavior:

Internet connection times out.

### Steps to Reproduce:
1. Runs streisand per instructions and diagnostics file below.
2. Follow the instructions to install the certificate and OpenVPN profile (direct) to iPhone.
3. Able to connect to VPN but no internet connection (google.com). However, I was able to connect to streisand gateway to see the instructions. I tried rebooting the phone but no success. 

I previously used Streisand to set up an identical VPN server back in May (commit 42c7ba7) and that profile still works fine on my phone today. As a sanity check, I checked out the repo at that commit and create another VPN server and that also worked fine on my phone. Not sure what has changed since then. 

### Ansible Information

* Ansible version: 2.5.4
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.12.6
* Python interpreter: python
* Python version: 2.7.15

### Streisand Information

* Streisand Git revision: 72b5cf22e2cbfe98c777cb39a44927f079baa2cf
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by alimakki** [comment]
Hi @huy-nguyen,

Does the lack of connectivity happen on cellular/wifi or both?

Also could you let me know what version of iOS are you using?

**Comment by alimakki** [comment]
One more question: are there any explicit DNS servers set on your iPhone?

**Comment by huy-nguyen** [comment]
@alimakki The connection problem happened on both wifi and cellular. iOS version is 11.4.1. I have DNS set to "automatic".

**Comment by alimakki** [comment]
@huy-nguyen thanks for following up,

I spun up an instance using the same commit, and was able to reproduce the issue. Fortunately, the solution is easy:

In the OpenVPN Connect app, could you visit settings, and set "Compression" to "No", and give it another shot?

![image-1](https://user-images.githubusercontent.com/920624/45658516-51471b80-babd-11e8-9531-6dd3038b2ed8.jpg)

**Comment by aeroweb340** [comment]
Good afternoon,

With the latest openvpn version on iOS 12. The compression is now set to NO by default as it seems to be insecure.

I get not internet connectivity with the compression set to NO by default. If I set to FULL it works again.

Looking at the server.conf compression lzo4 is used. Should I remove to compression?

**Comment by alimakki** [comment]
Closing issue as there has been no response.
