### ISSUE TITLE
Connecting Whatsapp Voice/Video Calls

### ISSUE THREAD

**Issue by kontinyu** [StreisandEffect/streisand#1451]
Hey there, this is probably wrong place for this issue. If so, please point me the right direction. I can't get whatsapp voice/video calls to work. I can see/hear the other side. But my audio/video is not received by the other side. 

Also thank you all for your great work in advance. I'm so sorry and angry that things have come to this stage with internet & governments.
### Expected behavior:
Working 2-way a/v call in whatsapp.
### Actual Behavior:
I can get a/v but cannot send it.
### Steps to Reproduce:
1. Install streisand.
2. Activate VPN in Android
3. Initiate a call.

NOTES:
1. I live in a country where whatsapp a/v calls are banned.
2. Used multiple devices on both side. Issue persist.
3. Used ALL vpn methods (openvpn, shadowsocks with obf. wireguard, anyconnect etc.
4. In a free country (where vpns or whatsapp is not banned) every connection method works properly.

So what is the problem? Can they sniff some data and determine that i'm using a vpn? If so how? 
Any pointer is welcome.

[ contents of `streisand-diagnostics.md` here ]

**Comment by alimakki** [comment]
Moving to https://github.com/StreisandEffect/discussions/issues/148
