### ISSUE TITLE
Error: Could not find the requested service stunnel4.service

### ISSUE THREAD

**Issue by dilandyechiel** [StreisandEffect/streisand#1454]
### Expected behavior:
Working service

### Actual Behavior:
Giving error
`
TASK [stunnel : Stop (init.d's) stunnel4] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service stunnel4.service: host"}
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry
`
### Steps to Reproduce:
1. 

[
### Ansible Information

* Ansible version: 2.5.4
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 3f93d457cb235cb2e4bde270e453a8bac2a9eb38
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 20
]

<!--

**Comment by nopdotcom** [comment]
(copy-paste from the other issue):

Was this a clean system before you started the localhost install? We try to support lightly modified machines, but it can be difficult to debug.

**Comment by dilandyechiel** [comment]
> (copy-paste from the other issue):
> 
> Was this a clean system before you started the localhost install? We try to support lightly modified machines, but it can be difficult to debug.

Yes it was clean system.
