### ISSUE TITLE
Error: Unable to load CA private key & wg-quick@wg0.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by dilandyechiel** [StreisandEffect/streisand#1456]
### Expected behavior:
Working Service

### Actual Behavior:
Receiving error as
`
TASK [streisand-gateway : Process certificate signing request with the Nginx CA to create leaf certificate] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["openssl", "ca", "-batch", "-create_serial", "-config"              , "/root/ca/openssl-local.cnf", "-extensions", "v3_req", "-days", "1825", "-in", "/etc/ssl/certs/strunningnew.c              sr", "-out", "/etc/ssl/certs/strunningnew.crt"], "delta": "0:00:00.007172", "end": "2018-10-03 13:42:33.428583"              , "msg": "non-zero return code", "rc": 1, "start": "2018-10-03 13:42:33.421411", "stderr": "Using configuration               from /root/ca/openssl-local.cnf\nError opening CA private key /root/ca/private/cakey.pem\n139998218712728:erro              r:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/root/ca/private/cakey.pem','r'              )\n139998218712728:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:\nunable to load CA private               key", "stderr_lines": ["Using configuration from /root/ca/openssl-local.cnf", "Error opening CA private key /ro              ot/ca/private/cakey.pem", "139998218712728:error:02001002:system library:fopen:No such file or directory:bss_fi              le.c:398:fopen('/root/ca/private/cakey.pem','r')", "139998218712728:error:20074002:BIO routines:FILE_CTRL:syste              m lib:bss_file.c:400:", "unable to load CA private key"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry
`

&-------------------------------------------------

`TASK [wireguard : Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interfa              ce] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0.service: Job for               wg-quick@wg0.service failed because the control process exited with error code. See \"systemctl status wg-quic              k@wg0.service\" and \"journalctl -xe\" for details.\n"}
...ignoring
`
### Steps to Reproduce:
1.  Follow general install instruction.

[ ### Ansible Information

* Ansible version: 2.5.4
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 3f93d457cb235cb2e4bde270e453a8bac2a9eb38
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: False
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: False
* SSH forward user enabled: True
* Configured number of VPN clients: 20
 ]

``

**Comment by nopdotcom** [comment]
Was this a clean system before you started the localhost install? We try to support lightly modified machines, but it can be difficult to debug.

**Comment by dilandyechiel** [comment]
Yes it was clean system.

**Comment by cpu** [comment]
Hi @dilandyechiel - Please try provisioning a system from scratch using one of the regular providers (DigitalOcean, AWS, Linode, etc). I suspect your problem is somehow related to the `localhost` provisioning. As noted in the initial setup process that is an advanced mode and we're not able to do as much to support it. If you find this problem affects the other providers we can reopen this bug. Thanks!
