### ISSUE TITLE
Streisand Localhost install fails on macOS 10.13.6

### ISSUE THREAD

**Issue by indre-waldemar** [StreisandEffect/streisand#1458]
Dear Team,

I try to install Streisand on a local Mac.

The macOS Version is 10.13.6
ansible --version ansible 2.5.4
python --version Python 2.7.15
pip --version pip 18.1
git --version git version 2.19.1

My step's as follow:
1. ssh-keygen
2. python2.7 -m ensurepip —user
3. ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/ install)" brew doctor
4. brew install git
5. git clone https://github.com/StreisandEffect/streisand.git && cd streisand
6. brew install python
7. brew install python@2
8. pip install --upgrade pip setuptools
9. sudo -H ./util/venv-dependencies.sh ./venv
Problem:
python-novaclient 2.27.0 has requirement pbr<2.0,>=1.6, but you'll have pbr 4.3.0 which is incompatible.
azure-cli-core 2.0.46 has requirement azure-mgmt-resource==2.0.0, but you'll have azure-mgmt-resource 1.2.2 which is incompatible.

10. source ./venv/bin/activate
11. ./streisand with default settings
Problem:
 [WARNING]: Found both group and host with same name: localhost

PLAY [Perform global variables validation] ****************************************************************************************************************************************************************************************

TASK [validation : Stat the Streisand SSH private key] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [validation : Fail if the Streisand SSH private key file doesn't exist] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Stat the Streisand SSH public key] *****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Fail if the Streisand SSH public key file doesn't exist] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that OpenVPN optional variables are rational] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that Tinyproxy optional variables are rational] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that sshutle optional variables are rational] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that the maximum number of clients is set to a reasonable amount] *************************************************************************************************************************************
skipping: [localhost]

TASK [validation : Validate that at least one VPN is specified] *******************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

 [WARNING]: Found both group and host with same name: localhost

PLAY [Prepare the new server for Ansible] *****************************************************************************************************************************************************************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "sudo: a password is required\n", "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/user/streisand/playbooks/localhost.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

Please, if something forgotten to help let me know.

Thank you very much.

All the best

Waldemar

**Comment by z0rc** [comment]
I don't think this installation method is supported with macOS. Moreover running streisand server on localhost doesn't make much sense and doesn't provide any security feature this project has in goals.

localhost method is available as advanced option to install on your own server when you logged onto it via SSH. Also you have to run Ubuntu 16.04 for this method to work.

**Comment by wmar** [comment]
I had tried to follow the MacOS steps, but fails to with User directory isn't owned and other problem.  Also, come up the another error after  ./util/venv-dependencies.sh ./ven

_python-novaclient 2.27.0 has requirement pbr<2.0,>=1.6, but you'll have pbr 5.1.1 which is incompatible._

**Comment by developeroka** [comment]
> I had tried to follow the MacOS steps, but fails to with User directory isn't owned and other problem. Also, come up the another error after ./util/venv-dependencies.sh ./ven
> 
> _python-novaclient 2.27.0 has requirement pbr<2.0,>=1.6, but you'll have pbr 5.1.1 which is incompatible._

I have the same problem, any solution did you found? 

I've install pbr (latest version) and other failed packages ,manually to its project interpreter but again in running `sudo ./streisand`  I got this error 

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 2, "stderr": "Unable to locate an executable at \"/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/apt\" (-1)\n", "stderr_lines": ["Unable to locate an executable at \"/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/apt\" (-1)"], "stdout": "", "stdout_lines": []}

which I think it needs a deb package and want to install it on macOS and because macOS doesn't have apt finally receive this error.
