### ISSUE TITLE
Provide a way to use OpenVPN with tls-auth as alternative to tls-crypt

### ISSUE THREAD

**Issue by trochdewei** [StreisandEffect/streisand#1468]
I found that my ISP throttle OpenVPN connection when used with tls-crypt, but not with tls-auth. Of course I can use openvpn inside stunnel, but at lower speed.

**Comment by cpu** [comment]
Hi @trochdewei,

I don't think this is a common enough occurrence to justify the added maintenance complexity. I also think it will be difficulty to conveye to the end user which choice is appropriate: this is a pretty case specific case that requires some knowledge of OpenVPN internals to understand. Additionally its a step in the wrong direction security-wise. `tls-auth` only authenticates the control channel, leaving it unencrypted.

If you want to customize this for your own installations I recommend you edit the `etc_openvpn_server_common.j2` template [found here]( https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/openvpn/templates/etc_openvpn_server_common.j2) before creating your Streisand instances. Conceptually you'll be looking to revert this change: https://github.com/StreisandEffect/streisand/commit/8ba56be8e912d59fe0b7a8cad73d1d72d65fd3df

Hope that helps! I'm going to close this issue for now. Without substantial demand from other users I don't think its the right path forward for the project. Thanks for understanding.
