### ISSUE TITLE
Git Clone libcork fails with GnuTLS error

### ISSUE THREAD

**Issue by unixfy** [StreisandEffect/streisand#1476]
I'm experiencing this issue on a fresh Ubuntu 16.04 install from `cloudimg` on a Proxmox hypervisor.

### Expected behavior:

The libcork repository will clone correctly and Streisand installation proceeds.

### Actual Behavior:

The clone hangs for a while and then gives the error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to init/update submodules: Submodule 'libcork' (https://github.com/shadowsocks/libcork.git) registered for path 'libcork'\nCloning into 'libcork'...\nerror: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.\nfatal: The remote end hung up unexpectedly\nfatal: clone of 'https://github.com/shadowsocks/libcork.git' into submodule path 'libcork' failed\n"}
```

### Steps to Reproduce:
1. Install a fresh Ubuntu 16.04

2. `apt update && apt upgrade -y`

3. Run streisand installer with Shadowsocks enabled

### Ansible Information

* Ansible version: 2.6.5
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: a90e8ce9594cb83a14f6bbc50890535faba895d8
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

Setting the http.postBuffer to a higher value did not work for me ([source](https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls))

**Comment by nopdotcom** [comment]
I can't reproduce this. Could you try again?

**Comment by unixfy** [comment]
> I can't reproduce this. Could you try again?

I tried it again and am still getting the same error. Maybe it's important to note that the network connection of the machine is through a wireguard tunnel with iptables 1:1 NAT?

**Comment by nopdotcom** [comment]
That's weird. I'm assuming a regular clone of
https://github.com/shadowsocks/libcork.git does work?

Could you try the top two stanzas of https://github.com/StreisandEffect/streisand/blob/3fb24ece7b79f6f8b4cc35f6d03c026580a391fc/playbooks/roles/shadowsocks/tasks/simple-obfs.yml manually?

**Comment by unixfy** [comment]
I've found this to be caused by a borked Wireguard tunnel configuration (in that the host node routes IPs through a tunnel)
