### ISSUE TITLE
python-software-properties has been deprecated in Ubuntu 18.04

### ISSUE THREAD

**Issue by KamilRT** [StreisandEffect/streisand#1479]
https://github.com/StreisandEffect/streisand/blob/a90e8ce9594cb83a14f6bbc50890535faba895d8/playbooks/roles/common/vars/main.yml#L27

This package has been deprecated and it is already replaced by software-properties-common.

It is causing fail during Streisand installation on Ubuntu 18.04. Should be either commented out or replaced by newer package name

**Comment by Scorpion2185** [comment]
Same problem on debian 9:
`fatal: [Existing.sever.ip]: FAILED! => {"changed": false, "msg": "No package matching 'python-software-properties' is available"}`
Is there a solution?

**Comment by nopdotcom** [comment]
These are "existing server" or "localhost"? Streisand currently only supports Ubuntu 16.04 as a target system. If you're interested in helping update target support to Ubuntu 18.04, check out #1453.

I doubt that Debian as a target will be supported; if you can pick Debian, usually you could also pick Ubuntu. PRs welcome, but please show your work early; I don't want you to get stuck later.

**Comment by Scorpion2185** [comment]
8th option existing server for me, anyway i forgot to change network (client and server were in the same).
Now I need to use a custom ssh port, later maybe i will have again this problem.
https://github.com/StreisandEffect/discussions/issues/159

**Comment by Scorpion2185** [comment]
Indeed I tried with local host and I have the same error.

**Comment by nopdotcom** [comment]
Could you upload a streisand-diagnostics.md file from one of the failures?

**Comment by Scorpion2185** [comment]
I did several attempts this one should be the one with localhost, so the problem is python-software-properties. 
(I still waiting for a custom shh port solution https://github.com/StreisandEffect/streisand/issues/1483).
Is it possible to use python3? So i can use the package python3-software-properties.
Or somehow install/use python-software-properties on python2?
```
<!--

Please share the contents of this file when you open a new Streisand issue
https://github.com/StreisandEffect/streisand-discussions/issues/ 

It will help the developers reproduce your problem and provide a fix.
-->

### Ansible Information

* Ansible version: 2.6.5
* Ansible system: Linux
* Host OS: Debian
* Host OS version:  9.6
* Python interpreter: /usr/bin/python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: a90e8ce9594cb83a14f6bbc50890535faba895d8
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5
```
