### ISSUE TITLE
SSH Error: data could not be sent to remote host, UNREACHABLE Linode

### ISSUE THREAD

**Issue by tiosecurity** [StreisandEffect/streisand#1481]
I've been trying to set up only WireGuard in **Linode** 20 profiles, clean / new installation of all from Mac 10.14.1, I guess I've tried already everything since yesterday. there's not way to get rid this error: 

> SSH Error: data could not be sent to remote host "Make sure this host can be reached over ssh", "unreachable": true

I've already tried almost everything I found searching / reading. nothing work. 
appreciate some help with this issue.

Update: Trying with **amazon**:
>fatal: [localhost]: FAILED! => {"changed": false, "msg": "Python modules \"botocore\" or \"boto3\" are missing, please install both"}

Update: With **Google**: (I'm generating and uploading my .json, still give me this error)
>fatal: [localhost]: FAILED! => {"changed": false, "msg": "GCP Credentials File /Users/me/Downloads/my.json  not found."}

Update: Testing **DigitalOcean** (I've generated my api, everything looks normal, everything is updated, the name and api number are correct...)
>fatal: [localhost]: FAILED! => {"changed": false, "msg": "* The API Access Token might be incorrect or missing the Write Scope. OR * The SSH key may already exist in the DigitalOcean Control Panel under a different name. OR * The dopy Python module might not be installed. Use `pip install dopy==0.3.5` to install this module. On the latest version of macOS, dopy > 0.3.5 is currently broken."}

Update: Well, I've been testing with the option 8 "**Existing server (Advanced)**" in other vps's (not supported) and VPS supported but using this option, all ready, but I'm still getting this error:
>fatal: [IP]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"IP\". Make sure this host can be reached over ssh", "unreachable": true}

it seems nothing work to me.

Update: Well, it was quite challenging but I finally found the way to make it work with **amazon aws**
 
![screen shot 2018-11-13 at 5 47 41 am](https://user-images.githubusercontent.com/8238880/48395741-2e4e8600-e753-11e8-9216-4084388a5743.png)

**Comment by nopdotcom** [comment]
For future reference: you will save a lot of pain if you go through [the README's configuration instructions](https://github.com/StreisandEffect/streisand/blob/master/README.md#bootstrap).
