### ISSUE TITLE
I have no Tor&sslh（ As shown）

### ISSUE THREAD

**Issue by sjnhnp** [StreisandEffect/streisand#1482]
![image](https://user-images.githubusercontent.com/18591921/48394473-aebeb800-e74e-11e8-9d41-4f0824aef252.png)

**Comment by alimakki** [comment]
Hi @sjnhnp 

Tor is currently disabled in the installer as there's an issue with upstream preventing it from installing correctly.  SSLH is not a VPN per se, it is mostly used in the background to multiplex multiple connections over a single port. If you're using OpenVPN over port 443, the gateway, or SSH over port 443, you're using SSLH :)

Thanks!
