### ISSUE TITLE
Obfsproxy OpenVPN ( Scramble )

### ISSUE THREAD

**Issue by Mehran** [StreisandEffect/streisand#1485]
is OpenVPN support  Obfsproxy ( Obf3sproxy / Obf4sproxy ... ) 

if yes How ? in a normal way or another way?

**Comment by cpu** [comment]
Hi @Mehran,

Streisand does not deploy OpenVPN with a configuration that would operate with Obfsproxy. I'm not sure if that is possible. If it is I don't know how.
