### ISSUE TITLE
Mirror Tunnelblick for macOS FAILED

### ISSUE THREAD

**Issue by kimaero** [StreisandEffect/streisand#1489]
### Actual Behavior:
```
TASK [openvpn : Mirror Tunnelblick for macOS] **********************************************************************************************************************************
fatal: [121.198.172.54]: FAILED! => {"changed": false, "dest": "/var/www/streisand/mirror/openvpn", "gid": 33, "group": "www-data", "mode": "0755", "msg": "Request failed: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>", "owner": "www-data", "size": 4096, "state": "directory", "uid": 33, "url": "https://tunnelblick.net/release/Tunnelblick_3.7.6a_build_5080.dmg"}

TASK [openvpn : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
```

### Ansible Information

* Ansible version: 2.6.5
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  18.04
* Python interpreter: python
* Python version: 2.7.15rc1

### Streisand Information

* Streisand Git revision: a90e8ce9594cb83a14f6bbc50890535faba895d8
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by alimakki** [comment]
This appears to be a transient network error and I'm unable to reproduce this issue.
