### ISSUE TITLE
how to update streisand?

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1491]
### Actual Behavior:
how do i update streisand
I haven't updated it for a long time, I want my new version to have the most current new versions and a nice addition to the function

How to do this without removing the streisand itself?

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]
### Ansible Information

* Ansible version: 2.6.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: af4a3ab60f73faed82a5b1d9e5fa4d522f93b263
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: True

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

##### *Operating System of target host:* 
```Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```
##### *Version of Ansible, using `ansible --version` :*
```ansible 2.6.0
  config file = /root/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
**af4a3ab60f73faed82a5b1d9e5fa4d522f93b263**

**Comment by cpu** [comment]
> How to do this without removing the streisand itself?

Unfortunately you can't. For more information see my comment here:
https://github.com/StreisandEffect/streisand/issues/513#issuecomment-431588195

If you have this need I recommend you look into a project that was designed with a more holistic system-wide update feature like Jigsaw's Outline: https://getoutline.org/en/home

**Comment by rdbox** [comment]
@cpu 
I really hoped that you invented something and were able to develop an automatic update.
Many users write about this, meaning this important function that we all need

**Comment by cpu** [comment]
Hi @rdbox

I agree that Streisand users would benefit from something like that. Unfortunately I'm not working on new Streisand features or bugfixes anymore and just help reply to issues when I have time. I think something as large a feature as this will be challenging to add retroactively to Streisand, especially given the number of hours the remaining maintainers have to give to the project.

**Comment by rdbox** [comment]
@cpu 
Your project is very powerful, it can not be stopped to develop.
Streisand is a whole complex of tools I want the developers to know about it.
ANALOGUES Streisand NO !!!

**Comment by cpu** [comment]
I hope that the folks that feel similar to yourself will step up and help @alimakki and @nopdotcom with bug fixes, issue triage and feature development! :-)
