### ISSUE TITLE
Error when installing streisand on AWS

### ISSUE THREAD

**Issue by DarkBlueSky18** [StreisandEffect/streisand#1499]
When trying to install streisand on AWS. I get the following error.

TASK [genesis-amazon : Create the EC2 instance] ***********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "assign_public_ip only available with vpc_subnet_id"}
	to retry, use: --limit @/home/osboxes/streisand/playbooks/amazon.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=15   changed=9    unreachable=0    failed=1

**Comment by DarkBlueSky18** [comment]
osboxes@osboxes:~/streisand$ which python
/usr/bin/python
osboxes@osboxes:~/streisand$ 
osboxes@osboxes:~/streisand$ python --version
Python 2.7.6
osboxes@osboxes:~/streisand$ 
osboxes@osboxes:~/streisand$ 
osboxes@osboxes:~/streisand$ uname -a
Linux osboxes 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
osboxes@osboxes:~/streisand$ 
osboxes@osboxes:~/streisand$ ansible --version
ansible 2.7.5
  config file = /home/osboxes/streisand/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
osboxes@osboxes:~/streisand$ 
osboxes@osboxes:~/streisand$ git rev-parse HEAD
30f4999f849ab978fc8a9a2710194cfb84fa2d16
osboxes@osboxes:~/streisand$

**Comment by DarkBlueSky18** [comment]
Setup:
Linux client that runs streisand is on a Oracle Virtual Box running Ubuntu 14.04. Trying to run streisand via Virtual box linux to eliminate the need for a dedicated linux machine.

**Comment by deniztoprak** [comment]
I ran into the same issue, I removed `venv` directory, reinstalled everything and it solved the problem.
