### ISSUE TITLE
iOS WireGuard QR code support?

### ISSUE THREAD

**Issue by c-edw** [StreisandEffect/streisand#1500]
There's an app available on the iOS App Store for WireGuard now. I'm assuming that I could just plug it into any WireGuard server and it would just work. The app has the ability to *Add a new WireGuard tunnel* using *Create from QR code*. It hints that a QR code can be generated using `qrencode -t ansiutf8 < tunnel.conf`.

It would be really handy if the generated instructions could include a QR code that could be scanned by this app.

**Comment by alimakki** [comment]
Hi @c-edw 

QR codes are currently being generated, you should be able to find them under the android instructions and they do work on iOS without any issues.

**Comment by c-edw** [comment]
Great! The only thing that should changed is displaying the QR code on the iOS instructions too.
