### ISSUE TITLE
Problem when install (AWS)

### ISSUE THREAD

**Issue by Malamut54** [StreisandEffect/streisand#1509]
Hello!
I run the installation script and after entering all the necessary data, I get an error during the installation.

### TASK [genesis-amazon : Create the EC2 instance] ***************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "assign_public_ip only available with vpc_subnet_id"}
	to retry, use: --limit @/home/malamut/streisand/playbooks/amazon.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=15   changed=9    unreachable=0    failed=1   

Target Cloud Provider: AWs
Operating System of client: Ubuntu 18.04.1 LTS"
Version of Ansible: ansible 2.7.6
git rev-parse HEAD :c917634659dad330d7a9d95344e2eee350541e35

Thanks for help!

**Comment by MarcBlackmer** [comment]
I ran into the same thing using the default VPC and subnet. When I created a VPC and associated subnet and used those, installation proceeded.

**Comment by nopdotcom** [comment]
I think this is related to legacy VPC/subnets. I saw this once in `us-east1` but never elsewhere.

If people want IPv6 support on AWS, we may need to create fresh VPCs; it's no fun to reconfigure existing ones to allocate IPv6 addresses.
