### ISSUE TITLE
TASK [gpg : Ensure a GPG agent is running] fails

### ISSUE THREAD

**Issue by asanari** [StreisandEffect/streisand#1521]
### Expected behavior:
Install on AWS EC2 clean Ubuntu 16.04
Change hostname
apt-get update
Follow install commands

### Actual Behavior:
Installation error on TASK [gpg : Ensure a GPG agent is running]

### Steps to Reproduce:
Run install normally on a fresh Ubuntu 16.04 EC2 instance

**Comment by asanari** [comment]
Don't run the install as root like this asshat and this won't happen.

**Comment by virtadpt** [comment]
Don't be mean.  You don't have to be mean.

**Comment by nopdotcom** [comment]
I agree. @asanari, that wasn't cool.

Could you re-open with a streisand-diagnostics.md?
