### ISSUE TITLE
Which method allows multiple client connection other than OpenVPN?

### ISSUE THREAD

**Issue by dilandyechiel** [StreisandEffect/streisand#1527]
Hi,

Just would like to know that other than OpenVPN, which other method of connection to VPN allows multiple clients to connect at the same time?

Thanks for answering and your time!

**Comment by dilandyechiel** [comment]
Any love here?

**Comment by alimakki** [comment]
Hi @dilandyechiel 

Streisand has been configured to *not* allow simultaneous users to connect with the same profiles, including OpenVPN unless you specifically override the generated configurations.

**Comment by dilandyechiel** [comment]
Hi. Thanks for answering, Two more question:

1. What provides multiple profile other than Openvpn?
2. I knew to what change required in generated configuration for single profile to use multiple connection in Openvpn. Can we do same to SSH and Shadowsocks? If yes then how?
