### ISSUE TITLE
ERROR! Module "vars" shadows the name of a reserved keyword. Please rename or remove this module. 

### ISSUE THREAD

**Issue by d1mirl1n** [StreisandEffect/streisand#1535]
Hello, is not established, checked on several machines the same error, also tried to roll back on ansible-2.6.0
### 
[DEPRECATION WARNING]: 'include' for playbook includes. You should use
'import_playbook' instead. This feature will be removed in version 2.8.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
ERROR! Module "vars" shadows the name of a reserved keyword. Please rename or remove this module. Found at /root/streisand/global_vars/vars.yml

**Comment by tkmw1985** [comment]
Confirm, Same issue !!!

**Comment by tkmw1985** [comment]
any solutions ?

**Comment by Pahom-ka** [comment]
Confirm, don't have any idea.

**Comment by d1mirl1n** [comment]
a week ago I checked everything worked

**Comment by Pahom-ka** [comment]
![image](https://user-images.githubusercontent.com/29920847/54825950-ca6b3980-4cbf-11e9-859c-1c0f62f4f990.png)
I got this error

**Comment by dilandyechiel** [comment]
I confirm the same error

**Comment by vandorb12** [comment]
Just to ask, are any of you trying to install this on a localhost, or are you attempting to build on a VPS?
Have you tried looking at the advanced installation instructions? https://github.com/StreisandEffect/streisand/blob/master/Advanced%20installation.md

**Comment by tiberzann** [comment]
Fixed by renaming at ./global_vars/ **vars.yml** file to **varss.yml**
Then **grep -rni vars.yml** and change link to **varss.yml** everywhere.

**Comment by Pahom-ka** [comment]
> Fixed by renaming at ./global_vars/ **vars.yml** file to **varss.yml**
> Then **grep -rni vars.yml** and change link to **varss.yml** everywhere.

Нет, получилось по расширенной инструкции.

**Comment by Pahom-ka** [comment]
> Just to ask, are any of you trying to install this on a localhost, or are you attempting to build on a VPS?
> Have you tried looking at the advanced installation instructions? https://github.com/StreisandEffect/streisand/blob/master/Advanced%20installation.md

Thank you, i found solution on this page

**Comment by Pahom-ka** [comment]
> Hello, is not established, checked on several machines the same error, also tried to roll back on ansible-2.6.0
> 
> [DEPRECATION WARNING]: 'include' for playbook includes. You should use
> 'import_playbook' instead. This feature will be removed in version 2.8.
> Deprecation warnings can be disabled by setting deprecation_warnings=False in
> ansible.cfg.
> ERROR! Module "vars" shadows the name of a reserved keyword. Please rename or remove this module. Found at /root/streisand/global_vars/vars.yml

Use this command:
`deploy/streisand-local.sh \
    --site-config global_vars/noninteractive/local-site.yml`

**Comment by tiberzann** [comment]
> 
> 
> > Fixed by renaming at ./global_vars/ **vars.yml** file to **varss.yml**
> > Then **grep -rni vars.yml** and change link to **varss.yml** everywhere.
> 
> Нет, получилось по расширенной инструкции.

Да вот, у коллеги не вышло. Потому и полез так "чинить". Может кому-то еще поможет.

**Comment by Pahom-ka** [comment]
In local-site.yml need add this strings:
`streisand_client_test: no
upstream_dns_servers:
  - 1.0.0.1
  - 1.1.1.1
#or your favorite DNS servers`

**Comment by tkmw1985** [comment]
> > Hello, is not established, checked on several machines the same error, also tried to roll back on ansible-2.6.0
> > [DEPRECATION WARNING]: 'include' for playbook includes. You should use
> > 'import_playbook' instead. This feature will be removed in version 2.8.
> > Deprecation warnings can be disabled by setting deprecation_warnings=False in
> > ansible.cfg.
> > ERROR! Module "vars" shadows the name of a reserved keyword. Please rename or remove this module. Found at /root/streisand/global_vars/vars.yml
> 
> Use this command:
> `deploy/streisand-local.sh \ --site-config global_vars/noninteractive/local-site.yml`

confirming advanced installation works fine !!!

**Comment by dvukolov** [comment]
> Fixed by renaming at ./global_vars/ **vars.yml** file to **varss.yml**
> Then **grep -rni vars.yml** and change link to **varss.yml** everywhere.

Works for me

**Comment by gdub010101** [comment]
This appears to be some sort of weird side effect of this commit:

https://github.com/StreisandEffect/streisand/commit/5e30c8ad2b53ef1dd0fe756b2ab89ec3bd4a0033#diff-f79cbdab862069e44bafb519a1026967

You can resolve it by commenting out this line in streisand/streisand

`export ANSIBLE_LIBRARY=
`

so it's

`#export ANSIBLE_LIBRARY=`

**Comment by nopdotcom** [comment]
This is my bug. I'll revert that line for now.
