### ISSUE TITLE
OpenVPN not connecting with Digital Ocean droplet instance

### ISSUE THREAD

**Issue by chriscrosstalk** [StreisandEffect/streisand#1563]
Hello - first of all, thanks for a great project.  I have been experimenting with different methods of installing Streisand, but I keep running into the same issue - OpenVPN will not connect, times out, and then continuously retries to connect, failing each time.

I am using the Digital Ocean method, but I have also tried doing a fresh clean Ubuntu 16.04 instance as well - both were exhibiting the same behavior.

I am able to connect fine using the SSH method/Firefox proxy settings - that works great - it's just OpenVPN that I'm having issues with (I have not tried any other methods).

I did receive two failure messages (where it paused for 20 seconds) during the installation process:

Install Error #1:

TASK [download-and-verify : Verify the OpenVPN Community download signatures were from the correct keys] ***
failed: [134.209.34.251] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [134.209.34.251] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [134.209.34.251]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

Install Error #2:

TASK [download-and-verify : Verify the PuTTY download signatures with the Streisand GPG keyring] ***
failed: [134.209.34.251] (item={u'sig': u'putty.exe.gpg', u'file': u'putty.exe'}) => {"changed": true, "cmd": ["gpgv2", "--keyring", "/root/.gnupg/streisand/pubring.gpg", "/var/www/streisand/mirror/ssh/putty.exe.gpg", "/var/www/streisand/mirror/ssh/putty.exe"], "delta": "0:00:00.014367", "end": "2019-04-16 15:47:32.288544", "item": {"file": "putty.exe", "sig": "putty.exe.gpg"}, "msg": "non-zero return code", "rc": 2, "start": "2019-04-16 15:47:32.274177", "stderr": "gpgv: Signature made Sat 16 Mar 2019 04:37:48 PM UTC using RSA key ID 4AE8DA82\ngpgv: Can't check signature: No public key", "stderr_lines": ["gpgv: Signature made Sat 16 Mar 2019 04:37:48 PM UTC using RSA key ID 4AE8DA82", "gpgv: Can't check signature: No public key"], "stdout": "", "stdout_lines": []}

----------
OpenVPN session log:
----------

Tue Apr 16 09:17:11 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Tue Apr 16 09:17:11 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Apr 16 09:17:11 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Enter Management Password:
Tue Apr 16 09:17:11 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25343
Tue Apr 16 09:17:11 2019 Need hold release from management interface, waiting...
Tue Apr 16 09:17:12 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25343
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'state on'
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'log all on'
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'echo all on'
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'bytecount 5'
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'hold off'
Tue Apr 16 09:17:12 2019 MANAGEMENT: CMD 'hold release'
Tue Apr 16 09:17:12 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Apr 16 09:17:12 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Apr 16 09:17:12 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Apr 16 09:17:12 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Apr 16 09:17:12 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]134.209.34.251:636
Tue Apr 16 09:17:12 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Tue Apr 16 09:17:12 2019 Attempting to establish TCP connection with [AF_INET]134.209.34.251:636 [nonblock]
Tue Apr 16 09:17:12 2019 MANAGEMENT: >STATE:1555431432,TCP_CONNECT,,,,,,
Tue Apr 16 09:17:13 2019 TCP connection established with [AF_INET]134.209.34.251:636
Tue Apr 16 09:17:13 2019 TCP_CLIENT link local: (not bound)
Tue Apr 16 09:17:13 2019 TCP_CLIENT link remote: [AF_INET]134.209.34.251:636
Tue Apr 16 09:17:13 2019 MANAGEMENT: >STATE:1555431433,WAIT,,,,,,
Tue Apr 16 09:17:13 2019 MANAGEMENT: >STATE:1555431433,AUTH,,,,,,
Tue Apr 16 09:17:13 2019 TLS: Initial packet from [AF_INET]134.209.34.251:636, sid=75b12537 cba41ebd
Tue Apr 16 09:17:13 2019 VERIFY OK: depth=1, C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate
Tue Apr 16 09:17:13 2019 VERIFY KU OK
Tue Apr 16 09:17:13 2019 Validating certificate extended key usage
Tue Apr 16 09:17:13 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Apr 16 09:17:13 2019 VERIFY EKU OK
Tue Apr 16 09:17:13 2019 VERIFY X509NAME OK: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=wall-screen-ginger
Tue Apr 16 09:17:13 2019 VERIFY OK: depth=0, C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=wall-screen-ginger
Tue Apr 16 09:17:13 2019 Connection reset, restarting [0]
Tue Apr 16 09:17:13 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Apr 16 09:17:13 2019 MANAGEMENT: >STATE:1555431433,RECONNECTING,connection-reset,,,,,
Tue Apr 16 09:17:13 2019 Restart pause, 5 second(s)
Tue Apr 16 09:17:18 2019 SIGTERM[hard,init_instance] received, process exiting
Tue Apr 16 09:17:18 2019 MANAGEMENT: >STATE:1555431438,EXITING,init_instance,,,,,

----------
OpenVPN server /var/log/syslog output
----------

Apr 16 16:17:15 streisand2 openvpn[15627]: Tue Apr 16 16:17:15 2019 w.x.y.z:63445 openvpn_execve: unable to fork: Resource temporarily unavailable (errno=11)
Apr 16 16:17:15 streisand2 openvpn[15627]: Tue Apr 16 16:17:15 2019 w.x.y.z:63445 openvpn_execve: unable to fork: Resource temporarily unavailable (errno=11)
Apr 16 16:17:15 streisand2 systemd-networkd[20611]: tun0: Lost carrier
Apr 16 16:17:15 streisand2 systemd[1]: Starting Update resolvconf for networkd DNS...
Apr 16 16:17:15 streisand2 sh[15870]: sed: can't read /run/systemd/netif/leases/*: No such file or directory
Apr 16 16:17:15 streisand2 systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Apr 16 16:17:15 streisand2 systemd[1]: openvpn@server.service: Unit entered failed state.
Apr 16 16:17:15 streisand2 systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
Apr 16 16:17:16 streisand2 sh[15870]: sed: can't read /run/systemd/netif/leases/*: No such file or directory
Apr 16 16:17:16 streisand2 ntpd[9696]: Deleting interface #13 tun0, 10.8.0.1#123, interface stats: received=0, sent=0, dropped=0, active_time=396 secs
Apr 16 16:17:17 streisand2 sh[15870]: sed: can't read /run/systemd/netif/leases/*: No such file or directory
Apr 16 16:17:20 streisand2 sh[15870]: message repeated 3 times: [ sed: can't read /run/systemd/netif/leases/*: No such file or directory]
Apr 16 16:17:20 streisand2 systemd[1]: openvpn@server.service: Service hold-off time over, scheduling restart.
Apr 16 16:17:20 streisand2 systemd[1]: Stopped OpenVPN service for server.
Apr 16 16:17:20 streisand2 systemd[1]: Starting OpenVPN service for server...
Apr 16 16:17:20 streisand2 systemd[1]: Started OpenVPN service for server.
Apr 16 16:17:20 streisand2 openvpn[15913]: Tue Apr 16 16:17:20 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Apr 16 16:17:20 streisand2 systemd-networkd[20611]: tun0: Gained carrier
Apr 16 16:17:20 streisand2 openvpn[15913]: Tue Apr 16 16:17:20 2019 Could not determine IPv4/IPv6 protocol. Using AF_INET
Apr 16 16:17:21 streisand2 sh[15870]: sed: can't read /run/systemd/netif/leases/*: No such file or directory
Apr 16 16:17:21 streisand2 ntpd[9696]: Listen normally on 14 tun0 10.8.0.1:123
Apr 16 16:17:21 streisand2 ntpd[9696]: new interface(s) found: waking up resolver
Apr 16 16:17:22 streisand2 sh[15870]: sed: can't read /run/systemd/netif/leases/*: No such file or directory

----------
streisand-diagnostics.md file:
----------

### Ansible Information

* Ansible version: 2.6.5
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 8f06cadd1500c7cdc02889fe1683d1124e00f78b
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

Any help or suggestions would be appreciated - thanks!

**Comment by akha666** [comment]
increase  **LimitNPROC** to 27 in
```
/lib/systemd/system/openvpn@.service
/etc/systemd/system/openvpn@server.service
/etc/systemd/system/openvpn@server-udp.service
```
then do 
`systemctl daemon-reload`

finally, restart all OpenVPN service or simply restart your droplet.

**Comment by dokzlo13** [comment]
> increase **LimitNPROC** to 27 in
> 
> ```
> /lib/systemd/system/openvpn@.service
> /etc/systemd/system/openvpn@server.service
> /etc/systemd/system/openvpn@server-udp.service
> ```
> then do
> `systemctl daemon-reload`
> 
> finally, restart all OpenVPN service or simply restart your droplet.

Yes, this solution works fine for DigitalOcean droplet.
Checked for profiles with all available profiles (direct, 443 TCP, 8757 UDP, combined) on linux and android devices.

## streisand-diagnostics.md file:

### Ansible Information

* Ansible version: 2.6.5
* Ansible system: Linux
* Host OS: Archlinux
* Host OS version:  NA
* Python interpreter: python
* Python version: 2.7.16

### Streisand Information

* Streisand Git revision: 8f06cadd1500c7cdc02889fe1683d1124e00f78b
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by chriscrosstalk** [comment]
That worked perfectly - thank you!

**Comment by patthiel** [comment]
Confirming this solution works on Linode as well. There's a PR to remove LimitNPROC entirely: https://github.com/StreisandEffect/streisand/pull/1553
