### ISSUE TITLE
Stunnel OpenVPN times out using Stunnel 5.50+

### ISSUE THREAD

**Issue by okay** [StreisandEffect/streisand#1571]
### Expected behavior:
Stunnel VPN connects with no issues
### Actual Behavior:
TIMEOUTconnect Exceeded error, VPN connection times out
### Steps to Reproduce:
1. Have Stunnel 5.30 on Streisand server (this is the version my Streisand instance is using)
2. Use Stunnel 5.50+ on your client machine
3. Try to connect to the VPN with the stunnel.conf provided from Streisand setup (mine is slightly modified - i've removed sslh and nginx and instead configured openvpn to work via port 443, it's worked before but recently it stopped working)
4. VPN times out

I've used Stunnel 5.39 on my client machine and it works fine with the VPN. However, I cannot downgrade Stunnel on one of the machines a friend is using. Upgrading the Stunnel version on the server to 5.50 breaks the VPN, even if I am using v5.50 on my client machine as well.

I do not have this file anymore as I didn't think I needed it, my instance has worked since December 2018 and I recently reinstalled it and still the issue is there.

**Comment by 0xNF** [comment]
I have also recently (that is, today), started to see timeouts while connecting via stunnel. However I am using v5.49 on my client.

**Comment by okay** [comment]
The funny thing is that it used to work on 5.51, with my jailbroken iPhone 8, but now it just times out. v5.30 is being used on the sever end. Hmm. I hope this can get fixed soon, as I use Stunnel all the time at school to bypass filters.

**Comment by okay** [comment]
I reinstalled and now it works, but I'll reopen this if it starts to act up again.
