### ISSUE TITLE
v2ray-plugin Installation problem

### ISSUE THREAD

**Issue by JonathanLehner** [StreisandEffect/streisand#1590]
I installed streisand on digital ocean

Output is:
TASK [shadowsocks : Copying v2ray-plugin to shadowsocks-libev directory] **********************************************************************************************************************
fatal: [165.22.55.50]: FAILED! => {"changed": true, "cmd": "cp /root/go/bin/v2ray-plugin /etc/shadowsocks-libev", "delta": "0:00:00.003960", "end": "2019-06-21 15:39:38.613855", "msg": "non-zero return code", "rc": 1, "start": "2019-06-21 15:39:38.609895", "stderr": "cp: cannot create regular file '/etc/shadowsocks-libev/v2ray-plugin': Text file busy", "stderr_lines": ["cp: cannot create regular file '/etc/shadowsocks-libev/v2ray-plugin': Text file busy"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/streisand/playbooks/digitalocean.retry

What to do about this?

**Comment by engmabdulwahab** [comment]
same problem.

**Comment by engmabdulwahab** [comment]
for now we can disable shadowsocks from the installer until someone  find a solution

**Comment by denoza** [comment]
@JonathanLehner were you setting it up on a fresh instance?

**Comment by drkiller2016** [comment]
Yes I am.
