### ISSUE TITLE
Problem in install Ansible

### ISSUE THREAD

**Issue by mostafa74** [StreisandEffect/streisand#1592]
Hi

I try to install Ansible with '  source ./venv/bin/activate ' Command but it's didn't work and return './venv/bin/activate: No such file or directory', I try this command on ubuntu

**Comment by sfoerster** [comment]
The virtual python environment directory `venv` must exist first and is created by running:

`./util/venv-dependencies.sh ./venv`

Also note that `./venv/bin/activate` is a relative path so you must run this command from the same directory that you run `./util/venv-dependencies.sh ./venv` which is from the streisand directory.

The installation instructions are here: https://github.com/StreisandEffect/streisand/blob/master/Installation.md

**Comment by nopdotcom** [comment]
Closing due to age. @mostafa74, reopen if you're still having problems.

**Comment by TheNomad11** [comment]
I had the same issue. By running 
`./util/venv-dependencies.sh ./venv`
a second time, a lot of other stuff got installed and I was able to run
`source "./venv/bin/activate"`
