### ISSUE TITLE
Failed to connect to the host via ssh: Permission denied

### ISSUE THREAD

**Issue by coci** [StreisandEffect/streisand#1595]
fatal: [198.143.179.135]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}

**Comment by sfoerster** [comment]
Did you select the name of the correct SSH public key to install on the streisand server? This needs to be a public key for which you have the corresponding private key (possibly `~/.ssh/id_rsa.pub`). You may need to upload this public key to your cloud provider before running streisand.

**Comment by blacksun777** [comment]
Make sure the keys are not too public as ssh will not accept them and not use them. 
I did something like that: 
```
sudo chown YOU ~/.ssh/id_rsa 
sudo chmod 400 ~/.ssh/id_rsa
ssh-add ~/.ssh/id_rsa
```
And then try to SSH into the instance itself by yourself.

**Comment by stevenbouillon** [comment]
Some people might take "YOU" literally

sudo chown $USER:$USER ~/.ssh/id_rsa
sudo chmod 400 ~/.ssh/id_rsa

You can put both on the same line if you put && before the 2nd sudo command

**Comment by nopdotcom** [comment]
This is good advice, so I'm changing the name of the bug to make it easier to find. @coci, if you're still having problems, re-open this bug?

**Comment by test2a** [comment]
i am facing this exact error on my ubuntu system trying to set up an instance on linode

**Comment by wajahatahmed245** [comment]
hello getting this error 

> **fatal: [52.173.150.120]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).", "unreachable": true}**

on my azure VM , have tried the @blacksun777  your solution but its not working for me

**Comment by steven-bouillon** [comment]
> hello getting this error
> 
> > **fatal: [52.173.150.120]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).", "unreachable": true}**
> 
> on my azure VM , have tried the @blacksun777 your solution but its not working for me

You need to make sure your SSH key is added to your authorized_keys file on the virtual machine.

Do you have the id_rsa and id_rsa.pub file on your computer? If so, you need to make sure the contents of id_rsa.pub is added to your azure virtual machine.

**Comment by steven-bouillon** [comment]
> hello getting this error
> 
> > **fatal: [52.173.150.120]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).", "unreachable": true}**
> 
> on my azure VM , have tried the @blacksun777 your solution but its not working for me

actually, you need to do the following

sudo chown -R $USER:$USER ~/.ssh && chmod 600 ~/.ssh/*

You don't need/want to use 'sudo' in front of chmod because you already own the file.

**Comment by wajahatahmed245** [comment]
@netfxtech its working its generating file too for me  now thanks a lot but there is an issue when i use the conf file of wire-guard its not performing its job ...it doesn't connect to the region .. here is how i have done the configurations 

- made VM on Azure 
- selected existing server 
- only selected wireguard
- files are generated

when i use that files in **_up_** command of wire-guard they don't serve me in fact my internet gets disconnected
