### ISSUE TITLE
shadowsocks-libev.service wont start

### ISSUE THREAD

**Issue by gragragrab** [StreisandEffect/streisand#1599]
### Expected behavior:
I am able to login into web page, connect via 443 port.
### Actual Behavior:
Web server refuses to display me the login page (ERR_CONNECTION_REFUSED);
I cannot connect via OpenVPN's 443 port;
Shadowsocks doest work.
### Steps to Reproduce:

I wish I know. Everything broke after a regular reboot.

### Additional Details:
`journalctl -u shadowsocks-libev.service` output
https://gist.github.com/gragragrab/f708f84ceedc28f092e4e71e5a77429f

**Comment by rayhu** [comment]
Looking at your log, it seems udp stack failed to bind to port 8530. You can find the parameters by running the below command:

systemctl status shadowsocks-libev.service

It shall be:

/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u

The -u at the end tells ss-server to bind UDP. So you might work around it by remove the -u switch, delete the $DAEMON_ARGS from the command line. Or figure out why the udp binding is not successful.

See the page of ss-server:
http://manpages.ubuntu.com/manpages/bionic/man1/ss-server.1.html

**Comment by gragragrab** [comment]
Here is the output of `systemctl status shadowsocks-libev.service`:
```
Process: 24621 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
```
It does not have any other parameters, other than -c.

**Comment by gragragrab** [comment]
Solved by wiping everything.
