### ISSUE TITLE
Readme should contain more information about future usage

### ISSUE THREAD

**Issue by Mayurifag** [StreisandEffect/streisand#1600]
I have installed streisand on my yet another VPS. I almost had no issues, except some gpg problems which I was able to skip and make everything working fine.

I decided to add some services to the VPS, i.e. Nextcloud instance. (or gitlab or wiki or whatever). So what I have to know at this point? Readme should contain this information, I hope.

So if I want Nextcloud at the subdomain, what have I do? 
Do I need to change the default streisand nginx configuration? 
Do I need to do something with letsencrypt? 
Is the certificate wildcard or not? 
Do I need to allow anything else at ufw or iptables?
Any additional information?

VPS after streisand looks like magic box, which you don't know how to cook for your needs.
Is there anybody who installed the Nextcloud after streisand, may you write some information about the topic, please?

**Comment by z0rc** [comment]
Streisand isn't designed out of the box to coexist with user installed software. Of course it's possible to install and configure something like Nextcloud on Streisand instance, but you are on your own with this.

In general just get a second VPS (they are super cheap these days) and install anything you need on it.

**Comment by Mayurifag** [comment]
I was missed the idea I had to have wildcard or subomain dns so thats why i wasnt able to connect

Still I had to remake the certificate to have wildcard there. Why wildcard SSL isn't avaiable by default? Just because streisand has to be the one thing on the vps??

**Comment by stevenbouillon** [comment]
I believe the information you're requesting is outside the scope of this project. I would suggest learning a bit about Docker and Traefik if you would like to add other services and have SSL handled seamlessly
