### ISSUE TITLE
Ansible 2.8.0 bad assert causes fatal failure during aws setup.

### ISSUE THREAD

**Issue by blacksun777** [StreisandEffect/streisand#1617]
### Expected behavior:
AWS instance is launched correctly

### Actual Behavior:
ec2_eip in ansible fails assert. Fatal error and aborted setup process. 

### Steps to Reproduce:
1. run ./streisand AWS Singapur manual VPC and subnet 

### Additional Details:
The problem can be fixed by modifying the ansible version in the requirements.txt to `2.8.3` before setting up the virtual env with `./util/venv-dependencies.sh ./venv`

related ansible issue:
https://github.com/ansible/ansible/pull/59231

**Comment by nopdotcom** [comment]
#1626 will take care of this. Thank you for the bug report.

**Comment by nopdotcom** [comment]
Fixed by #1626.
