### ISSUE TITLE
GCE: Failure on TASK [gce-network : Create network]

### ISSUE THREAD

**Issue by zee-shany** [StreisandEffect/streisand#1623]
I'm unable to provision streisand server on GCP, i've gotten past the json file step but the process seems to fail at "TASK [gce-network : Create network]". I've managed to setup on AWS, DO platform successfully, this is my first time on GCP. Any pointers to solution will be highly appreciated. sorry in advance if i've not submitted/formatted the this ticket as required.

### Expected behavior:
Installation process will complete.
### Actual Behavior:
Installation process is cancelled because of the gce-network error.
### Steps to Reproduce:
1. Run ./streisand
2.Choose Google as provider
3.Choose 35 as zone
4.Key "enter" for default server name
5.Enter location of my streisand.json file
6. Key "enter" to begin install process

[ contents of `streisand-diagnostics.md` here ]

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
:

PLAY [Provision the GCE Server] ************************************************************

TASK [Gathering Facts] *********************************************************************
ok: [localhost]

TASK [Set the Google Compute Engine Zone interactive] **************************************
ok: [localhost]

TASK [Register JSON file contents] *********************************************************
ok: [localhost]

TASK [Set JSON file contents fact] *********************************************************
ok: [localhost]

TASK [Set the Google Compute Engine Service Account Email] *********************************
ok: [localhost]

TASK [Set the Google Compute Engine Project ID] ********************************************
ok: [localhost]

TASK [gce-network : Create network] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "libcloud with GCE support (0.17.0+) required for this module"}

PLAY RECAP *********************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

(venv) root@streisandbuilder:~/streisand#

##### *Version of Ansible, using `ansible --version` : (venv) root@streisandbuilder:~/streisand# ansible --version
ansible 2.8.0
  config file = /root/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/streisand/venv/local/lib/python2.7/site-packages/ansible
  executable location = /root/streisand/venv/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]*

**Comment by nopdotcom** [comment]
Could you attach the contents of `streisand-diagnostics.md`?

**Comment by zee-shany** [comment]
Hi nopdotcom,

i tried looking for streisand-diagnostics.md file under top level of directory, I only see below

(venv) root@streisandbuilder:~/streisand# ls -la
total 368
drwxr-xr-x 12 root root   4096 Aug 12 07:24 .
drwx------  7 root root   4096 Aug 12 07:27 ..
-rw-r--r--  1 root root   2397 Aug 12 07:22 Advanced installation.md
-rw-r--r--  1 root root    719 Aug 12 07:22 ansible.cfg
-rw-r--r--  1 root root   6699 Aug 12 07:22 CONTRIBUTING.md
drwxr-xr-x  2 root root   4096 Aug 12 07:22 deploy
drwxr-xr-x  4 root root   4096 Aug 12 07:22 documentation
-rw-r--r--  1 root root   3991 Aug 12 07:22 Features.md
drwxr-xr-x  8 root root   4096 Aug 12 07:22 .git
drwxr-xr-x  2 root root   4096 Aug 12 07:22 .github
-rw-r--r--  1 root root    400 Aug 12 07:22 .gitignore
drwxr-xr-x  4 root root   4096 Aug 12 07:22 global_vars
-rw-r--r--  1 root root   5281 Aug 12 07:22 Installation.md
drwxr-xr-x  2 root root   4096 Aug 12 07:22 inventories
-rw-r--r--  1 root root  36362 Aug 12 07:22 LICENSE
-rw-r--r--  1 root root 141163 Aug 12 07:22 logo.jpg
drwxr-xr-x  4 root root   4096 Aug 12 07:22 playbooks
-rw-r--r--  1 root root  17895 Aug 12 07:22 README-chs.md
-rw-r--r--  1 root root  21020 Aug 12 07:22 README-fr.md
-rw-r--r--  1 root root   5526 Aug 12 07:22 README.md
-rw-r--r--  1 root root  28244 Aug 12 07:22 README-ru.md
-rw-r--r--  1 root root    636 Aug 12 07:22 requirements.txt
-rw-r--r--  1 root root   5552 Aug 12 07:22 Services.md
-rwxr-xr-x  1 root root   7168 Aug 12 07:22 streisand
drwxr-xr-x  4 root root   4096 Aug 12 07:22 tests
-rw-r--r--  1 root root   1018 Aug 12 07:22 .travis.yml
drwxr-xr-x  2 root root   4096 Aug 12 07:22 util
-rw-r--r--  1 root root   1380 Aug 12 07:22 Vagrantfile
-rw-r--r--  1 root root    817 Aug 12 07:22 Vagrantfile.remotetest
drwxr-xr-x  6 root root   4096 Aug 12 07:24 venv
(venv) root@streisandbuilder:~/streisand#

I believe streisand-diagnostics.md is not yet created at this point in provisioning. 

appreciate your support.

**Comment by nickgnazzo** [comment]
I ran into this issue too recently. The only thing that worked for me was installing `apache-libcloud` inside of the virtualenv:

`(venv) user@home:/streisand# pip install apache-libcloud`

After that I was able to run the GCP build normally. I would imagine adding this to Streisand's requirements.txt wouldn't be that big of a deal to fix this, assuming it's not purely an upstream bug.

I can't remember for the life of me where I found the issue thread for this fix, but some digging shows this is coming from the gce_net ansible module, around this line:

https://github.com/ansible/ansible/blob/v2.8.0/lib/ansible/modules/cloud/google/gce_net.py#L301

The module does a quick check to see if importing `libcloud` works earlier in that file, and if it gets an `ImportError`, it fails on that line with the error message you saw. It's not clear to me why this only recently became a problem (did Streisand recently remove `apache-libcloud` from requirements.txt?).

**Comment by zee-shany** [comment]
thanks for your input.
I tried running pip install apache-libcloud inside of virtualenv then ran the installation, however this time it gave some bigger error under TASK [gce-network : Create network ] compared to before.

TASK [gce-network : Create network] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unexpected response: ({u'locationType': u'parameter', u'domain': u'global', u'message': u\"Invalid value 'StreisandVPN-network'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'\", u'reason': u'invalidParameter', u'location': u'network'}). Detail: Traceback (most recent call last):\n  File \"/tmp/ansible_gce_net_payload_pptHUs/__main__.py\", line 325, in main\n    network = gce.ex_get_network(name)\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7348, in ex_get_network\n    response = self.connection.request(request, method='GET').object\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 121, in request\n    response = super(GCEConnection, self).request(*args, **kwargs)\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/common/google.py\", line 815, in request\n    *args, **kwargs)\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/common/base.py\", line 636, in request\n    response = responseCls(**kwargs)\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/common/base.py\", line 155, in __init__\n    self.object = self.parse_body()\n  File \"/root/streisand/venv/local/lib/python2.7/site-packages/libcloud/common/google.py\", line 285, in parse_body\n    raise InvalidRequestError(message, self.status, code)\nInvalidRequestError: {u'locationType': u'parameter', u'domain': u'global', u'message': u\"Invalid value 'StreisandVPN-network'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'\", u'reason': u'invalidParameter', u'location': u'network'}\n"}

PLAY RECAP *********************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

(venv) root@streisandbuilder:~/streisand#

:(

**Comment by nickgnazzo** [comment]
Looks like the naming convention for the GCE network isn't passing a regex test. From your error message it looks like you're trying to name your server "StreisandVPN"? That regex looks like it only accepts lowercase names for GCP networks, maybe try naming your server "streisandvpn" instead (or just the default "streisand")?

**Comment by zee-shany** [comment]
Thanks nickgnazzo, you are absolutely correct, I tried again with all defaults settings and it went past through the gce-network task. it is currently building and nearly completing.

many thanks for your support :))

**Comment by zee-shany** [comment]
All good now 👍 Thanks again for your support nickgnazzo, appreciated.
