### ISSUE TITLE
unable to browse after connecting wireguard

### ISSUE THREAD

**Issue by zee-shany** [StreisandEffect/streisand#1627]
### Expected behavior:
Able to browse internet after android wigureguard client connection is established
### Actual Behavior:
wg client on android is up
unable to browse internet, chrome error: DNS_PROBE_FINISHED_NO_INTERNET
### Steps to Reproduce:
1. 

 [### Ansible Information

* Ansible version: 2.8.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 15bbbccfbb4b5af83a68a56b959fc2211443189d
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 20]

### Additional Details: 
I've used Localhost type installation on azure as I wanted to run streisand server on UAE-north DataCentre. The normal procedure under azure didn't show up UAE north option to create streisand server so i used localhost option.

appreciate if someone can suggest how to troubleshoot this issue of no browsing.
------------------------------------------------------
wg0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.192.122.1  P-t-P:10.192.122.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP  MTU:1420  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

content of /etc/resolv.conf

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1

**Comment by zee-shany** [comment]
so I have now tried another method "existing server" which was successfully completed however experiencing same issue of no browsing.
in addition to wireguard client, I tried openconnect method on win 10 and below is the log

2019-08-16 13:00:38 |  850 | POST https://x.x.x.x:4443/
2019-08-16 13:00:38 |  850 | Attempting to connect to server x.x.x.x:4443
2019-08-16 13:00:59 |  850 | Failed to connect to x.x.x.x:4443: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2019-08-16 13:00:59 |  850 | Failed to connect to host x.x.x.x
2019-08-16 13:00:59 |  850 | Failed to open HTTPS connection to x.x.x.x
2019-08-16 13:00:59 |  850 | Authentication error; cannot obtain cookie
2019-08-16 13:00:59 | 27c0 | Disconnected

I'm not sure what is the issue. On Azure portal HTTPS, SSH ports are open.
I appreciate if anyone can support in troubleshooting.
Thanking in advance.

**Comment by lucasff** [comment]
I'm having problems with the Handshake in Wireguard. It keeps retrying. Also suddenly today my OpenConnect stopped working.

**Comment by zee-shany** [comment]
@lucasff thanks for your comment. I'm not expert in this, so apologies I won't be able to help you much. I could suggest to open a new issue ticket with your findings and provide full diagnostic logs so an expert can help you better.

fortunately, i was able to find the cause of my issue in this ticket. The cause was, required inbound protocol/ports were not opened for striesand to pass traffic in/out. I assumed wrongly that under localhost & existing server type installation, streisand would open the required protocol/ports.

I hope you can find fix to your issue soon. I'll go ahead and close this issue as its now resolved.
Thanks
