### ISSUE TITLE
[localhost]: FAILED! => {"changed": false, "msg": "found unpermitted parameters: virtio"}

### ISSUE THREAD

**Issue by zee-shany** [StreisandEffect/streisand#1634]
### Expected behavior:
To complete the installation on Digital Ocean
### Actual Behavior:
installation stops at 

TASK [genesis-digitalocean : Create the new Droplet] ***************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DoError: found unpermitted parameters: virtio
fatal: [localhost]: FAILED! => {"changed": false, "msg": "found unpermitted parameters: virtio"}

TASK [genesis-digitalocean : fail] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to create the Droplet. Please ensure that the API Access Token you provided has the Write Scope enabled."}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

##### *Version of Ansible, using `ansible --version` : ansible 2.8.0
  config file = /root/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/streisand/venv/local/lib/python2.7/site-packages/ansible
  executable location = /root/streisand/venv/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609
##### *Output from `git rev-parse HEAD` in your Streisand directory 🔢 (venv) root@streisandbuilder:~/streisand# git rev-parse HEAD
edb862353962a6e9642238c011d6879234acb852

**Comment by zee-shany** [comment]
I've checked scope for token it has write enabled
ssh key is also present

**Comment by N0xFF** [comment]
Formatted error:

```
TASK [genesis-digitalocean : Create the new Droplet] 
The error was: DoError: found unpermitted parameters: virtio
```

Also, setup process shows warning:

> [DEPRECATION WARNING]: digital_ocean is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain
>  more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
> deprecation_warnings=False in ansible.cfg.

Looks like we need to update Digitalocean module.

I found https://github.com/StreisandEffect/streisand/pull/1629, but got a new error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "found unpermitted parameters: id"}
```

Algo have same issue https://github.com/trailofbits/algo/issues/1571.

**Comment by nopdotcom** [comment]
Yeah, both `digital_ocean` and `digital_ocean_droplet` are broken. I'm filing bugs.

**Comment by nopdotcom** [comment]
OK, https://github.com/ansible/ansible/issues/61664 and https://github.com/ansible/ansible/issues/61665. I submitted #1635 but want to test it a little more before we seriously think of merging it.

@N0xFF, thanks for the pointer to Algo; that really saved some time.

**Comment by andrewsomething** [comment]
Thanks for raising this. I mentioned this in the Ansible issue opened by @nopdotcom, but wanted to share this info here as well.

The team at DigitalOcean made change deployed to the `/v2/droplets` endpoint to reject requests with extra, non-supported parameters. This was not communicated properly, and broke existing implementations. The change has been rolled back, and this should now work as it did previously. Sorry for the disruption.

**Comment by zee-shany** [comment]
Thanks All for your input and support. I can confirm the installation on DO went through successfully.
I shall close this issue.
Thanks.
