### ISSUE TITLE
Stop Using Ubuntu

### ISSUE THREAD

**Issue by zx2c4** [StreisandEffect/streisand#1640]
Ubuntu is not the most reliable distro to use, and their kernels tend to be a bit flaky, resulting in issues like https://github.com/StreisandEffect/streisand/issues/1637. It might be worthwhile to consider switching to a different distro, perhaps one that stays closer to mainline and has more active package managers, such as Arch.

**Comment by tiliarou** [comment]
Ideally, it would be better to support multiple distro but it's a ton of work...

**Comment by zx2c4** [comment]
Adding distro choice sounds even worse. The goal would be to pick something that actually works well and stick with it.

**Comment by tiliarou** [comment]
But then you exclude a potentially huge amount of people from using streisand... Ubuntu is really "mainstream" and easy to start with compared to Arch.

**Comment by zx2c4** [comment]
I'm referring to what's run on the server, not the client.

**Comment by tiliarou** [comment]
Fair enough, but Arch is not available with as many provider as Ubuntu is.
In my case, I'm using basic Aruba Cloud and Oracle Always Free instances and Arch is not offered. But maybe the most used like AWS and alike always offer Arch ?

**Comment by its0x08** [comment]
a debian and freebsd version would be awesome !!! 
freebsd is known for networking/firewall/vpn 
debian is known to be very close to kernel and over years it introduces very few major changes like ubuntu (mainly bugfixes and security patches) so debian is ideal choice and offered everywhere
also ubuntu is not bad .. the bad part is that it works only with ubuntu 16.04 and nothing else at all 
so at least make it fully compatible with most recent ubuntus..!

**Comment by lucasff** [comment]
I think streisand is more or less a thing that you want to "set and forget". If it works reliably, why care which system is under? I never SSH'ed into my Streisand server and I hope I never need to.

**Comment by nerdspar** [comment]
i can understand ubuntu being flaky at times, but many cloud/vps providers don't offer images for *bsd or arch so it's sort of a diy type of situation.  i'd be willing to take on different architecture support but it would be a huge chunk of time.

**Comment by zx2c4** [comment]
As an update to this issue, we've managed to get WireGuard as a supported package in 18.10. So I'll close this issue and somebody can follow up on the "don't use ancient Ubuntu" one.

**Comment by its0x08** [comment]
at least support the 3-4 last major ubuntu releases so that every ubuntu vps at least would work!!!
not all my ubuntus work!!!!!
so thats a problem also

**Comment by tiliarou** [comment]
You can't support all ubuntu come on...
But at least the latest LTS would be great.
