### ISSUE TITLE
anything changed on AWS? a working server on aws has stopped working on wireguard

### ISSUE THREAD

**Issue by zee-shany** [StreisandEffect/streisand#1641]
I had 2 streisand servers in different aws region and were working ok with wireguard. I was helping one of my friend to setup his streisand server on aws but couldn't get to work. I then checked mine and appears both my servers are broken. tried android/PC wireguard client, connection is establish with the server end but no browsing happens. 

Any one has any idea? please advise.

Thanks.

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by zee-shany** [comment]
Anyconnect method works off of AWS ireland/bahrain server.. so its specifically wireguard affected. I've tested wireguard through other cloud providers (azure/DO) they work fine on my devices so, its not the ISP/network issue.

**Comment by nickgnazzo** [comment]
Maybe you're running into the issue described here?

https://github.com/StreisandEffect/streisand/issues/1637#issuecomment-529013444

Ubuntu made an oopsie by breaking WireGuard recently in the kernel (I think kernel headers specifically). WireGuard published a workaround for this in the Ubuntu package, so you might be able to fix it by just running `apt update && apt upgrade`. If it shows updates available for the wireguard package it might be you just needed to get the workaround.

Are you getting errors in your logs like the one in that issue above? (like `Handshake did not complete`?)

**Comment by zee-shany** [comment]
Thanks @nickgnazzo this indeed is the same issue. fixed it by following @zx2c4 instruction
