### ISSUE TITLE
Still not able to connect with Wireguard

### ISSUE THREAD

**Issue by iynere** [StreisandEffect/streisand#1644]
### Steps to Reproduce:
Run regular installation steps (I customized to disable everything except Wireguard, and I'm installing on a non-standard cloud provider, Lunanode, with a standard Ubuntu 16.04 server)

### Ansible Information

* Ansible version: 2.8.4
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.14.5
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 4c82389dfe307205f752e49bf09badfb4feaf28a
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  False
* Wireguard enabled: True
* OpenVPN enabled: False
* stunnel enabled: False
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: False
* SSH forward user enabled: False
* Configured number of VPN clients: 3

My server seems to have the newer versions of `wireguard-dkms` & `wireguard-tools` that are mentioned [in this comment](https://github.com/StreisandEffect/streisand/issues/1637#issuecomment-529013444) (`0.0.20190905`)—for example, [the three lines mentioned here](https://github.com/StreisandEffect/streisand/issues/1637#issuecomment-528373875) are already present in my `/var/lib/dkms/wireguard/0.0.20190905/source/compat/compat.h` file—but am still not able to browse the internet after connecting to my Wireguard tunnel (same behavior across iOS, Android, and macOS)

Like others, this was working fine for me until a few days ago. Since then, I've tried repeatedly re-provisioning on fresh Ubuntu 16.04 servers without success.

**Comment by BranZhang** [comment]
How you fixed this problem? 
I encountered same problem like you.

**Comment by dfortescue** [comment]
I seem to be having the same issue (using Lightsail as my host). WIreguard was working initially but no longer works after an update. The handshake never completes.

I've validated connectivity using netcat, so doesn't appear to be a firewall problem.
