### ISSUE TITLE
Unable to finish installation on minimal vulter vps

### ISSUE THREAD

**Issue by its0x08** [StreisandEffect/streisand#1689]
### Expected behavior:
Installation to complete
### Actual Behavior:
installation breaks the whole vps
### Steps to Reproduce:
1. just followed steps on installation.md untill the ./streisand 

[ contents of `streisand-diagnostics.md` here ]

##### *Output from `git rev-parse HEAD` in your Streisand directory :*

i think the codebase of the project is getting big and mine freezes in the middle of installation !!
there are alot of operation being made that i see them as strictly unnecessary and they should be removed or simplified ...!!!
it failed 4 times verifying external ip using opendns.com and dig command
then it failed like 9 times at the step that adds nginx repo or something...
so if there is any solution please reach out!!
thank u.

**Comment by nopdotcom** [comment]
This is very weird; most of my operational servers are on Vultr, and it's my second test platform.

Is there a way you could make a complete transcript of your interactions with a Vultr server? The log is probably big and/or sensitive, so email is fine. I'm at `nop@nop.com`, GPG accepted.

**Comment by its0x08** [comment]
Sorry but cant do that !!
