### ISSUE TITLE
How i can update all package installed via streisand?

### ISSUE THREAD

**Issue by AHTOLLlKA** [StreisandEffect/streisand#1690]
### Expected behavior:
Connect to internet using WireGuard

Linux rootuser 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[https://i.imgur.com/O7a5I2P.jpg](url)

### Actual Behavior:
how update all package installed via streisand? or just apt-get update/upgrade is enough?

**Comment by nopdotcom** [comment]
The `unattended-upgrades` package is installed, so all security-related upgrades of software from mainline and PPAs will be performed automatically.

Unfortunately, there is not a good way to upgrade software we've built from source code ourselves. Redeploying the server is the upgrade, then.

We greatly prefer software delivered via PPA for this reason.
