### ISSUE TITLE
selinux

### ISSUE THREAD

**Issue by tastesliketriangle** [StreisandEffect/streisand#1713]
installing to a centOS server using localhost. install fails despite `selinux` being installed.

```
TASK [lineinfile] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

##### *Target Cloud Provider:*
Vultr
##### *Operating System of client:*
CentOS Linux release 8.1.1911 (Core)
##### *Version of Ansible, using `ansible --version` :*
```
ansible 2.8.4
  config file = /home/talitr/streisand/ansible.cfg
  configured module search path = ['/home/talitr/streisand/library']
  ansible python module location = /home/talitr/streisand/venv/lib64/python3.6/site-packages/ansible
  executable location = /home/talitr/streisand/venv/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
c2a8236ade43b5f1aaf2ada30ba1dbae57dc2422

**Comment by nopdotcom** [comment]
We don't support installing *to* anything but Ubuntu 16.04. (I suspect we're going to jump directly to 20.04 shortly.) Please reopen if I'm misunderstanding you?
