### ISSUE TITLE
No VPN response on Azure,it doesnt work for me and my mates 

### ISSUE THREAD

**Issue by wajahatahmed245** [StreisandEffect/streisand#1791]
### Expected behavior:
When i use wireguard client it should be accessed and up

### Actual Behavior:
The **_conf_** file generated by streisand doesnt work 

### Steps to Reproduce:
1. run **_streisand_**  on azure VM 
2. select **_existing server_** 
3. Provide your VM **_IP_**
4. only allow wire-guard service to generate conf file
5. the generated docs is created with **_.html_** file follow it , go to the address it points to and add username password it has provided
6. select linux , downlaod conf file and use that in wire-guard client

**Comment by gruberdev** [comment]
May be related to that: https://github.com/StreisandEffect/streisand/issues/1569
and it seems like an old issue: https://github.com/StreisandEffect/streisand/issues/1611

Could you provide more information or any sort of logs? At least the stdout (output) of the terminal?

**Comment by wajahatahmed245** [comment]
@VerifiedGruber  thanks alot .. it was solved .
the mistake i made was this that there is a generated doc with 2 files the **_firewall_** file has details about the port which were required to be there so after adding those on azure **inbound ports** i was finally able to connect .
