### ISSUE TITLE
Invalid type for parameter Unit when installing on AWS from Mac

### ISSUE THREAD

**Issue by thomaswitt** [StreisandEffect/streisand#1827]
### Actual Behavior:

When installing streisand on AWS with Python 3.9 on MacOS 11.1 (installed via homebrew) (which worked a few month ago - so I am installing alongside a running instance with a new name), I'll get an error - I first thought it's because I am installing from the AWS root user (found some similar reports that API behavior has changed and a username which was transmitted before for root isn't transmitted anymore), but same result with an IAM user.

`
TASK [genesis-amazon : Create CloudWatch alarm to auto-recover instance] *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Unit, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/xg/2_ffq7p10f5gc6wvq9fcg50w0000gn/T/ansible_ec2_metric_alarm_payload_c4gdi__y/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py\", line 406, in <module>\n  File \"/var/folders/xg/2_ffq7p10f5gc6wvq9fcg50w0000gn/T/ansible_ec2_metric_alarm_payload_c4gdi__y/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py\", line 400, in main\n  File \"/var/folders/xg/2_ffq7p10f5gc6wvq9fcg50w0000gn/T/ansible_ec2_metric_alarm_payload_c4gdi__y/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py\", line 254, in create_metric_alarm\n  File \"/usr/local/lib/python3.9/site-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/botocore/client.py\", line 648, in _make_api_call\n    request_dict = self._convert_to_request_dict(\n  File \"/usr/local/lib/python3.9/site-packages/botocore/client.py\", line 696, in _convert_to_request_dict\n    request_dict = self._serializer.serialize_to_request(\n  File \"/usr/local/lib/python3.9/site-packages/botocore/validate.py\", line 297, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter Unit, value: None, type: <class 'NoneType'>, valid types: <class 'str'>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

### Ansible Information

* Ansible version: 2.9.6
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.15.6
* Python interpreter: python3
* Python version: 3.8.5

### Streisand Information

* Streisand Git revision: af5eb7dac157a2416ea64cba96cf32f7f505d9ff
* Streisand Git clone has untracked changes: yes
* Genesis role: genesis-amazon
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by lmerritt47** [comment]
Having a similar problem did you find any workaround?

**Comment by thomaswitt** [comment]
The problem didn't appear anymore when using the newest version of Streisand.
