### ISSUE TITLE
Unable to download certificate (IE, Chrome on Win7 Ultimate)

### ISSUE THREAD

**Issue by hux2000** [StreisandEffect/streisand#308]
I launched Streisand from a newly built Ubuntu 14.04.4 VM and successfully created an Amazon EC2 instance. I then opened '~/streisand/generated-docs/streisand.html' using Google Chrome (v50.0.2661.102) running on Windows 7 Ultimate. However, when I click the "Download Certificate" link there, Chrome blocks it entirely. If I open the same page in IE11, that link causes the page to attempt to navigate somewhere, but it hangs endlessly.

So...how can I install this cert?

**Comment by jlund** [comment]
What error does Chrome display (if any)?

**Comment by hux2000** [comment]
![google_streisand_cert_block](https://cloud.githubusercontent.com/assets/1163924/15797483/09409e6e-29cf-11e6-8b0e-f96093960193.png)

But I figured out the solution: after dismissing it (which is the only option), you can do CTRL+J to open the downloads window, then click "recover malicious file" to force the download it.

A pain in the ass, but it works. :)

**Comment by jlund** [comment]
Huh. Good to know there's a workaround. I'll try to think of a better way to solve this too. Chrome doesn't do this on Linux, OS X, or Windows 10. Firefox should also work. I haven't tested Edge yet.

**Comment by edbury** [comment]
I'm now getting the same thing on OS X. Workaround is the same, though. Thanks @hux2000.

**Comment by cpu** [comment]
Linking this issue to https://github.com/jlund/streisand/issues/440 - there may be a workaround to help with both.

**Comment by cpu** [comment]
RE: IE, closing this in favour of https://github.com/StreisandEffect/streisand/issues/1058 RE: Chrome/OSX I believe the issues reported are no longer applicable with the rework done by @nopdotcom in master.
