### ISSUE TITLE
[Feature req] Add SOCKS5 and HTTP proxy

### ISSUE THREAD

**Issue by tebowy** [StreisandEffect/streisand#35]
This could be useful for getting some selected apps to works with streisand. Proxy could be just a non-caching one, so eg. squid.  Pardon me if this functionality is already included. 

[edit] Wait, Socks is normally unencrypted?

**Comment by Keridoo** [comment]
OpenSSH does not seem to be part of Streisand anymore. Is there a current method to setup a SOCKS5 proxy? If not, could it be added? I explain my need for it [here](https://github.com/StreisandEffect/discussions/issues/119).
