### ISSUE TITLE
Can't download certificate in Safari.

### ISSUE THREAD

**Issue by d1r7y** [StreisandEffect/streisand#440]
Because Safari doesn't support the "download" attribute, clicking on the Download Certificate button in the generated-docs/streisand.html file downloads a file named Unknown.

Right clicking and using Download Linked File has the same issue.

It would be nice if the HTML were updated to support Safari.  It could just be something simple like using the correct certificate name when using Download Linked File.

**Comment by quinncomendant** [comment]
If Streisand includes a filename with a `.cer` extension the file would open in Keychain Access by double-click. This can be achieved by sending a `Content-Disposition: attachment; filename=streisand-certificate.cer` header with the http response.

**Comment by nopdotcom** [comment]
Apple suggests a Content-Type of `application/x-x509-ca-cert` in [their OTA guide](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/iPhoneOTAConfiguration/profile-service/profile-service.html#//apple_ref/doc/uid/TP40009505-CH2-SW24).

**Comment by nopdotcom** [comment]
This works now in Safari 11; it might have worked before but I neglected this bug.
