### ISSUE TITLE
Remove/modularize Monit HTTP interface

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#636]
Presently Streisand ships monit with the HTTPD interface enabled but bound only to localhost. An Nginx proxy-pass is configured for `/monit` to allow HTTP basic authenticated users to access the monit interface.

Long term we should evaluate whether this is necessary functionality or just Yet More Attack Surface. At the very least we should consider making the web interface an opt-in choice or modular component. The [Monit httpd docs](https://mmonit.com/monit/documentation/monit.html#MONIT-HTTPD) also detail all sorts of authentication options & support for read-only users that may be useful for minimizing the potential for harm.

**Comment by cpu** [comment]
We should 100% definitely remove Monit and its web interface. Related: https://github.com/StreisandEffect/streisand/issues/704

**Comment by alimakki** [comment]
PR #1292
