### ISSUE TITLE
Add IP SAN to snakeoil certificates

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#641]
Presently the [self-signed certificate generation](https://github.com/jlund/streisand/blob/f5c83d0a8ef9ab8a567d95ff6e8d04c66b07783e/playbooks/roles/streisand-gateway/tasks/main.yml#L14:L43) used for the streisand-gateway HTTPS does not include IP type SAN entries, only a deprecated common name field. This causes issues with Chrome and modern TLS clients.

With the current `openssl` based approach its a minor pain to add these SAN entries and I think there are larger issues to address with the TLS configuration first but this issue captures the problem in the meantime.

**Comment by cpu** [comment]
Likely the root cause of https://github.com/jlund/streisand/issues/579

**Comment by cpu** [comment]
This caused another user to experience problems in #793. I'll try to prioritize getting a fix for this landed after the modular shadowsocks/wireguard PRs land. I have an in-progress branch from a few months ago to complete.

**Comment by mmmooorrrttt** [comment]
Thank you for your response to the similar issue in #793. I have some follow-up questions. First, if I ignore the privacy warning and click through, the page is not secure (http, not https). Is this safe? I'm typing stuff into the clear.

Second, why does the certificate work on Safari but not Chrome or Firefox? Even when I disable all extensions (including Avast), I still get the privacy warning.

Thank you for your time and attention.

**Comment by cpu** [comment]
>  First, if I ignore the privacy warning and click through, the page is not secure (http, not https)

Are you sure that's the case? I believe it is probably HTTPS but marked insecure.

> Is this safe? I'm typing stuff into the clear.

If the only error you clicked through was the missing subject alternate name error then it is reasonable safe. I believe in this case the CA signature on the certificate is checked and so there's a reasonable assurance that the certificate is the one that was generated as part of your Streisand bootstrap and not a replacement.

> Second, why does the certificate work on Safari but not Chrome or Firefox? Even when I disable all extensions (including Avast), I still get the privacy warning.

I am not sure. Chrome rightly enforces that SANs are present because the Common Name field is deprecated. I don't know if Firefox does the same thing. Safair likely still allows the legacy behaviour of a Subject Common Name without a Subject Alternate Name.

> Thank you for your time and attention.

Happy to try and help!

**Comment by mmmooorrrttt** [comment]
-> Are you sure that's the case? I believe it is probably HTTPS but marked insecure.

On Chrome I get a big red "Insecure" and HTTPS struck through. Also, I don't get a request for my user name and password, though I might have signed in at some earlier time (I haven't restarted Chrome because I have a jillion tabs open regarding this issue).

On Firefox, however, I have HTTPS showing with a ! sign saying I have a security exception.

Just reporting more information for your consideration. Obviously, I'll use Safari to set things up. I assume everything will work and be secure once I start using the openVPN.

Again, thanks for your help.

**Comment by cpu** [comment]
> On Chrome I get a big red "Insecure" and HTTPS struck through

That makes sense since you ignore the SAN error. Expected :-)

> Also, I don't get a request for my user name and password, though I might have signed in at some earlier time 

That sounds like the most likely explanation. Chrome will cache HTTP authentication between visits.

> On Firefox, however, I have HTTPS showing with a ! sign saying I have a security exception.

Have you followed the "SSL Certificate Installation" instructions for Firefox from the generated docs file for your server? There shouldn't be any errors in Firefox if so.

> Just reporting more information for your consideration. Obviously, I'll use Safari to set things up. I assume everything will work and be secure once I start using the openVPN.

I appreciate it! Thank you! These HTTPS related errors shouldn't cause you issues with OpenVPN. If you have any trouble with OpenVPN please open a new issue and we can dig into that separately :-)

**Comment by nopdotcom** [comment]
OS X 10.11 Safari hates the certs that the Streisand Effect Department issues.  (iOS 10 doesn’t like them much either.) I blame SAN too. 

I think this is a blocker for working mobileconfig files for certs on iOS. Tested from head on EC2.

![voila_capture 2017-08-02_03-33-04_pm](https://user-images.githubusercontent.com/1357866/28892352-ace54450-779b-11e7-9008-1d79b5bb02ea.png)

**Comment by cpu** [comment]
This was resolved with https://github.com/StreisandEffect/streisand/commit/3da73df3d3eb4bdd726786181d28b2ac94b65531 :tada:
