### ISSUE TITLE
Replace monit with systemd

### ISSUE THREAD

**Issue by z0rc** [StreisandEffect/streisand#704]
What's the maintainer consensus about using systemd here?

I noticed that couple of key services are launched via rc.local (ugh) and monitored by monit. Given that systemd can properly launch, monitor and restart services on failure, it might be worth investing some time into writing custom unit files or updating default ones with overrides. This would allow to drop monit from list of required services.

**Comment by cpu** [comment]
@jlund What do you think? I suspect you went the monit route before the base system was Ubuntu/systemd?

@z0rc I would be interested in seeing PRs that replaced rc.local / monit with systemd services if it wasn't likely to increase maintenance burden.

**Comment by z0rc** [comment]
@cpu yeah, I can take a look into what can be moved under systemd hood.

**Comment by cpu** [comment]
@z0rc Great - I assigned this issue to you. If you don't end up having time that's no problem, please comment here and I can un-assign it again and add a help wanted tag. No harm no foul :-)

**Comment by Russell-IO** [comment]
@cpu I contributed the monit code, yes it was done during Ubuntu 14.04 times when systemd wasn't supported.

I don't see anything that systemd can't do that monit offers (other than the status page, which arguably should be removed for other reasons)

**Comment by cpu** [comment]
@Russell-IO Thanks for confirming and for contributing the code initially! :+1: 

We're going to be prioritizing this work over the next few weeks. @alimakki has been doing some `systemd` conversion work in preparation :tada:

**Comment by alimakki** [comment]
Monit has been removed as of PR #1292
