### ISSUE TITLE
Documentation: L2TP is suggested for Windows, but it can’t deal with NAT

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#823]
I think this is a *documentation* bug. 

I tried to run an L2TP client on Windows 10. I had the problems described in #291. Other people are going to run into this too, and not be able to figure out why their Windows box isn’t working. I think we should do either or both of:

1. Describe (and provide the .reg file, why not) needed to make Windows L2TP work behind NAT
2. Document that L2TP on Windows has this issue and suggest other methods.

**Comment by cpu** [comment]
> Describe (and provide the .reg file, why not) needed to make Windows L2TP work behind NAT

I think this option is preferable. My only hesitation is a personal unfamiliarity with L2TP and Windows. I would be leaning on other maintainers/users to try and vet the documentation/reg file.

**Comment by nopdotcom** [comment]
Yeah, I'll make a pass at this; the reg is trivial, the pbk isn't. Rather
than finding a Windows RAS wizard immediately, I think it will be easier to
do the first cut, and find a wizard to tell me that I'm wrong.

Another possibility is to generate a per-Streisand-server Windows
"installer" using NSIS just to do any local configuration rather than as an
installer. `apt-cache show nsis`. That's definitely a "later" thing, though.
