### ISSUE TITLE
RFC: make passphrases from more common words

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#824]
### Warning: personal taste

There are a lot of opinions on passphrases. Streisand is not in any *dire* need of new passphrase generation in theory, especially because most users will have to type each passphrase at most one time.

### Expected behavior:

Passwords are long, but are OK to type on an iPhone SE.

### Actual Behavior:

Passwords are shorter, but often made of words that native speakers rarely encounter. They can be difficult to spell and transcribe.

### Suggested behavior

Use longer passphrases from a smaller dictionary.

### Notes

keybase.io uses a [list of 2048 English words](https://github.com/bitcoin/bips/blob/ce1862ac6bcffa1dd20aad858380e51e66e949ea/bip-0039/english.txt) from [BIP-039](https://github.com/bitcoin/bips/blob/d9396155350b16b098a0d0b5ec10da80ebd96d5f/bip-0039.mediawiki) to generate paper keys. The [BIP-039 directory](https://github.com/bitcoin/bips/tree/8fc0e0d4be730f032e3d0e122b344e847c06661b/bip-0039)  includes English, French, Italian, Japanese, and Simplified and Traditional Chinese wordlists, with some rationales described.

An easy way to play with the wordlists is GNU shuf:

```
$ gshuf --head-count=12 --repeat --random-source=/dev/urandom english.txt | tr '\n' ‘ '
coast easy subject belt arctic mule depth track bargain exhibit scene buyer
[...]
reopen all initial bacon castle wonder label consider timber gasp brisk cheap
hockey goose employ blossom gauge distance hair alien update churn wrestle hill
input lottery control message peanut judge gun develop winter execute rapid truth
organ draft disorder hip tent crumble start shrug start remember still stomach
```

which represents 132 bits. For 66: 

```
high easy chaos blast bundle tuition
neutral cube before gun park rose
marine easy welcome history motor pudding
radar mean shadow access ecology color
```

With `/dev/random`, there's 66 or 132 bits of entropy of course.

I can work on the PR, but it’s easy to implement compared to making the design decision.

**Comment by nopdotcom** [comment]
Existing 4-word Streisand passphrases have ~73 bits in them. If 72 is a magic number, add another word.
```
fuel depth best hint burden oxygen unfold
left occur clerk blossom balcony endless oppose
wood naive popular salon grant wedding sight
argue economy phrase chapter squirrel balance quote
```

There is an argument for using “.” instead of “-“ as a separator: mobile keyboards have a good way of typing a period, but dash is usually shifted--or worse, on the symbol-lock keyboard. Yeah, there’s no “.” on the little iPhone keyboard, but you can type it easily by space-space-backspace.

**Comment by cpu** [comment]
@nopdotcom Thanks for the RFC. I'm not tied to the way that Streisand does password generation at present. I've looked at it before hoping to try and consolidate the generation to common code instead of replicating it across roles as is done presently but didn't make much progress. 

I really like the idea of leaning on the work from BIP-039 and Keybase in this space. It seems well reasoned and I don't think there's any reason to reinvent the wheel in isolation.

I'm also a +1 on switching the "-" separator to "." - thinking about these passphrases in the context of mobile device input is extremely sensible.

@jlund @alimakki Do you have strong counter opinions?

**Comment by alimakki** [comment]
@cpu, I think it's a good idea.

**Comment by jlund** [comment]
Thanks for writing up a solid proposal, @nopdotcom. This sounds reasonable to me as well.

We can break out the new BIP-039-based passphrase functionality into a separate role and use the new-ish `include_role` Ansible module instead. That will clean things up quite a bit in the other roles. I think it's a very worthwhile goal to make things easier for mobile users. Switching `-` to `.` is totally obvious in hindsight and I like that a lot.

Hacks that involve pipelines of `grep`, `sed`, and `xargs` (and `awk` if you're lucky!) can sometimes fill their creators with a weird sort of ironic pride, but I won't be sad to see `grep -v -P "[\x80-\xFF]" /usr/share/dict/american-english-huge | sed -e "s/'//" | shuf -n <num> | xargs | sed -e 's/ /-/g'` in fewer places :)

**Comment by cpu** [comment]
@nopdotcom Was there more work you wanted to do in this issue beyond the BIP-039 work that's landed in master?

**Comment by nopdotcom** [comment]
Nope! I'm happy.
