### ISSUE TITLE
Update translations - OpenConnect

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#894]
I merged https://github.com/jlund/streisand/pull/887 which unsynchronized the translations. I suspect this will keep happening and I don't have a great solution so for the time being I think we should create issues when we merge new docs content to update the translations accordingly.

Required updates:
*playbooks/roles/openconnect/templates/instructions.md.j2*:
* [x] - FR - @alimakki Can you update this one?
* [ ] - CHS - @nickolasclarke Can you update this one?
* [ ] - RU - @levleontiev Can you update this one?

Thanks folks!

**Comment by nickolasclarke** [comment]
got it.

**Comment by levleontiev** [comment]
later in August

**Comment by nickolasclarke** [comment]
actually, I was working through tickets quickly and thought this was just in the README.md. We dont have this for chinese yet, but we will. I'm tracking that work in #862

**Comment by HougeLangley** [comment]
OK

**Comment by levleontiev** [comment]
Not sure I'll be able to do it in August. @mbravorus, is there a chance that you could do it?

**Comment by mbravorus** [comment]
Can do. Please clarify, are we talking just about 

playbooks/roles/openconnect/templates/instructions.md.j2

or is there something else that requires a _quick_ update?

Also, if @levleontiev can point me to a branch with unfinished/outdated version, please do, I'll sorta cherrypick then

**Comment by levleontiev** [comment]
No, no unfinished version, sorry.

**Comment by mbravorus** [comment]
If I understand correctly, then we need this file (why not others? I see it is touched by #887 but not clear on why it's so special, sorry if I'm being dumb), but also quite likely we need the rest of the work on playbooks to include Russian the same way French was introduced by @alimakki, right?

I'll try to fill the need, with the minimum amount of guidance :) bear with me a couple days

**Comment by mbravorus** [comment]
I have checked what needs to be done; I'll be able to do a quick job for all template files (within the next 48 hours I hope), but it will be a bit of a preliminary version - since I do not have Windows with Russian locale as primary readily available, I'll do a pass with translating the Instructions but not all localized field names (if any). When I get that set up (a couple virtualboxes will do it nicely), I'll do a second pass.

**Comment by cpu** [comment]
@mbravorus That sounds great. Thank you!

@levleontiev Can I continue to tag you for review on the Russian translation PRs? It definitely helps to have a second person with fluency in the language to check over the work since none of the maintainers speak Russian :-)

**Comment by levleontiev** [comment]
Sure, I am ok to do the reviews - it takes much less time than translation itself ;)

**Comment by alimakki** [comment]
As the translated instructions are only in French at the moment, I think this issue can be closed as its no longer in scope.
