### ISSUE TITLE
Modifications on openssl.cnf

### ISSUE THREAD

**Issue by wzyboy** [StreisandEffect/streisand#902]
### Expected behavior:
- Modifications on `openssl.cnf` should be idempotent;
- System-wide `openssl.cnf` should not be modified.

### Actual Behavior:
- The reverse.

### Steps to Reproduce:
1. Run "streisand-gateway" role for multiple times;
2. Open `/usr/lib/ssl/openssl.cnf` and you can see a lot of repeated lines at the bottom of the file:
```
dir             = /root/ca
dir             = /root/ca
dir             = /root/ca
dir             = /root/ca
dir             = /root/ca
dir             = /root/ca
dir             = /root/ca
```

The idempotent issue is caused by the incorrect usage of Ansible "lineinfile" module (https://github.com/jlund/streisand/blob/61c6e2f73128b687c01f826706e18692c50c1692/playbooks/roles/streisand-gateway/tasks/main.yml#L29-L33).

Another issue is: we should not modify `/usr/lib/ssl/openssl.cnf` at all since this file is managed by package manager and is overwritten the next time OpenSSL package is upgraded (we have unattended upgrades on). The certification generation is a one-time process but we could this in a better way. :-)

Considering the above two issues, maybe we could just ship a full copy of customized `openssl.cnf` for OpenSSL-related operations.

**Comment by nopdotcom** [comment]
I came close to shipping our own `openssl.cnf`, but I backed off because I could get most of the same effect from extfile stuff. But shipping our own seems like it would be a smart thing to do.

We have enough damn cert-like-objects in this system that consolidation of CAs would probably help too.

**Comment by nopdotcom** [comment]
I am amused that Ubuntu ships with both `/usr/lib/ssl/openssl.cnf` and `/etc/ssl/openssl.cnf`, no prizes for guessing which is hardwired into the libraries for `/usr/bin/openssl`. From `strace -e trace=file openssl ca`

```
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
Using configuration from /usr/lib/ssl/openssl.cnf
```

**Comment by cpu** [comment]
Does https://github.com/StreisandEffect/streisand/pull/1063 address this issue?

**Comment by nopdotcom** [comment]
Yes.

**Comment by nopdotcom** [comment]
I should keep this open until #1063 lands, sorry for the noise.

**Comment by nopdotcom** [comment]
Done.
