### ISSUE TITLE
Provisioning GCE fails without registering id_rsa.pub

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#919]
### Expected behavior:

I create ssh keys with `ssh-keygen`. This gives me a new `id_rsa` and `id_rsa.pub`.

I provide a Google `streisand.json` for authorization.

`./streisand` should deploy a working GCE streisand instance.

### Actual Behavior:

`streisand` errors out on initial connect, not authorized.

### Additional Details:

My theory is that Ansible is not actually deploying `id_rsa.pub` to `authorized_keys`. Once `id_rsa.pub` is added to the Google IAM, deployment works.

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*

```
TASK [genesis-google : Set the streisand_server_name variable] ******************************************************
ok: [localhost]
PLAY [Checking instance status] *************************************************************************************
TASK [Wait for cloud-init to complete] ******************************************************************************
fatal: [104.197.125.237]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: 
Permanently added '104.197.125.237' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unre
achable": true}
        to retry, use: --limit @/home/nop/streisand/playbooks/google.retry
PLAY RECAP **********************************************************************************************************
104.197.125.237            : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=22   changed=12   unreachable=0    failed=0
```

##### *Target Cloud Provider:*

GCE

##### *Operating System of target server:*

Ubuntu 16.04 LTS

##### *Operating System of client:*

Debian 8.9. (It’s what the Google Cloud Console has.)

##### *Version of Ansible, using `ansible --version` :*

```
$ ansible --version
ansible 2.3.2.0
  config file = /home/nop/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### *Output from `git rev-parse HEAD` in your Streisand directory :*

b197e7bd79ca1bc7b65b05dae778c82804ba06e0

**Comment by nopdotcom** [comment]
SSH handling failures on GCE is also discussed in #828.

**Comment by cpu** [comment]
I was able to reproduce after I deleted my SSH keys from the control panel. PRs welcome!

**Comment by vypr** [comment]
Same error here.

**Comment by cpu** [comment]
@vypr The bug hasn't been fixed - it's expected to happen in all cases until someone fixes it with a PR :-) You can work around it for now by registering your SSH key in the GCE control panel manually.

**Comment by vadimzharov** [comment]
Hi! I got the same issue (in GCE) - and fixed it by changing in playbooks/roles/genesis-google/tasks/main.yml
#    ansible_user: ubuntu
to 
    ansible_user: root

which seems to be logical..

**Comment by peterpme** [comment]
changing `ansible_user` to `root` did in fact work, thanks! That being said, are there any security repercussions that may come with this?

Thanks!

**Comment by cpu** [comment]
@peterpme even using `ubuntu` as the Ansible user Streisand will become root. There should be no difference - in both cases the Streisand Ansible tasks will be run as root.

**Comment by vadimzharov** [comment]
The problem here is that ansible script which is creating GCE instance (playbooks/roles/genesis-google/tasks/mail.yml) putting user's keys for root user, not for ubuntu:
- name: Create the GCE instance
  gce:
    name: "{{ gce_server_name }}"
...
    metadata: '{"sshKeys":"root:{{ ssh_key.stdout }}"}'
  register: streisand_server

It means that we have to change user from root to ubuntu in this section of the script OR change ansible_user parameter from ubuntu to root (also in this script, section below).

IMHO better to change from root to ubuntu in metadata section.

**Comment by cpu** [comment]
@vadimzharov A PR is better than code in an issue comment :-)

**Comment by vadimzharov** [comment]
I'm new to GitHub sorry, I don't know how to do it (fix) better

**Comment by cpu** [comment]
@vadimzharov Understood, that's ok! Someone from the project can take a look at implementing this workaround.

In the past I [tried using the `ubuntu` user for GCE](https://github.com/StreisandEffect/streisand/commit/15920bf1cce7f6c45c6bbf95273bd452aecd5fba#diff-0a0a4e09a02d5576bcbdcfba49721d6c) and later reverted it [when it wasn't working any longer](https://github.com/StreisandEffect/streisand/commit/e04b034f0b256a791b197d267becee6b90d16e10#diff-0a0a4e09a02d5576bcbdcfba49721d6c). I may have overlooked the SSH key metadata and perhaps that was the reason that it didn't work.

I _thought_ that I had verified that this particular issue meant that the SSH key wasn't being registered at all, for any user, when provisioning a brand new GCE instance. I might be remembering wrong. Seems like there are some workarounds to investigate with fresh eyes.

**Comment by vadimzharov** [comment]
@cpu thanks for understanding.
May be google changing presence of ubuntu user in GCE templates.
Now it exists, but as temporary workaround changing ansible user from ubuntu to root works.
I will try to change/test scripts.

**Comment by nopdotcom** [comment]
What I ended up doing in the cloud-init script was:

```
elif ! quiet id ubuntu; then
    # Some systems don't have an ubuntu user; make an alias for root.
    useradd --non-unique --uid 0 --gid 0 --home-dir /root -s /bin/bash ubuntu
```

**Comment by vadimzharov** [comment]
According to https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
looks like correct attribute to add ssk keys is 'ssh-keys' (not sshKeys).
I've changed in playbooks/roles/genesis-google/tasks/main.yml metadata to 

name: Create the GCE instance
 gce:
   ...
    metadata: '{"ssh-keys":"ubuntu:{{ ssh_key.stdout }}"}'

Then it works for user ubuntu.

**Comment by cpu** [comment]
@vadimzharov Apologies for letting this sit. I've put out a PR (https://github.com/StreisandEffect/streisand/pull/1048) with the fix you suggested. It was spot on - I was able to reproduce the problem & as expected using the correct SSH keys metadata key and setting the SSH key for the ubuntu user worked. Thanks again!
