### ISSUE TITLE
Issues with OpenVPN and SSLDroid in Android 8.0

### ISSUE THREAD

**Issue by itsrajivshah** [StreisandEffect/streisand#922]
### Steps to Reproduce:
1. Follow the steps on the Streisand page to install both SSLDroid and OpenVPN on android and configure as instructed.
2. Ensure SSLDroid service is running
3. Connect to server in OpenVPN

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
![screenshot_20170905-112853](https://user-images.githubusercontent.com/18684709/30057447-a71852c6-922e-11e7-9f83-25234f8f10a0.png)
![screenshot_20170905-112850](https://user-images.githubusercontent.com/18684709/30057448-a7f4e010-922e-11e7-83f4-ee866d709613.png)
![screenshot_20170905-112846](https://user-images.githubusercontent.com/18684709/30057451-a8e55374-922e-11e7-9877-380fb60f846b.png)
![screenshot_20170905-112844](https://user-images.githubusercontent.com/18684709/30057456-a9cf1f18-922e-11e7-8e03-7a794bf9792c.png)

##### *Version of Ansible, using `ansible --version` :*ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

**Comment by alimakki** [comment]
@itsrajivshah Could you let me know what data center on Digital Ocean did you spin your server up on?

**Comment by itsrajivshah** [comment]
@alimakki I spun this one up in the London DC

**Comment by iSsO** [comment]
I can confirm that the same issue happens on Android 8.0

**Comment by historype** [comment]
This issue is not a server issue.SSLDroid app is too old.We need new stunnel client for latest Android OS (Android 7.0, 8.0...).

**Comment by Palatis** [comment]
well the problem is, when VPN connection is established, Android tries to route all connections through VPN, including the stunnel connection.

I'm using [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn), and the solution is to add the tunneling app (SSLDroid, SSL/TLS Tunnel, or whatever) into the "whitelist"...

**Comment by itsrajivshah** [comment]
I can confirm that everything is working fine with @Palatis's suggestion. Thanks all.

**Comment by mariansw** [comment]
@Palatis I am new to Android, Could you please show me how to "whitelist" the Openvpn. Thank you.

**Comment by Keridoo** [comment]
Are there actively maintained Android SSH clients out there – ideally free and open source?

@ghost What do you mean by "too old"? Is SSLDroid broken?

**Comment by arcaartem** [comment]
just to expand on to @Palatis's whitelist solution, you'd have to open OpenVPN app and edit the relevant profile. One of the options at the top is 'Allowed Apps'. If you navigate to that tab, you can exclude "SSLDroid" from using the selected VPN profile

**Comment by Alex220** [comment]
I have the same Issue with Local http-proxy + official openvpn (https://play.google.com/store/apps/details?id=net.openvpn.openvpn) on Android **8**

`route XXX.XXX.XXX.XXX 255.255.255.255 net_gateway` Solves the problem on Android 6 And windows 10, But on Android **8** OpenVPN gets stuck in a loop.
