### ISSUE TITLE
Using only stunnel+openvpn yields 'Bad encapsulated packet length from peer'

### ISSUE THREAD

**Issue by describe19** [StreisandEffect/streisand#962]
I'm attempting to connect via Tunnelblick on OSX

### Expected behavior:
Make TCP connection->server response->get configuration->connected
### Actual Behavior:
Make TCP connection->waiting for server response LOOPS
Have error: WARNING: Bad encapsulated packet length from peer (10784), which must be > 0 and <= 1575
Direct OpenVPN appears to work ok (although i get 'DNS appears to be not working' from tunnelblick)
### Steps to Reproduce:
What I have done
1. Run streisand, set up new DigitalOcean server, select no to everything except OpenVPN and stunnel
2. Follow install instructions for OpenVPN+stunnel on OSX

### Ansible Information

* Ansible version: 2.3.2.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.11.6
* Python interpreter: python
* Python version: 2.7.10

### Streisand Information

* Streisand Git revision: c58d33776cf19570486858d636aad1d8c1c09d2f
* Streisand Git clone has untracked changes: 
* Genesis role: genesis-digitalocean

### Enabled Roles

* Shadowsocks enabled:  False
* Wireguard enabled: False
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: False
* SSH forward user enabled: False
* L2TP enabled: False
* Configured number of VPN clients: 5

**Comment by alimakki** [comment]
@describe19 Could you let me know what data center on Digital Ocean did you spin your server up on?

**Comment by describe19** [comment]
Sorry for the late reply - singapore

**Comment by baimafeima** [comment]
@describe19 Could you tell me how to change the "enabled roles", that is, how to disable some services? Do you do this for security reasons? I have a similar question at #1137 
If you don't need one of the services and they are kept enabled, is there a greater risk for them to be discovered? Many thanks for your support.

**Comment by alimakki** [comment]
@baimafeima to pick and choose which vpn services are installed, when running the `./streisand` script, you will be present with question if you want to customize the install, choose yes. you be prompted with several yes/no questions to enable/disable vpns during install.

**Comment by cpu** [comment]
I think this issue has become stale enough that forward progress is unlikely. I'm going to close this issue for now. Please comment if you are still affected running the latest code in master and are able to coordinate with us on debugging. Thanks!
