### ISSUE TITLE
Support non-interactive usage of Streisand

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#972]
Presently the `./streisand` script invoked to begin provisioning requires user input to select the provisioning genesis role (Amazon, Linode, etc). There is also a request for input if the user wishes to customize the installation, and to safe-guard local and existing server provisioning. Further, the genesis roles themselves prompt for user information: API keys, Cloud regions, server names, etc.

It will be considerable work to make a fully non-interactive provisioning work based on env var/config file pre-specification of inputs but it has been suggested as [one route](https://github.com/StreisandEffect/discussions/issues/20#issuecomment-333266258) towards simplifying a Docker image for the Streisand builder. Personally I think the only way to achieve this is to abstract out the cloud provider provisioning [using terraform](https://github.com/StreisandEffect/discussions/issues/10) and focusing on removing the user input that is strictly Streisand-specific.

**Comment by exratione** [comment]
I think this can be done more straightforwardly than an outright refactor.

I've provided an example pull request that achieves the goal in the present architecture, with minimal Ansible changes.

https://github.com/StreisandEffect/streisand/pull/1022

**Comment by cpu** [comment]
#1022 was merged - there's now non-interactive deployment support in master thanks to @exratione :tada:
