### ISSUE TITLE
Localhost provisioning: Clarify SSH key authentication assumptions.

### ISSUE THREAD

**Issue by sirkyuubi** [StreisandEffect/streisand#974]
When I try to get root access after deploying streisand I get a **Permission denied (publickey).** error.

I'm not sure how to ssh into root.

I deployed my VPS in vultr and used the localhost option since it was a brand new cloud server.

When I was asked for the ssh key I simply left it blank and hit enter.

streisand is working. I haven't tested everything yet, but I can't ssh into the server to make small tweaks.

**Comment by nopdotcom** [comment]
You'll need the `~/id_rsa` you used to create the machine. 

I believe Vultr will also mail you root passwords, usable on the console.

**Comment by sirkyuubi** [comment]
Do I need to get that from the server? I'm slightly new to ssh keys. I usually use login and passwords

**Comment by nopdotcom** [comment]
That might be a documentation bug. If you're configuring localhost, we should be clear that you want a copy of `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub` somewhere other than the very machine you're setting up.

I think your best course is to log into the console and fish out those two files. While you're at it, make sure that the contents of `id_rsa.pub` are listed in `~/.ssh/authorized_keys`, and you'll be able to use `id_rsa` locally to connect. https://www.vultr.com/docs/how-do-i-generate-ssh-keys may be useful, especially if you generate a new machine.

**Comment by sirkyuubi** [comment]
That was also something I found odd. There was no ~/.ssh/authorized_keys file before the streisand install, and after it as well. I will see if I can find a way back into the server. I might have to reset the root through vultr control panel, and it might break the way streisand has configured the server. If that happens I am not sure I will know how to fix it.

**Comment by nopdotcom** [comment]
If you were doing this from scratch (and I'm about to suggest that), you'd generate a local RSA key, and push the local `id.rsa_pub` to Vultr's control panel. When you create instances, you can select uploaded Vultr public keys to push into the instance.

I'm still playing with [my cloud-init script](https://gist.github.com/nopdotcom/fb88fc23028695d3fad531297b7d87d9), which installs all the Streisand dependencies. You can add this as a "Startup Script" in the Vultr "create instance page". If it breaks, you get to keep the pieces...

**Comment by cpu** [comment]
> That might be a documentation bug. If you're configuring localhost, we should be clear that you want a copy of ~/.ssh/id_rsa and ~/.ssh/id_rsa.pub somewhere other than the very machine you're setting up.

I agree. This seems like the best action to take away from this issue. 

As a sidenote, I would generally encourage users not familiar with SSH key authentication to use one of the supported providers instead of Vultr & the advanced localhost provisioning mode. Choosing DigitalOcean, AWS or Linode provisioning will do more of the SSH key management work for you and perhaps be an easier experience overall.

**Comment by sirkyuubi** [comment]
I don't have a choice. Due to latency issues in china setting up streisand took 2 hours. I know because I tried it once on my macbook. I hit over an hour and 30 minutes on DO before canceling the operation and switching to localhost mode.

**Comment by sirkyuubi** [comment]
I also decided to switch to vultr too since they have an LA location. The reason for this is because LA is the closest location to the most convenient submarine communications cable comming out from asia

**Comment by cpu** [comment]
>  Due to latency issues in china setting up streisand took 2 hours. I know because I tried it once on my macbook. I hit over an hour and 30 minutes on DO before canceling the operation and switching to localhost mode.

That's valuable information to hear. You suspect the latency on your SSH connections to the Digital Ocean instance were the cause of the extremely long runtime? If you're willing to try again I would be interested in seeing the full output and where it seems to get hung up.

**Comment by sirkyuubi** [comment]
The latency will always be that way because of the added latency that you get comming out of china.

**Comment by cpu** [comment]
> I'll give you a full output, just give me instructions on how to give it to you, and how to obtain it.

Can you paste it as [a Github gist](https://gist.github.com) and link here?

If possible can you also add the output from `mtr -c 20 -w -r <IP of the DO instance>`. If you're on OSX you can find `mtr` in homebrew.

**Comment by sirkyuubi** [comment]
can you give me a little more information? Do you want me to delete the DO droplet and create a new one then run mtr on it? Please give me the idea behind mtr so I can know how to implement it.

**Comment by cpu** [comment]
> can you give me a little more information? Do you want me to delete the DO droplet and create a new one then run mtr on it?

Yup! The plan would be:
1. Delete the existing Digital Ocean instance that got hung up before
2. Install `mtr` on your OSX machine.
3. Note the current time
4. Go to the place you cloned the Streisand code on your OSX machine and run `./streisand`, choose the Digital Ocean provisioning mode and follow the prompts.
5. Wait for provisioning to complete or get stuck. Copy the output into a Github gist. If it gets stuck please also note the current time
6. Log into the Digital Ocean control panel and find the IP of the server that was created by the Streisand script
7. Run `mtr -c 20 -w -r <That IP Address>`. Copy the output from that `mtr` command in a Github gist

The idea behind running `mtr` is to find out more about the latency from your computer to the Digital Ocean instance. Mtr is like `ping` and `traceroute` combined in one.

Does that make sense?

**Comment by sirkyuubi** [comment]
Ok. I'll start that.
I would like to note that I usually run vpn when I do this.
I like to run shadowsocks sometimes, but shadowsocks seems limited. even when run globally and UDP relay is turned on SS has problems encapsulating UDP since a few app that are UDP dependent still won't tunnel through it.

**Comment by sirkyuubi** [comment]
https://gist.github.com/sirkyuubi/6876db73454ac0c8011e88278d706dfd

**Comment by cpu** [comment]
> but the entire streisand setup was run with the vpn on.

Can you share more details about which VPN you're using? It seems to increase your latency considerably and I don't understand the use case of using a VPN to run Streisand over to provision a VPN server :-)
Based on the log it looks like the provisioning completed successfully, how long did it take this time?

**Comment by sirkyuubi** [comment]
I use airvpn. I connect to Singapore through SSH tunnel which has been the most reliable for me. If you'd like I can send you a copy of the airvpn log privately. Also I will delete the streisand droplet and try it again without vpn, then run mtr, and post the results.

**Comment by sirkyuubi** [comment]
is it possible to split this into 2 threads. One for the SSH key issue and the other for the latency issue?

**Comment by cpu** [comment]
> is it possible to split this into 2 issues. One for the SSH key issue and the other for the latency issue?

Great idea - I've created https://github.com/jlund/streisand/issues/975 for the latency issue.

We can leave this issue strictly for the discussion about making localhost provisioning's assumptions about SSH keys clearer.

**Comment by sirkyuubi** [comment]
I haven't tried your script yet. When streisand asks for my ssh key durring the setup/install phase is it ok to leave it blank? What is the recommended course of action? I have left it blank and I still get a public key error.

**Comment by nopdotcom** [comment]
You should use the same password as you used in `ssh-keygen`. It's a great idea to have an ssh passphrase, but it can complicate the debugging. I think I am confused about your current key setup. Let's decrease the number of variables. Could you `cd ~/.ssh`, and 

```
mv id_rsa id_rsa-hide
mv id_rsa.pub id_rsa.pub-hide
ssh-keygen
```

While we're debugging, you can use no passphrase; later, you can set a passphrase with `ssh-keygen -p`.

**Comment by cpu** [comment]
Closing this from inactivity.
