### ISSUE TITLE
Problem report: High latency renders Streisand provisioning unusable 

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#975]
Originally reported by @sirkyuubi [as part of issue #974](https://github.com/jlund/streisand/issues/974#issuecomment-334014799):
> Due to latency issues in china setting up streisand took 2 hours. I know because I tried it once on my macbook. I hit over an hour and 30 minutes on DO before canceling the operation and switching to localhost mode.

**Comment by cpu** [comment]
Hi @sirkyuubi - I'm reposting my [last questions](https://github.com/jlund/streisand/issues/974#issuecomment-334298953) from #974 here to continue the discussion:

Can you share more details about which VPN you're using? It seems to increase your latency considerably and I don't understand the use case of using a VPN to run Streisand over to provision a VPN server :-)
Based on the log it looks like the provisioning completed successfully, how long did it take this time?

**Comment by sirkyuubi** [comment]
It takes roughly 2 hours. I have about a 200 ping to the CA DO servers. In my opinion this is expected behavior. I'm more than welcome to share my vpn details if you wish to leave me your email, or other contact information.

**Comment by cpu** [comment]
Sure, my email is `daniel <at> binaryparadox.net`

**Comment by cpu** [comment]
Closing this - 2 hours with a 200ms ping to the server seems ~reasonable & I'm not sure how we can take action within the Streisand project to improve on this. Thanks!
