### ISSUE TITLE
can't connect to the VPN server

### ISSUE THREAD

**Issue by Bafrianboy** [StreisandEffect/streisand#976]
i have setup the server successfully BUT i tried all possible  was to connect to it (openVPN , stunnel ,etc) and always disconnecting 

i'm not sure if that from my SIP provider is blocking everything (That's in Egypt)
or
something else wrong
The server installed over Digital Ocean 

https://178.62.61.239/

can any one help me on testing this issue 

Thanks

**Comment by cpu** [comment]
Hi @Bafrianboy,

Can you share more information?

If you have a `streisand-diagnostics.md` file in your Streisand directory please
paste its contents below. 

[ contents of `streisand-diagnostics.md` here ]

If you *do not* have a `streisand-diagnostics.md` file to share, please answer 
the following questions:
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

Can you share the exact error message you see using OpenVPN and the other options you've tried? Which OpenVPN profile did you use?

**Comment by cpu** [comment]
I'm going to close this issue since it's missing information. Please comment with the requested information if you still need help. Thanks!
