### ISSUE TITLE
Anyone knows how to using wireguard client on macOS

### ISSUE THREAD

**Issue by HougeLangley** [StreisandEffect/streisand#985]
I knew how to configure wireguard client on Linux, but how to on macOS, just install wireguard from brew and used command to launch?

**Comment by alimakki** [comment]
WireGuard isn't available on macOS :c

**Comment by cpu** [comment]
To expand on @alimakki's answer (Thanks!) - Wireguard is implemented as a Linux kernel module presently. There is active work being done to create a userland version that could be used for non-Linux operating systems (OSX, Windows, etc) and for devices that can't easily insert kernel modules (Android phones, etc). None are available presently but hopefully over the next year or so there will be better Wireguard options for non-Linux clients :-)

**Comment by HougeLangley** [comment]
But I see wireguard could be install on macOS.

https://www.wireguard.com/install/

**Comment by cpu** [comment]
@HougeLangley You'll note the OSX download says "tools" in light grey font while the other Linux downloads say "module & tools". I believe the OSX download only gives you the few small userland utilities that Wireguard ships to interact with the kernel module. There's no kernel module for OSX so the tools aren't very useful except (I suspect) to the folks that are working on building userland alternatives to the kernel module.

**Comment by yeago** [comment]
experimental effort here https://tunsafe.com/osx

**Comment by cpu** [comment]
> experimental effort here https://tunsafe.com/osx

The author of WireGuard [strong discourages the use of tunsafe](https://lists.zx2c4.com/pipermail/wireguard/2018-March/002448.html):

> Please stay away from this software, and generally be wary of closed-source WireGuard implementations trying to fill the void. This one was written by a community-unfriendly proprietary author, and we've got little way of ensuring protocol compliance or basic security.

My recommendation for Streisand users on OSX is to wait for the upstream WireGuard project to deliver first party support.

**Comment by erndev** [comment]
@HougeLangley @cpu 

I've been using macOS for a while to connect to my streisand wireguard server, and it seems to be working fine so far.

But take into account that the official user space tools for wireguard are still under development, so you may expect crashes or unexpected behaviour. If you're OK with that, you can test it following these steps:

1. Follow [official Wireguard instuctions](https://www.wireguard.com/install/) to install the user space tools using `brew`.
2. Download one of the client configuration files from your Streisand server and copy it to `/usr/local/etc/wireguard/`  (or `/etc/wireguard/`). You'll need to create the directory first.
3. Launch the client with ´sudo wg-quick up service´ . Replace "service" with the name of the configuration filed you copied to ´etc´(without the extension). For instance, if your config file is `viable-wall.conf` you'll start the vpn executing `sudo wg-quick up viable-wall`.
4. To stop the vpn run `sudo wg-quick down viable-wall`

**Comment by cpu** [comment]
@erndev If you're interested in contributing to Streisand adding this information to the documentation would help with https://github.com/StreisandEffect/streisand/issues/1346 !

**Comment by erndev** [comment]
@cpu sure. 
i've forked the project and changed the template, but i have one question.
Is there any one to generate the html files from the templates without deploying a server? 
i'd like to check if i did not break something on the way.

**Comment by cpu** [comment]
> Is there any one to generate the html files from the templates without deploying a server?
> i'd like to check if i did not break anything on the way.

I haven't tried that. Deploying a new server is likely the easiest way to test.

**Comment by cpu** [comment]
> i've forked the project and changed the template, but i have one question.
> Is there any one to generate the html files from the templates without deploying a server?
> i'd like to check if i did not break anything on the way.|

@erndev Alternatively if you open a PR with your changes (Feel free to add "Work-in-progress" to the PR title if you aren't quite finished) and I can take a look & try running it in some test infrastructure.

Thanks!

**Comment by erndev** [comment]
@cpu 
done.
https://github.com/StreisandEffect/streisand/pull/1362

I've been using the android app to connect to my server, and seems to work too.  Like the macOS client, still experimental and potentially unstable, but it connects to the server just fine.

I could add the android instructions too. Anyway, first, i'll wait for the approval of the macos pull request, just to confirm i am editing it property.

**Comment by hadifarnoud** [comment]
@erndev your instruction does not work for me. wireguard says it's connected just fine but I lose internet connection all together.

**Comment by minaguib** [comment]
> @erndev your instruction does not work for me. wireguard says it's connected just fine but I lose internet connection all together.

You likely specified `AllowedIPs = 0.0.0.0/0` (change your default route to the other VPN endpoint), but the other endpoint was not yet configured to act as a router/gateway/NAT
