### ISSUE TITLE
Issue when provisioning server

### ISSUE THREAD

**Issue by ortonomy** [StreisandEffect/streisand#987]
### Expected behavior:
1. Provisioning server runs smoothly
### Actual Behavior:
Error:

FAILED! => {"failed": true, "msg": "The conditional check 'streisand_openconnect_enabled' failed. The error was: error while evaluating conditional (streisand_openconnect_enabled): 'y' is undefined\n\nThe error appears to have been in '/Users/gregoryorton/MEGAsync/dev/shared/devops/streisand/playbooks/roles/ufw/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install UFW\n  ^ here\n"}
### Steps to Reproduce:
1. Try to provision a server

[ contents of `streisand-diagnostics.md` here ]

### Ansible Information

* Ansible version: 2.3.2.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 66f27ec3befe21ba9e24ab492e536317cfd54e58
* Streisand Git clone has untracked changes: 
* Genesis role: genesis-digitalocean

### Enabled Roles

* Shadowsocks enabled:  y
* Wireguard enabled: n
* OpenVPN enabled: n
* stunnel enabled: n
* Tor enabled: n
* Openconnect enabled: y
* TinyProxy enabled: n
* SSH forward user enabled: y
* L2TP enabled: n
* Configured number of VPN clients: 5

**Comment by alimakki** [comment]
@ortonomy, enable/disable should be `yes` or `no`.

Cheers!

**Comment by ortonomy** [comment]
@alimakki -- I'm such an idiot.

**Comment by alimakki** [comment]
Happens to the best of us :)

**Comment by alimakki** [comment]
That's one way to go about it, but I think a better approach is to accept `y` and `n` in addition to what we already do; as CLI users we've all been trained to answer such questions with one letter.

$0.02

**Comment by cpu** [comment]
> That's one way to go about it, but I think a better approach is to accept y and n in addition to what we already do; as CLI users we've all been trained to answer such questions with one letter.

:+1: Agreed - this is what I mean by "fix it in the validation role" but didn't express very well :-)
