### ISSUE TITLE
Let's Encrypt: print the public address explicitly in interview

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#989]
Here's what we get in a remote install for the LE interview:

```
TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] **************
changed: [198.51.100.124]
Which domain do you want to use to host Streisand server?

This is an optional question. If you have a domain that points to your
Streisand server, the installation scripts can request Let's Encrypt
HTTPS certificates for you automatically.  If you do not provide one or
the request fails, self-signed certificates will be used instead.

If you have just created a new cloud server in previous steps, it is
good time to point your domain to your server's public address, as DNS
changes take time to propagate.

Please type your domain below. Press enter to skip.
:
```

It would be nice to say, "Point your domain at 198.51.100.124"; it's in that `changed` line above, but it may not be obvious.

**Comment by wzyboy** [comment]
It would be good to print `{{ streisand_ipv4_address }}` in the prompt. But Ansible does not support templating in "prompt" module. If we print the address with a "debug" task before the prompt, the address ends up being even harder to notice than the "changed: xxx" line.

**Comment by cpu** [comment]
I'm going to close this for now since as @wzyboy points out it's pretty tricky with the way Ansible prompt works. If someone can figure out a way to do this I'd be happy to review a PR but unfortunately it's not as simple as putting the `{{ streisand_ipv4_address }}` into the prompt text :'(
