### ISSUE TITLE
L2TP connection does not complete on Android

### ISSUE THREAD

**Issue by nopdotcom** [StreisandEffect/streisand#990]
### Expected behavior:

By following the Android instructions in the gateway, I connect to my streisand server using L2TP.

### Actual Behavior:

On Android, the connection never completes; the VPN tab shows "Unsuccessful" after a minute or two.

Android, determined to make L2TP unfriendly, treats the PSK field as a password field with no "view" option. Great move.

### Ansible Information

* Ansible version: 2.3.1.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 66f27ec3befe21ba9e24ab492e536317cfd54e58
* Streisand Git clone has untracked changes: 
* Genesis role: genesis-amazon

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

----

I have no idea why it says the streisand git clone has untracked changes:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

$ git remote -v
origin	https://github.com/StreisandEffect/streisand.git (fetch)
origin	https://github.com/StreisandEffect/streisand.git (push)
```

**Comment by cpu** [comment]
> I have no idea why it says the streisand git clone has untracked changes:

It doesn't, `Streisand Git clone has untracked changes:` would be `Streisand Git clone has untracked changes: true` if so. I think I just didn't template the negative case well :-)

**Comment by nopdotcom** [comment]
I have been having random issues with this and can't reproduce reliably. I'm putting this on the back burner until it bites someone else. I'm leaving it open, because we need to test against this, at least during the next testing spree.

If you have this bug, please comment.

**Comment by genewitch** [comment]
I'm having this bug, android won't connect over cellular, and windows won't connect over DSL (win10 default VPN client) - i checked android to make sure it wasn't my VPN passthrough on my router.

I installed onto "existing server" using default settings; ubuntu 16.04.3. The existing server is in a datacenter and shouldn't have any restrictions (like NAT or whatever)

**Comment by genewitch** [comment]
if there's any other information i can provide out of band (build logs, stuff from the streisand instance itself) please let me know. I can try building a fresh streisand and see if it has the same issue. it could just be a kernel version issue...

**Comment by nopdotcom** [comment]
Thank you for the offer of logs. I may take you up on it in a bit.

I am currently using OpenVPN on Android. It's not optimal.

**Comment by nopdotcom** [comment]
OK, this is working for me now on Android--after a few tries initially. The failures look like this in `journalctl -f`:

```
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: pppd 2.4.7 started by root, uid 0
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: Using interface ppp0
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: Connect: ppp0 <--> /dev/pts/1
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: Peer streisand failed CHAP authentication
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: Connection terminated.
Nov 02 11:29:20 ip-172-31-32-173 pppd[27524]: Exit.
```

@genewitch, could you take another look at this? I think that we're running into an Android cut&paste problem. Which would be important to know, so we can document it.

**Comment by cpu** [comment]
@genewitch If you could reply to @nopdotcom's [last comment](https://github.com/StreisandEffect/streisand/issues/990#issuecomment-341395540) I would appreciate it!

**Comment by cpu** [comment]
There hasn't been a reply to the previous two requests for information. I'm going to close this issue for now since it doesn't appear to be actionable in the short term.
