### ISSUE TITLE
linode-python required for this module

### ISSUE THREAD

**Issue by mg0314a** [StreisandEffect/streisand#992]
Hi I receive the following error message running the Streisand script to create a new linode instance, please advise. Thank you

TASK [genesis-linode : Create the server] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "linode-python required for this module"}
        to retry, use: --limit @/mnt/c/Users/myusername/streisand/playbooks/linode.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1

Note: I also receive this warning message, not sure if related:  [WARNING]: Found both group and host with same name: localhost

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by cpu** [comment]
Hi @mg0314a,

I think you also found your way to `#streisand` on Freenode. Thanks for opening an issue here instead - that IRC channel isn't monitored/active.

Please provide answers to the new issue template questions (e.g. your client operating system, ansible version, etc). It makes it much, much easier to help!

> Note: I also receive this warning message, not sure if related: [WARNING]: Found both group and host with same name: localhost

That warning is not unusual and should be unrelated.

> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "linode-python required for this module"}

What does `pip show linode-python` say on your system? Did you install this pip module ahead of running `./streisand` as described in the Linode section of the [README prerequisites](https://github.com/StreisandEffect/streisand#prerequisites)?

**Comment by mg0314a** [comment]
Yes I had installed this pip module. From my research this appears to be a problem with Windows subsystem, which appears to not be compatible with linode-python.

**Comment by cpu** [comment]
Hi @mg0314a,

> From my research this appears to be a problem with Windows subsystem, which appears to not be compatible with linode-python.

Ahhh. That would make sense :-( I'm going to close this issue for now since we do not support the Windows Linux subsystem presently.

**Comment by habnabit** [comment]
I got this same message when I (accidentally) installed `ansible-playbook` as python 3 instead of python 2. I think there's other incompatibilites with doing the `./streisand` install with python 3.
