### ISSUE TITLE
Ubuntu 14.04 Ansible install errors with cryptography package

### ISSUE THREAD

**Issue by mg0314a** [StreisandEffect/streisand#997]
Hi is there a change in the cryptography package that is breaking Ansible installation? See messages below. Thank you.

Downloading/unpacking cryptography (from ansible)
  Downloading cryptography-2.1.1.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log

**Comment by cpu** [comment]
@mg0314a Please answer the questions from the new issue template. What Ansible version are you using? What is your python version? What is your host OS? Is this still using the Windows Linux subsystem?

**Comment by mg0314a** [comment]
Hi since I was having so much trouble I decided to use an existing Ubuntu linode and use that to configure the new streisand linode. Host OS Ubuntu 14.04 LTS. Python 2.7.6. The error message above was what I received when attempting to execute the command "sudo pip install ansible markupsafe". From doing some googling is it possible that some changes have been made to ansible that are causing ansible's cryptography setup to break? Thank you for your time.

**Comment by cpu** [comment]
Hi @mg0314a - Thanks for providing that info! 

One idea is to try `sudo pip install --upgrade pip setuptools` - I believe this might be related to an older version of setup tools.

> Host OS Ubuntu 14.04 LTS. 

Another idea is to use Ubuntu 16.04 for your builder Linode. That's the LTS version Streisand provisions and in general will be easier to use for running the provisioning scripts.

**Comment by mg0314a** [comment]
I had already tried the former, didn't work.

**Comment by cpu** [comment]
@mg0314a Ok, trying 16.04 is probably the best bet then. Alternatively, if you're still having trouble I recommend taking this support query to the Ansible project since this is a problem with installing Ansible on Ubuntu 14.04 and not related to the Streisand project (which depends on Ansible).

**Comment by mg0314a** [comment]
Installing ansible 2.2.3.0 works. But a newer version of ansible is required? What if I follow this person's advice and:

git reset --hard fa120fa6b172f13b0535434caa93d838d739762c

Source: https://github.com/StreisandEffect/streisand/issues/626

**Comment by cpu** [comment]
@mg0314a That's not good advice. You'll be running a fixed version of Streisand that's already old and obsolete and missing both features and bug fixes. Similarly it will provision a VPN instance that uses old software.

Have you tried using 16.04 and installing the up-to-date Ansible version that Streisand pins as a dependency?

**Comment by danvaida** [comment]
stumbled upon this issue while getting the same error as the OP, in an unrelated project. depending on your setup, you can try to fix it by updating `setuptools` (preferred) or using a [previous](https://github.com/pyca/cryptography/releases/tag/2.0.3) release of the `cryptography` package. hope this helps someone.

**Comment by daveadams** [comment]
Same here. I've had luck installing cryptography==2.0.3 explicitly before installing ansible.

**Comment by nopdotcom** [comment]
One thing that might be useful is a `pip list` from people who are seeing issues.

**Comment by daveadams** [comment]
Since the problem seems to be related to pip, this sequence works for me on the latest Ubuntu 14.04 AMI on EC2 (ami-6e29e714 in us-east-1) by ensuring I'm using the latest pip and not the Ubuntu-packaged pip:

# apt install python-setuptools
# easy_install pip
# pip install ansible

The same steps work on Ubuntu 16.04 as well.

**Comment by nopdotcom** [comment]
I've been installing upstream's `python-pip` package and then upgrading it to bootstrap the rest. I have no idea if that works on 14.04.

**Comment by nopdotcom** [comment]
Here's what I did on a (rather bare) Vultr 14.04 install:

```
apt-get install build-essential git python-dev libffi-dev libyaml-dev libssl-dev
apt-get install python-pip
pip install --upgrade pip
### pip moves from /usr/bin/pip to /usr/local/bin/pip. Tell the shell.
hash -r
pip install ansible
```

But @daveadams tool works just as well; I think it's a matter of taste as to where we pull libraries.
